/* Shared upgrade and hit rules: UI, targeting and projectiles consume the same profile. */
(() => {
  'use strict';
  const g=window.lastRail,D=window.GAME_DATA,B=D.BALANCE,C=window.COMBAT_CONFIG,W=window.WEAPON_UPGRADES,A=window.LAST_RAIL_SCENE;
  const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const old={};for(const k of ['turretStats','turretReadout','fireTurret','resolveProjectile','damageEnemy','onHullImpact','upgradeEquipment','upgradeCost','equipmentHTML','draw','update','newRun','updateCrew','healAfterStage','executeArmor','applyResult','stationAction'])old[k]=g[k].bind(g);
  g.enemySpeed=function(base){const m=C.mobility,bias=clamp((m.referenceHp-base.hp)/m.referenceHp*m.hpWeight-(base.armor||0)*m.armorWeight,m.min,m.max);return base.speed*m.global*(1+bias);};
  g.weaponProfile=function(eq){const out={damage:1,rate:1,heat:1,cooling:1,range:1,pierce:0,targets:1,knockback:0};for(const [tier,id]of Object.entries(eq.weaponBranches||{})){const d=W.tiers[tier]?.[id];if(!d)continue;for(const k of ['damage','rate','heat','cooling','range'])out[k]*=d[k]??1;out.pierce+=d.pierce||0;out.targets=Math.max(out.targets,d.targets||1);out.knockback+=d.knockback||0;}return out;};
  g.turretCooling=function(eq,ci){const operate=this.crewForCar(ci).reduce((sum,c)=>sum+this.effectiveStat(c,'operate'),0),mod=clamp(operate*B.heat.operatorCoolingBonusPerPoint,0,B.heat.maxOperatorModifier);return D.TURRETS[eq.type].cool*(1+mod)*this.moduleEffect(ci,'cooling','coolingMult')*this.weaponProfile(eq).cooling;};
  g.turretStats=function(eq,ci,op){const stats=old.turretStats(eq,ci,op),p=this.weaponProfile(eq);stats.damage*=p.damage;stats.interval/=p.rate;stats.heat*=p.heat;stats.armorPierce=clamp(stats.armorPierce+p.pierce,0,1);stats.targets=p.targets;stats.knockback=p.knockback;return stats;};
  g.rangeBounds=function(t,eq){const focus=this.state.orders.focus.active>0?B.focus.rangeBonus+(Number(this.meta.upgrades.focus)||0)*B.meta.focusRangeBonus:0,p=eq?this.weaponProfile(eq):{range:1};return{min:t.minRange?B.targeting[t.minRange]*p.range:0,max:B.targeting[t.range]*(1+focus)*p.range};};
  g.targetInRange=function(e,r){return 'destroyed' in e?r.max>=W.bossReach.near&&r.min<=W.bossReach.far:Math.max(0,e.x)>=r.min&&Math.max(0,e.x)<=r.max;};
  g.turretTargets=function(t,eq){const r=this.rangeBounds(t,eq);return [...this.state.enemies,...(this.state.battle?.parts||[])].filter(e=>!e.dead&&!e.destroyed&&this.enemyOnScreen(e)&&this.targetInRange(e,r)).sort((a,b)=>a.x-b.x);};
  g.pickTurretTarget=function(ci,t,eq){const targets=this.turretTargets(t,eq),focus=this.state.orders.focus;if(focus.active>0){const target=targets.find(e=>e.id===focus.target);if(target)return target;}return targets.find(e=>!('destroyed' in e))||targets.find(e=>e.victory)||targets[0]||null;};
  g.fireTurret=function(eq,stats,target,ci){const targets=[target,...this.turretTargets(D.TURRETS[eq.type],eq).filter(e=>e.id!==target.id)].slice(0,stats.targets||1);for(const t of targets)old.fireTurret(eq,stats,t,ci);};
  g.turretReadout=function(eq,ci){const out=old.turretReadout(eq,ci),p=this.weaponProfile(eq);for(const row of out.rows){if(row[0]==='초당 냉각')row[2]=this.turretCooling(eq,ci)*(this.state.cars[ci].armor>0?B.armor.coolingMultiplier:1);if(row[0]==='최대 사거리')row[2]=this.rangeBounds(D.TURRETS[eq.type],eq).max;}out.rows.push(['동시 조준 대상',1,p.targets,false]);return out;};
  g.weaponUpgradePlan=function(eq){const level=eq.level||1;for(const tier of Object.keys(W.tiers).map(Number).sort((a,b)=>a-b))if(level>=tier&&!eq.weaponBranches?.[tier])return{level,tier,cost:0};if(level>=W.maxLevel)return null;const next=level+1;return{level:next,tier:W.tiers[next]?next:null,cost:W.costs[next]};};
  g.equipmentUpgradeSeconds=function(eq){const branching=eq.kind==='turret'?!!this.weaponUpgradePlan(eq)?.tier:D.MODULES[eq.type].upgradeable!==false&&(eq.level||1)>=2&&!eq.model;return branching?B.station.actionSeconds.upgrade:0;};
  g.upgradeCost=function(eq){return eq.kind==='turret'?this.weaponUpgradePlan(eq)?.cost??null:old.upgradeCost(eq);};
  function branchWarning(){const parent=$('#inspector');parent.querySelector('.branch-warning')?.remove();const p=document.createElement('p');p.className='negative branch-warning';p.setAttribute('role','alert');p.textContent='분기 강화는 정비 스테이션에서만 가능합니다.';parent.prepend(p);g.playSound('error');}
  g.upgradeEquipment=function(id,choice){const eq=this.findEquipment(id);if(!eq)return false;
    if(eq.kind==='module'){if((eq.level||1)>=2&&!eq.model&&this.mode!=='station'){branchWarning();return false;}return old.upgradeEquipment(id,choice);}
    const plan=this.weaponUpgradePlan(eq);if(!plan)return false;if(plan.tier&&this.mode!=='station'){branchWarning();return false;}if(plan.tier&&!W.tiers[plan.tier][choice])return false;if(this.state.scrap<plan.cost){this.toast('고철이 부족합니다.');return false;}
    this.state.scrap-=plan.cost;eq.investedScrap=(eq.investedScrap||0)+plan.cost;eq.level=plan.level;eq.branch=false;eq.weaponBranches??={};if(plan.tier)eq.weaponBranches[plan.tier]=choice;this.renderAll();this.playSound('upgrade');return true;
  };
  g.upgradeHTML=function(){return this.state.cars.flatMap(c=>c.equipment.map(eq=>{const data=(eq.kind==='turret'?D.TURRETS:D.MODULES)[eq.type],plan=eq.kind==='turret'?this.weaponUpgradePlan(eq):null,cost=this.upgradeCost(eq),branches=eq.kind==='turret'?(plan?.tier?W.tiers[plan.tier]:null):((eq.level||1)>=2&&!eq.model?B.moduleUpgrade.branches:null);let buttons='';
    if(cost===null)buttons=`<button disabled>${data.upgradeable===false?'강화 불가':'최대 강화 완료'}</button>`;else if(branches&&this.mode==='station')buttons=Object.entries(branches).map(([id,d])=>`<button data-upgrade-id="${eq.id}" data-module-model="${id}" title="${d.text||`효과량 ×${d.factor} / ${d.range==='all'?'모든 객차':d.range==='self'?'현재 객차':'기본 범위'}`}">${d.name} · ▰ ${cost}</button>`).join('');else buttons=`<button data-upgrade-id="${eq.id}">${branches?'분기 강화 · 정비소 전용':`Lv.${(eq.level||1)+1} 강화 · ▰ ${cost}`}</button>`;
    return `<article class="upgrade-entry"><b>${data.name} Lv.${eq.level||1} · ${c.name}</b>${buttons}${this.mode==='station'&&cost!==null?this.timeHTML(this.equipmentUpgradeSeconds(eq)): ''} </article>`;})).join('')||'<p>강화할 장비가 없습니다.</p>';};
  g.equipmentHTML=function(eq,ci){let html=old.equipmentHTML(eq,ci);if(eq.kind==='turret'){const branches=Object.entries(eq.weaponBranches||{}).map(([tier,id])=>{const d=W.tiers[tier]?.[id];return d?`<p>Lv.${tier} · ${d.name}: ${d.text}</p>`:'';}).join('');html+=branches;if(this.weaponProfile(eq).knockback)html+='<p>보스는 후퇴 면역입니다.</p>';}return html;};

  // Floating numbers use effective HP differences, with a short aggregation window.
  let numbers=[],ricochets=[],clock=0,lastState=null,shot=null;
  const floatCanvas=document.createElement('canvas');floatCanvas.setAttribute('aria-hidden','true');floatCanvas.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:18';document.body.append(floatCanvas);
  function carPoint(i){const p=A.getCarPosition(i);return p||{x:g.view.w/2,y:g.view.h*.7};}
  function crewPoint(c){const el=$(`[data-crew="${c.id}"]`)||$(`.moving-sprite[data-id="${c.id}"]`);if(el){const r=el.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top};}return carPoint(c.car);}
  function number(key,amount,p,color,positive=false){if(!(amount>0))return;let n=numbers.find(n=>n.key===key&&clock-n.born<W.numbers.mergeSeconds);if(n){n.amount+=amount;return;}numbers.push({key,amount,x:p.x/g.view.w,y:p.y/g.view.h,color,positive,born:clock});if(numbers.length>W.numbers.max)numbers.shift();}
  function snapshot(){const s=g.state;return s?{state:s,cars:s.cars.map(c=>c.hp),crew:s.crew.map(c=>({id:c.id,hp:c.hp}))}:null;}
  function changes(before,onlyHealing=false){const s=g.state;if(!before||s!==before.state)return;before.cars.forEach((hp,i)=>{const delta=s.cars[i].hp-hp;if(delta>0)number('carheal'+i,delta,carPoint(i),'#8dffa6',true);else if(delta<0&&!onlyHealing)number('carhit'+i,-delta,carPoint(i),'#ff6f6f');});for(const prev of before.crew){const c=s.crew.find(c=>c.id===prev.id);if(!c)continue;const delta=c.hp-prev.hp;if(delta>0)number('crewheal'+c.id,delta,crewPoint(c),'#8dffa6',true);else if(delta<0&&!onlyHealing)number('crewhit'+c.id,-delta,crewPoint(c),'#ff6f6f');}}
  g.onHullImpact=function(ci,before){old.onHullImpact(ci,before);const s=this.state;number('carhit'+ci,Math.max(0,before.car-s.cars[ci].hp),carPoint(ci),'#ff6f6f');for(const p of before.crew){const c=s.crew.find(c=>c.id===p.id);if(c)number('crewhit'+c.id,Math.max(0,p.hp-c.hp),crewPoint(c),'#ff6f6f');}};
  for(const method of ['updateCrew','healAfterStage','executeArmor','applyResult','stationAction'])g[method]=function(...args){const before=snapshot(),result=old[method](...args);changes(before,method==='updateCrew');return result;};
  g.resolveProjectile=function(p){const previous=shot;shot=p;try{return old.resolveProjectile(p);}finally{shot=previous;}};
  g.damageEnemy=function(e,amount,pierce=0){if(!e)return;const hp=e.hp,pos=A.project(e,this.view.w,this.view.h);old.damageEnemy(e,amount,pierce);const actual=Math.max(0,hp-e.hp);number('enemy'+e.id,actual,pos,'#ffffff');if(actual>0&&shot&&!shot.hostile&&(e.armor||0)>pierce){ricochets.push({x:pos.x/this.view.w,y:pos.y/this.view.h,born:clock,angle:-Math.PI*.8+Math.random()});if(ricochets.length>W.ricochet.max)ricochets.shift();this.playSound('metal');}
    if(actual>0&&shot?.stats?.knockback&&!e.dead&&!('destroyed' in e)){e.boarded=false;e.x=Math.min(e.entryStart||W.knockbackMaxDistance,e.x+shot.stats.knockback);e.attackTimer=Math.max(e.attackTimer,e.interval);}
  };
  g.update=function(dt){if(this.state!==lastState){lastState=this.state;numbers=[];ricochets=[];}old.update(dt);if(!document.hidden&&!this.sceneTransition){const battle=this.mode==='battle',paused=battle&&($('#overlay').classList.contains('show')||!this.state?.speed);if(!paused)clock+=dt*(battle?(this.state?.speed||0):1);}numbers=numbers.filter(n=>clock-n.born<W.numbers.seconds);ricochets=ricochets.filter(n=>clock-n.born<W.ricochet.seconds);};
  g.draw=function(){old.draw();const w=this.view.w,h=this.view.h,ratio=Math.min(devicePixelRatio||1,2);if(floatCanvas.width!==Math.round(w*ratio)||floatCanvas.height!==Math.round(h*ratio)){floatCanvas.width=Math.round(w*ratio);floatCanvas.height=Math.round(h*ratio);floatCanvas.style.width=`${w}px`;floatCanvas.style.height=`${h}px`;}const ctx=floatCanvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,w,h);if(!this.state||this.sceneTransition)return;ctx.save();ctx.font='bold 16px sans-serif';ctx.textAlign='center';ctx.lineWidth=3;for(const n of numbers){const age=clock-n.born;ctx.globalAlpha=clamp(1-age/W.numbers.seconds,0,1);ctx.fillStyle=n.color;ctx.strokeStyle='#07171de6';const text=(n.positive?'+':'−')+(Math.round(n.amount*10)/10).toFixed(1).replace(/\.0$/,'');ctx.strokeText(text,n.x*w,n.y*h-age*W.numbers.rise);ctx.fillText(text,n.x*w,n.y*h-age*W.numbers.rise);}
    for(const r of ricochets){const t=(clock-r.born)/W.ricochet.seconds,x=r.x*w,y=r.y*h;ctx.globalAlpha=1-t;ctx.strokeStyle='#fff0b8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+Math.cos(r.angle)*W.ricochet.length*Math.max(0,t-.3),y+Math.sin(r.angle)*W.ricochet.length*Math.max(0,t-.3));ctx.lineTo(x+Math.cos(r.angle)*W.ricochet.length*t,y+Math.sin(r.angle)*W.ricochet.length*t);ctx.stroke();}ctx.restore();};
})();
