/* Device-local knowledge is separate from run progression and event transactions. */
(()=>{
 const g=lastRail,D=GAME_DATA,B=D.BALANCE,C=EVENT_CONFIG,R=REVISION_CONFIG,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>typeof v==='number'?Number(v.toFixed(3)):v,key='lastRailCodexV2';
 let book;try{book=JSON.parse(localStorage.getItem(key));}catch{}book??={gear:[],enemies:[],crew:[],skills:[],events:[],results:{}};for(const k of ['gear','enemies','crew','skills','events'])book[k]??=[];book.results??={};
 function save(){try{localStorage.setItem(key,JSON.stringify(book));}catch{g.toast('도감 기록을 저장할 공간이 없습니다.');}}
 g.recordEncounter=function(kind,id){if(!book[kind]||book[kind].includes(id))return;book[kind].push(id);save();};
 g.recordEventResult=function(id,choice,index){this.recordEncounter('events',id);const k=id+':'+choice;book.results[k]??=[];if(!book.results[k].includes(index)){book.results[k].push(index);save();}};
 function crew(c){g.recordEncounter('crew',c.name);for(const t of c.traits)g.recordEncounter('skills',t);}
 const equipmentHTML=g.equipmentHTML.bind(g);g.equipmentHTML=function(e,...a){this.recordEncounter('gear',e.kind+':'+e.type);return equipmentHTML(e,...a);};
 const crewHTML=g.crewHTML.bind(g);g.crewHTML=function(c,...a){if(c.id)crew(c);return crewHTML(c,...a);};
 function train(){if(!g.state)return;g.state.cars.forEach(c=>c.equipment.forEach(e=>g.recordEncounter('gear',e.kind+':'+e.type)));g.state.crew.forEach(crew);}
 const make=g.makeInitialState.bind(g);g.makeInitialState=function(){const s=make();s.cars.forEach(c=>c.equipment.forEach(e=>this.recordEncounter('gear',e.kind+':'+e.type)));s.crew.forEach(crew);return s;};
 const spawn=g.spawnEnemy.bind(g);g.spawnEnemy=function(...a){const r=spawn(...a);this.state.enemies.forEach(e=>this.recordEncounter('enemies',e.type));return r;};
 const boss=g.startBoss.bind(g);g.startBoss=function(id){const r=boss(id);this.recordEncounter('enemies','boss:'+id);return r;};
 const shop=g.renderStation.bind(g);g.renderStation=function(){shop();if(this.stationTab==='gear')this.stationOffers.gear.forEach(e=>this.recordEncounter('gear',e.kind+':'+e.id));if(this.stationTab==='crew')this.stationOffers.crew.forEach(crew);};
 const render=g.renderCars.bind(g);g.renderCars=function(){render();train();};
 function table(rows){return '<table class="codex-table"><tbody>'+rows.map(([a,b])=>`<tr><th>${esc(a)}</th><td>${esc(num(b))}</td></tr>`).join('')+'</tbody></table>';}
 function fold(name,html,known){return known?`<details class="codex-entry"><summary>${esc(name)}</summary>${html}</details>`:'<article class="codex-entry locked">미발견 · ???</article>';}
 const behavior={hook:'갈고리로 객차 수리 효율을 떨어뜨리고 승선 적 접근을 돕습니다.',power:'일정 시간 객차의 유효 전력을 감소시킵니다.',shield:'주변 적이 받는 피해를 감소시킵니다.',transport:'접근 후 승선병들을 하차시킵니다.',repair:'주변 적을 지속 수리합니다.',suppress:'연사와 모듈 효과를 억제합니다.',bomber:'선로 폭격으로 열차 속도를 감소시킵니다.',infiltrator:'승선 후 객차의 포탑·모듈 운용을 방해합니다.'};
 function gear(e){const d=(e.kind==='turret'?D.TURRETS:D.MODULES)[e.type];let html=g.equipmentHTML({...e,level:1,heat:0},null)+table([['기본 가격',d.price],['최대 강화',d.upgradeable===false?'강화 불가':e.kind==='turret'?WEAPON_UPGRADES.maxLevel:'레벨 3 분기'],['출력 0','사격·모듈 정지, 포탑 냉각 유지'],['출력 1','기본 성능'],['출력 2',`포탑 간격 ×${R.power[1].intervalMult}, 모듈 효과량 ×${R.modulePower[2]}`],['출력 3',`포탑 간격 ×${R.power[2].intervalMult}, 피해 ×${R.power[2].damageMult}, 발열 ×${R.power[2].heatMult}, 모듈 효과량 ×${R.modulePower[3]}`]]);
  if(e.kind==='turret'){html+=table([['탄환 수',d.pellets||1],['연쇄 수',d.chains||1],['연쇄 피해 비율',d.chainRatio||0],['광역 반경',(d.splash||0)*B.projectile.splashRadiusScale],['기본 DPS',d.damage*(d.pellets||1)/d.interval],['과열 한도 / 재개',`${B.heat.max} / ${B.heat.resumeAt}`],['냉각 공식',`보정 냉각량 ÷ (1 + ${R.heat.drag} × (현재 열 / 최대 열)^${R.heat.exponent})`],['개틀링 열 증폭',e.type==='gatling'?`발당 열 × (1 + ${R.heat.gatlingGrowth} × 현재 열 / 최대 열)`:'없음']]);for(const[tier,branches]of Object.entries(WEAPON_UPGRADES.tiers))html+=`<h4>Lv.${tier} · 정비소 전용 분기</h4>`+Object.values(branches).map(b=>`<p>${esc(b.name)}: ${esc(b.text)}</p>`).join('');html+='<p>실제 전투 수치는 장비를 클릭하면 직원·전력·모듈·강화·현재 열을 반영해 표시됩니다.</p>';}
  else if(d.upgradeable!==false)html+=Object.values(B.moduleUpgrade.branches).map(b=>`<p>${esc(b.name)} · 효과량 ×${b.factor} · 범위 ${esc(({self:'현재 객차',base:'기본 범위',all:'모든 객차'})[b.range])}</p>`).join('');return html;
 }
 function enemy(id,e){let html=table([['기본 HP',e.hp],['장갑',`${num((e.armor||0)*100)}%`],['객차 피해',e.carDamage],['직원 피해',e.crewDamage],['공격 간격 (초)',e.interval],['접근 속도',g.enemySpeed(e)],['원거리 / 승선',`${e.ranged?'원거리':'근접'} / ${e.boards?'승선 가능':'승선 없음'}`],['공격 사거리',e.attackRange??'접근 후'],['전투 예산 비용',e.threatCost],['역할',(e.tags||[]).join(' / ')]])+`<p>${esc(behavior[e.behavior]||'접근 후 열차 또는 직원을 공격합니다.')}</p>`;
  if(e.elite&&g.eliteCodexHTML)html+=g.eliteCodexHTML(id);
  const tuning=ACT2_CONFIG[e.behavior];if(tuning)html+=table(Object.entries(tuning).map(([k,v])=>[({'repairMultiplier':'객차 수리 배율',boardingSpeed:'승선 접근 배율',radius:'효과 반경',damageMultiplier:'받는 피해 배율',hpPerSecond:'초당 회복',seconds:'지속 시간',amount:'감소 전력',count:'하차 인원',range:'발동 거리'})[k]||k,typeof v==='object'?JSON.stringify(v):v]));
  html+='<p>최종 피해 = 공격 피해 × (1 − 장갑 × (1 − 관통)). 구간별 HP·공격 배율이 추가 적용됩니다.</p><details><summary>구간별 HP / 피해 배율</summary>'+table(D.STAGE_CURVE.map((c,i)=>[`ACT ${i<R.stages?'I':'II'}-${i%R.stages+1}`,`HP ×${num(c.hp)} / 피해 ×${num(c.damage)}`]))+`<p>정예전: 위 배율에 HP ×${num(R.elite.hp*B.battle.eliteHp)}, 피해 ×${num(R.elite.damage*B.battle.eliteDamage)} 추가.</p></details>`;return html;
 }
 function reward(r={}){const names={money:'돈',scrap:'고철',relics:'고대 잔해',distance:'타이탄 거리 (km)',moneyLoss:'돈 손실',carDamage:'객차 HP 손실',crewDamage:'직원 HP 손실',actorDamage:'출전 직원 HP 손실',engineDamage:'기관실 HP 손실',carCount:'피해 객차 수',crewCount:'피해 직원 수',gear:'장비 종류',candidates:'직원 후보 수',repairRatio:'최대 객차 HP 회복 비율',healRatio:'최대 직원 HP 회복 비율',healCrew:'직원 HP 회복',temporaryEngine:'다음 전투 엔진 속도 배율',shop:'거래소',shopFactor:'상점 가격 배율',freeItem:'상품 1개 무료',disableGear:'무작위 장비 다음 전투 정지',routeInfo:'다음 경로 정보',buff:'런 한정 무작위 강화',debuff:'런 한정 무작위 약화',medicalRescue:'의무병 구조',possibleCandidate:'추가 직원 후보',possibleRareGear:'희귀 장비',possibleTalent:'전투 재능',labReward:'실험실 무작위 보상'};
  let rows=Object.entries(r).map(([k,v])=>[names[k]||k,Array.isArray(v)?v.join(' ~ '):v===true?'있음':v]);if(r.possibleCandidate)rows.push(['후보 확률',C.candidateChance*100+'%']);if(r.possibleRareGear)rows.push(['희귀 장비 확률',C.rareGearChance*100+'%']);if(r.possibleTalent)rows.push(['재능 확률',C.talentChance*100+'%']);if(r.candidates||r.medicalRescue)rows.push(['성급 1/2/3 확률',(r.medicalRescue?C.medicalStars:C.survivorStars).map(v=>v*100+'%').join(' / ')],['초기 HP',C.survivorHp.map(v=>v*100+'%').join(' ~ ')]);if(r.buff)rows.push(...Object.entries(C.buffs).map(([k,v])=>[k,v]));if(r.debuff)rows.push(...Object.entries(C.debuffs).map(([k,v])=>[k,v]));if(r.labReward)rows.push(['균등 무작위','잔해 4 / 희귀 모듈 / 무료 포탑 강화권']);return table(rows);
 }
 function event(e){return `<p>${esc(e.text)}</p>`+e.choices.map(c=>{const seen=book.results[e.id+':'+c.id],p=c.chance;return `<details><summary>${esc(c.label)} ${seen?'':'🔒 결과 미발견'}</summary>${table([['거리 비용',c.time+' km'],...Object.entries(c.cost||{}).map(([k,v])=>[k,v])])}${reward(c.reward)}${seen?table([['기본 성공률',p===undefined?'결과별 가중치':p*100+'%'],...(c.scholarChance?[['연구자 성공률',c.scholarChance*100+'%']]:[]),...(c.skill?[['능력 보정',`${c.skill} 5 기준 ±1당 ${C.skill.step*100}%p (최소 ${C.skill.min*100}%, 최대 ${C.skill.max*100}%)`]]:[]),...(c.engineChance?[['엔진 보정',`출력 ${C.engine.powerReference} 기준 ±1당 ${C.engine.powerStep*100}%p, 손상 비율 ×${C.engine.hullStep*100}%p 감소`]]:[])])+((c.outcomes||[]).map((o,i)=>seen.includes(i)?`<h4>${esc(o.title)}</h4><p>${esc(o.text)}</p>${p===undefined?'<p>확률 '+num(o.weight/c.outcomes.reduce((n,o)=>n+o.weight,0)*100)+'%</p>':''}${reward(o.reward)}`:'<p class="locked">미경험 결과 🔒</p>').join('')):'<p class="locked">이 행동을 선택하면 확률과 경험한 결과가 기록됩니다.</p>'}</details>`;}).join('');}
 let tab='gear';g.showCodex=function(){train();const m=this.modalShell('도감','발견 기록',''),body=m.querySelector('.dialog-body');m.classList.add('codex-modal');body.innerHTML='<nav class="codex-tabs">'+[['gear','장비'],['enemies','적'],['crew','직원'],['events','이벤트']].map(([id,label])=>`<button data-codex-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')+'</nav><div id="codex-content"></div>';let html='';
  if(tab==='gear')for(const kind of ['turret','module'])for(const[type,d]of Object.entries(kind==='turret'?D.TURRETS:D.MODULES))html+=fold(d.name,book.gear.includes(kind+':'+type)?gear({kind,type}):'',book.gear.includes(kind+':'+type));
  if(tab==='enemies'){for(const[id,e]of Object.entries(D.ENEMIES))html+=fold(e.name,book.enemies.includes(id)?enemy(id,e):'',book.enemies.includes(id));for(const[id,b]of Object.entries(D.BOSSES))html+=fold(b.name,g.bossCodexHTML?g.bossCodexHTML(id):table(b.parts.map(p=>[p.name,`HP ${p.hp}`])),book.enemies.includes('boss:'+id));}
  if(tab==='crew'){html='<h3>직원</h3>';for(const c of D.CREW_TEMPLATES)html+=fold(c.name,g.crewHTML({...c,traits:[],stars:1,level:1},false)+'<p>1성 기본 분포. 타고난 2성은 총 +5, 3성은 총 +13. 고레벨 영입은 추가 무작위 배분.</p>',book.crew.includes(c.name));html+='<h3>능력과 성장</h3>'+table(Object.entries(g.crewStatGuides()))+'<h3>재능</h3>';for(const[id,t]of Object.entries(D.TRAITS))html+=fold(t.name,'<p>'+esc(t.text)+'</p>',book.skills.includes(id));}
  if(tab==='events')for(const e of C.events)html+=fold(e.title,book.events.includes(e.id)?event(e):'',book.events.includes(e.id));$('#codex-content').innerHTML=html;body.querySelectorAll('[data-codex-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.codexTab;this.showCodex();});};
 const css=document.createElement('style');css.textContent='.codex-modal{max-height:90dvh;overflow:auto}.codex-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}.codex-tabs button{padding:12px 20px;background:#243f46;color:#eee;border:1px solid #7e9e9b;border-radius:5px}.codex-tabs [aria-pressed=true]{border-color:#dfc580;background:#526059}.codex-entry{padding:14px;border:1px solid #627f7a;border-radius:6px;margin:10px 0}.codex-entry summary{cursor:pointer;word-break:keep-all}.codex-entry details{padding:12px 0}.codex-table{width:100%;border-collapse:collapse;margin:12px 0;table-layout:fixed}.codex-table th,.codex-table td{padding:8px;text-align:left;word-break:keep-all;overflow-wrap:anywhere;border-bottom:1px solid #8fa49d33}.codex-table th{width:38%;color:#bccdc3}.locked{color:#a2aaaa;background:#ffffff07}.codex-entry .stat-grid{display:grid;grid-template-columns:repeat(4,1fr)}';document.head.append(css);
 train();
 for(const id of g.meta.discovered?.enemies||[])if(D.ENEMIES[id])g.recordEncounter('enemies',id);
 try{const saved=JSON.parse(localStorage.getItem(C.storageKey));if(saved?.session){const s=saved.session;g.recordEncounter('events',s.eventId);if(s.selected&&['result','receipt','candidate','placement','shop','finish','leaving'].includes(s.phase))g.recordEventResult(s.eventId,s.selected,s.chosenOutcome??-1);}}catch{}
})();
