/* Skill effects use the same combat / equipment / event paths as existing talents. */
(()=>{
 const g=lastRail,D=GAME_DATA,B=D.BALANCE,C=CREW_SKILLS_CONFIG,P=PROGRESSION_CONFIG;
 const active=c=>c&&!c.dead&&c.hp>0&&!c.moving,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 g.normalizeCrewSkills=function(c){const valid=id=>!!D.TRAITS[id],unique=a=>[...new Set(a||[])].filter(valid);c.starTraits=unique(c.starTraits||c.normalSkills||c.traits).filter(id=>D.TRAITS[id].canBeNormalSkill!==false&&!D.TRAITS[id].captainOnly).slice(0,Math.max(0,(c.stars||1)-1));const event=c.eventSkill??c.eventTraits?.[0];c.eventSkill=valid(event)&&!c.starTraits.includes(event)?event:null;c.eventTraits=c.eventSkill?[c.eventSkill]:[];c.normalSkills=c.starTraits;c.traits=[...c.starTraits,...c.eventTraits,...(c.captain?['fieldCaptain']:[])];return c;};
 g.setEventSkill=function(c,id){this.normalizeCrewSkills(c);if(!D.TRAITS[id]?.canBeEventSkill||c.traits.includes(id))return false;c.eventSkill=id;c.eventTraits=[id];c.traits=[...c.starTraits,id,...(c.captain?['fieldCaptain']:[])];this.recordEncounter?.('skills',id);this.playSound('upgrade');return true;};
 g.skillValue=function(c,key){return(c.traits||[]).reduce((n,id)=>n+(Number(D.TRAITS[id]?.effect?.[key])||0),0);};
 const val=(c,k)=>g.skillValue(c,k),crew=ci=>g.crewForCar(ci),sum=(ci,key,except)=>Math.min(C.maxSupport,crew(ci).filter(c=>c!==except).reduce((n,c)=>n+val(c,key),0));
 const burning=ci=>(g.state?.battle?.fires||[]).some(f=>f.car===ci&&f.left>0);
 const elite=e=>!!D.ENEMIES[e.type]?.elite;
 const eliteAlive=()=>g.state.enemies.some(e=>!e.dead&&elite(e));
 let weapon=null,personal=null,projectile=null;
 const stat=g.effectiveStat.bind(g);g.effectiveStat=function(c,key){let n=stat(c,key);if(!this.state||!this.state.cars[c.car]||!active(c))return n;const car=this.state.cars[c.car],friends=crew(c.car),hp=car.hp/car.maxHp;let bonus=0;
  if(['combat','repair','operate'].includes(key)){if(friends.length===1)bonus+=val(c,'solo');if(friends.length>1)bonus+=val(c,'partnerStats');if(hp<=C.lastHull)bonus+=val(c,'lastStats');}
  if(['combat','repair'].includes(key)){if(burning(c.car))bonus+=val(c,'burningStats');if(c.car<=1)bonus+=val(c,'frontStats');}
  if(key==='combat')bonus+=sum(c.car,'combatAura');
  if(key==='repair'){bonus+=val(c,'woundedRepair')*(1-clamp(hp,0,1))+sum(c.car,'repairAura',c);if(hp<=C.lowHull)bonus+=val(c,'lowRepair');}
  if(key==='operate'){bonus+=val(c,'operate');if(this.effectiveCarPower(c.car)>=2)bonus+=val(c,'poweredOperate');if(weapon)bonus+=val(c,'weaponOperate');if(car.equipment.some(e=>e.ancient||(e.kind==='turret'?D.TURRETS:D.MODULES)[e.type]?.ancient||C.ancientTypes.includes(e.type)))bonus+=val(c,'ancientOperate');}
  return n*(1+Math.min(C.maxStatBonus,bonus));
 };
 const stats=g.turretStats.bind(g);g.turretStats=function(eq,ci,...args){const prev=weapon;weapon=eq;try{const s=stats(eq,ci,...args),hot=eq.heat>=(EQUIPMENT_REFORM.turret[eq.type]?.high??B.heat.max);if(this.state.orders.focus.active>0){s.damage*=1+sum(ci,'focusDamage');s.interval/=1+sum(ci,'focusRate');}if(hot){s.damage*=1+sum(ci,'hotDamage');s.interval/=1+sum(ci,'hotRate');}return s;}finally{weapon=prev;}};
 const cool=g.turretCooling.bind(g);g.turretCooling=function(eq,ci){const prev=weapon;weapon=eq;try{return cool(eq,ci)*(1+sum(ci,'cooling'));}finally{weapon=prev;}};
 const range=g.rangeBounds.bind(g);g.rangeBounds=function(t,eq){const r=range(t,eq),ci=eq?this.equipmentLocation(eq):-1;if(ci>=0)r.max*=1+sum(ci,'turretRange');return r;};
 g.crewFireRate=c=>1+val(c,'rate');
 g.crewAttack=function(c,e,amount,pierce=0){const previous=personal;personal=c;try{let bonus=0;if(e.boarded)bonus+=val(c,'boardDamage');if(e.boarded||e.grip>0||e.x<=C.closeRange)bonus+=val(c,'closeDamage');if(elite(e))bonus+=val(c,'eliteDamage');if(D.ENEMIES[e.type]?.family==='drone'||/drone/i.test(e.type))bonus+=val(c,'droneDamage');if(c.skillStay>=C.stanceSeconds)bonus+=val(c,'stanceDamage');return this.damageEnemy(e,amount*(1+Math.min(C.maxWeaponBonus,bonus)),Math.min(1,pierce+val(c,'pierce')));}finally{personal=previous;}};
 for(const name of ['crewReturnFire','bossCrewReturnFire']){const old=g[name].bind(g);g[name]=function(c,dt){const r=P.returnFire.range;P.returnFire.range=r*(1+val(c,'range')+(c.skillStay>=C.stanceSeconds?val(c,'stanceRange'):0));try{return old(c,dt*this.crewFireRate(c));}finally{P.returnFire.range=r;}};}
 const move=g.crewMoveMultiplier.bind(g);g.crewMoveMultiplier=c=>move()*(1+(c?val(c,'move')+(eliteAlive()?val(c,'eliteMove'):0):0));
 g.crewRestorationMultiplier=c=>1+val(c,'restoration');
 g.fireLifetimeMultiplier=ci=>1+sum(ci,'fireClear');
 g.hurtCrew=function(c,amount,kind='attack'){if(!c||c.dead||c.hp<=0)return 0;let reduction=sum(c.car,'guard',c);if(kind==='boarded')reduction+=val(c,'boardDefense');if(kind==='fire')reduction+=Math.min(C.fireReductionCap,val(c,'fireDefense'));if(this.state.cars[c.car].hp/this.state.cars[c.car].maxHp<=C.lowHull)reduction+=val(c,'lowDefense');const before=c.hp;let next=Math.max(0,before-Math.max(0,amount)*(1-Math.min(kind==='fire'?C.fireReductionCap:C.maxDamageReduction,reduction)));if(next<=0&&val(c,'tough')&&!c.skillToughUsed&&before/c.maxHp>=C.toughHp){next=C.toughRemain;c.skillToughUsed=true;this.playSound('armor');}c.hp=next;return before-next;};
 function healthSnapshot(){return{state:g.state,cars:g.state.cars.map(c=>c.hp),crew:g.state.crew.map(c=>({id:c.id,hp:c.hp}))};}
 const update=g.updateCrew.bind(g);g.updateCrew=function(dt){for(const c of this.state.crew){if(c.moving||c.skillCar!==c.car){c.skillStay=0;c.skillCar=c.car;}else if(active(c))c.skillStay=(c.skillStay||0)+dt;}update(dt);const before=healthSnapshot();for(const c of this.state.crew)if(active(c)&&val(c,'firstAid')&&!c.skillAidUsed&&c.hp/c.maxHp<=C.firstAidHp){c.skillAidUsed=true;c.hp=Math.min(c.maxHp,c.hp+c.maxHp*C.firstAidHeal);this.playSound('heal');}this.reportHealthChanges?.(before,true);};
 const hull=g.onHullImpact.bind(g);g.onHullImpact=function(ci,...args){const car=this.state.cars[ci];if(car.hp<=0)for(const c of crew(ci)){if(!val(c,'escape')||this.bossCrewStopped?.(c))continue;const dest=[ci-1,ci+1].find(i=>this.state.cars[i]?.hp>0&&this.state.crew.filter(x=>!x.dead&&(x.moving?.to??x.car)===i).length<this.crewCapacity(i));if(dest!==undefined)this.moveCrew(c.id,dest);}return hull(ci,...args);};
 for(const name of ['startBattle','startBoss']){const old=g[name].bind(g);g[name]=function(...args){for(const c of this.state.crew){this.normalizeCrewSkills(c);c.skillAidUsed=false;c.skillToughUsed=false;c.skillStay=0;c.skillCar=c.car;}return old(...args);};}
 const heal=g.healAfterStage.bind(g);g.healAfterStage=function(...args){const before=healthSnapshot();for(const [ci,car]of this.state.cars.entries())if(car.hp>0)car.hp=Math.min(car.maxHp,car.hp+car.maxHp*sum(ci,'afterRepair'));const r=heal(...args);this.reportHealthChanges?.(before,true);return r;};
 const resolve=g.resolveProjectile.bind(g);g.resolveProjectile=function(p){const prev=projectile;projectile=p;try{return resolve(p);}finally{projectile=prev;}};
 const damage=g.damageEnemy.bind(g);g.damageEnemy=function(e,...args){const alive=e&&!e.dead&&!e.destroyed&&e.hp>0;const result=damage(e,...args);if(alive&&(e.dead||e.destroyed||e.hp<=0)&&!('destroyed'in e)&&(D.ENEMIES[e.type]?.mechanical??!['boarder','runner','infiltrator'].includes(e.type))){const owners=personal?[personal]:projectile&&!projectile.hostile&&Number.isInteger(projectile.from)?crew(projectile.from):[];for(const c of owners)if(val(c,'scrapChance')>Math.random()){this.state.scrap+=this.metaGain?.('scrap',val(c,'scrap'))??val(c,'scrap');this.toast(`${c.name} · 해체 고철 +${val(c,'scrap')}`);}}return result;};
 const xp=g.grantCrewXp.bind(g);g.grantCrewXp=function(c,...args){const result=xp(c,...args);this.normalizeCrewSkills(c);return result;};
 const init=g.makeInitialState.bind(g);g.makeInitialState=function(...args){const s=init(...args);s.crew.forEach(c=>this.normalizeCrewSkills(c));return s;};
 const shop=g.prepareActShop.bind(g);g.prepareActShop=function(...args){const r=shop(...args);this.stationOffers?.crew.forEach(c=>this.normalizeCrewSkills(c));return r;};
 const restore=g.restoreMetaRun.bind(g);g.restoreMetaRun=function(...args){const r=restore(...args);this.state.crew.forEach(c=>this.normalizeCrewSkills(c));return r;};
 g.skillDetailsHTML=id=>{const t=D.TRAITS[id];return t?`<details><summary>${esc(t.name)} · ${t.eventExclusive?'이벤트 전용':'일반 스킬'}</summary><p>${esc(t.text)}</p></details>`:'';};
 const html=g.crewHTML.bind(g);g.crewHTML=function(c,...args){this.normalizeCrewSkills(c);return html(c,...args).replace(/<div class="trait-guides">[\s\S]*?<\/div>/,'')+`<section class="crew-skill-list"><h4>일반 스킬 (${c.starTraits.length}/${Math.max(0,(c.stars||1)-1)})</h4>${c.starTraits.map(this.skillDetailsHTML).join('')||'<p>성급 상승 시 획득</p>'}<div class="crew-event-skill"><h4>◇ 이벤트 스킬 (최대 1개)</h4>${c.eventSkill?this.skillDetailsHTML(c.eventSkill):'<p>비어 있음 · 훈련/특별 사건에서 획득</p>'}</div></section>`;};
 const style=document.createElement('style');style.textContent='.crew-event-skill{border:1px solid #d8bd78;border-radius:8px;padding:10px;margin:10px 0}.crew-skill-list details{padding:8px;background:#ffffff08}.crew-skill-list summary{cursor:pointer}.crew-skill-list p{line-height:1.6}';document.head.append(style);
})();
