/* Data-driven special enemies plus discrete boarding/repair presentation. */
(() => {
 'use strict';
 const g=lastRail,D=GAME_DATA,B=D.BALANCE,C=ELITE_CONFIG,A=LAST_RAIL_SCENE;
 const old={};for(const k of ['startBattle','startBoss','updateSpawns','spawnEnemy','updateEnemies','enemyAttack','damageEnemy','resolveProjectile','turretTargets','effectiveCarPower','moduleData','projectBossEntity','inspectEnemy'])if(g[k])old[k]=g[k].bind(g);
 const live=e=>e&&!e.dead&&!e.destroyed,elite=e=>!!D.ENEMIES[e.type]?.elite,choose=a=>a[Math.floor(Math.random()*a.length)],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const nearby=(a,b,r)=>Math.hypot(a.x-b.x,(a.y-b.y)/B.projectile.laneSpan)<=r;
 const bstate=()=>g.state?.battle;
 const living=()=>g.state.enemies.filter(live);
 const data=e=>D.ENEMIES[e.type];
 const present=()=>g.mode==='battle';
 function reset(){const b=bstate();b.eliteShots=[];b.fires=[];b.eliteNotice=null;b.droneNextAt=0;for(const c of g.state.crew){c.workClock=0;c.workCar=c.car;} }
 for(const method of ['startBattle','startBoss'])g[method]=function(...args){const r=old[method](...args);reset();if(method==='startBattle'){const stage=this.globalStage(),f=C.frequency.filter(x=>x.stage<=stage).at(-1);bstate().elitePlan={left:f.count&&(bstate().elite||Math.random()<(f.chance??1))?f.count+(bstate().elite?C.eliteExtra:0):0,gap:f.gap,next:C.firstDelay};}return r;};
 const discovered=new Set();try{for(const id of JSON.parse(localStorage.getItem('lastRailEliteSeen')||'[]'))discovered.add(id);}catch{}
 function warn(e){const first=!discovered.has(e.type);bstate().eliteNotice={text:`${data(e).icon} ${first?'정예 적 발견 · ':''}${e.name}`,help:first?data(e).help:'',left:C.warningSeconds};discovered.add(e.type);try{localStorage.setItem('lastRailEliteSeen',JSON.stringify([...discovered]));}catch{}g.playSound('alarm');g.recordEncounter?.('enemies',e.type);}
 function cap(){const b=bstate(),late=g.globalStage()>=C.lateStage&&['CRISIS','FINAL'].includes(b.rhythm?.phase?.kind);return late?C.caps[b.elite?'lateElite':'lateNormal']:C.caps[(b.elite?'eliteA':'a')+(g.state.actId==='act2'?'ct2':'ct1')];}
 function valid(id){const list=living().filter(elite),ids=list.map(e=>e.type),d=D.ENEMIES[id],b=bstate();if(g.allowElite09&&!g.allowElite09(id,list))return false;if(ids.includes(id)||list.length>=(g.eliteCap09?.()??cap())||d.eliteMinStage>(g.eliteStage09?.()??g.globalStage()))return false;if(id==='stealthElite'&&(ids.includes(id)||b.elapsed<b.droneNextAt))return false;
   if(g.eliteComboAllowed09)return g.eliteComboAllowed09(id);
   const combo=[...ids,id];if(g.globalStage()<C.lateStage){if(combo.includes('sniperElite')&&combo.includes('fireElite'))return false;if(combo.filter(x=>['stealthElite','siegeElite','parasiteElite'].includes(x)).length>1)return false;if(living().filter(e=>e.boarded).length>=C.boarderDanger&&['sniperElite','fireElite'].includes(id))return false;}return true;
 }
 g.updateSpawns=function(dt){old.updateSpawns(dt);const b=bstate(),plan=b.elitePlan;if(!plan||!plan.left||(b.routeProgress??b.elapsed)>=b.duration||b.elapsed<plan.next||b.rhythm?.phase?.kind==='RECOVERY')return;const pool=Object.keys(D.ENEMIES).filter(id=>D.ENEMIES[id].elite&&valid(id));if(!pool.length)return;const id=choose(pool),d=D.ENEMIES[id],room=B.battle.maxAlive-living().length,required=d.specialBehavior==='bulwark'?1+d.escortMin:1;if(room<required)return;const e=this.spawnElite(id);if(e){plan.left--;plan.next=b.elapsed+plan.gap;}};
 g.spawnElite=function(id){if(!valid(id)||living().length>=B.battle.maxAlive)return null;const before=this.state.enemies.length;old.spawnEnemy(id);if(this.state.enemies.length===before)return null;const e=this.state.enemies.at(-1),d=data(e);Object.assign(e,{x:C.spawnDistance,entrySide:'horizon',eliteAge:0,attackTimer:d.interval,majorActive:true,baseArmor:e.armor,baseSpeed:e.speed,linkedSeconds:0,orderTimer:d.orderInterval||0});warn(e);
   if(d.specialBehavior==='bulwark'){const n=Math.min(B.battle.maxAlive-living().length,d.escortMin+Math.floor(Math.random()*(d.escortMax-d.escortMin+1)));for(let i=0;i<n;i++){const count=this.state.enemies.length;old.spawnEnemy('boarder');if(this.state.enemies.length>count){const escort=this.state.enemies.at(-1);escort.x=e.x;escort.y=clamp(e.y+(i-(n-1)/2)*C.escortSpacing,.25,.73);escort.targetCar=e.targetCar;escort.entrySide='horizon';}}}return e;
 };
 g.crewWorkStep=function(c,dt){if(c.workCar!==c.car){c.workClock=0;c.workCar=c.car;}c.workClock=(c.workClock||0)+dt;const steps=Math.floor((c.workClock+1e-9)/C.tick);if(!steps)return 0;c.workClock-=steps*C.tick;return steps*C.tick;};
 g.tickBoardedEnemy=function(e,dt){e.boardClock=(e.boardClock||0)+dt;while(e.boardClock+1e-9>=C.tick&&live(e)){e.boardClock-=C.tick;this.enemyAttack({...e,carDamage:e.carDamage*C.tick/e.interval,crewDamage:e.crewDamage*C.tick/e.interval});}};
 g.onCrewBoardShot=function(c,target){const q=A.project(target,this.view.w,this.view.h);c.returnFireVisual={x:q.x/this.view.w,y:q.y/this.view.h,life:C.shotVisual,hit:true};c.boardShot=C.shotVisual;this.playSound('shotCrack');};
 g.onCrewHammer=function(c){c.hammerVisual=C.shotVisual;this.playSound('hammer');};
 g.enemyAttack=function(e){if(elite(e))return;if(e.boarded){const owner=this.state.enemies.find(x=>x.id===e.id);if(owner)owner.boardShot=C.shotVisual;this.playSound('shotCrack');}return old.enemyAttack(e);};
 const project=old.projectBossEntity;
 g.projectBossEntity=function(e,w,h){if(e.boarded){const p=A.getCarPosition(e.targetCar);if(p){const list=this.state.enemies.filter(x=>live(x)&&x.boarded&&x.targetCar===e.targetCar),i=list.indexOf(e);return{x:p.x+(i-(list.length-1)/2)*C.boardVisual.spacing,y:p.y-C.boardVisual.roofOffset,scale:1,r:18};}}return project?.(e,w,h);};
 // Focus-only filtering is limited to turret AI: area hits and personal weapons remain valid.
 g.turretTargets=function(t,eq){const focus=this.state.orders.focus;return old.turretTargets(t,eq).filter(e=>data(e)?.targetingRule!=='focusOnly'||focus.active>0&&focus.target===e.id);};
 let projectile=null,redirecting=false;
 g.resolveProjectile=function(p){const prev=projectile;projectile=p;try{return old.resolveProjectile(p);}finally{projectile=prev;}};
 g.damageEnemy=function(e,amount,pierce=0){if(!live(e))return;const guard=!redirecting&&!e.bossPart&&!e.boarded&&(data(e)?.boards||data(e)?.behavior==='infiltrator'||e.type==='infiltrationTruck')&&!(projectile?.arc||projectile?.stats?.splash)?living().find(x=>data(x)?.specialBehavior==='bulwark'&&x!==e&&nearby(x,e,data(x).radius)):null;
   if(guard){const share=data(guard).transfer;redirecting=true;try{old.damageEnemy(guard,amount*share,pierce);}finally{redirecting=false;}amount*=1-share;}old.damageEnemy(e,amount,pierce);if(e.dead&&data(e)?.specialBehavior==='stealth')bstate().droneNextAt=bstate().elapsed+C.droneRest;
 };
 function snapshot(ci){return{car:g.state.cars[ci].hp,crew:g.state.crew.map(c=>({id:c.id,hp:c.hp,dead:c.dead}))};}
 function damageCar(ci,hp,crewAmount=0,victim=null,kind='attack'){const car=g.state.cars[ci];if(!car||car.armor>0)return;const before=snapshot(ci);car.hp=Math.max(0,car.hp-(g.absorbHullDamage?.(ci,hp)??hp));if(hp>0)car.hitFlash=B.feedback.carFlashSeconds;const occupants=g.state.crew.filter(c=>!c.dead&&!c.moving&&c.hp>0&&c.car===ci);for(const c of victim?[victim]:occupants){if(!c||c.dead||c.moving||c.car!==ci)continue;if(g.hurtCrew)g.hurtCrew(c,typeof crewAmount==='function'?crewAmount(c):crewAmount,kind);else c.hp=Math.max(0,c.hp-(typeof crewAmount==='function'?crewAmount(c):crewAmount));if(c.hp<=0&&car.hp<=0)c.dead=true;}
   if(car.hp<=0&&!car.destroyedLogged){car.destroyedLogged=true;g.log(`${car.name} 파괴!`,'bad');}g.onHullImpact(ci,before);
 }
 function target(){return g.pickTargetCar(false);}
 function staffTarget(e){let pool=g.state.crew.filter(c=>!c.dead&&!c.moving&&c.hp>0&&c.id!==e.lastStaff);if(!pool.length){e.lastStaff=null;return null;}const d=data(e),weight=c=>1+(1-c.hp/c.maxHp)*d.lowHpWeight+Math.max(0,g.effectiveStat(c,'operate'))*d.operateWeight+(g.state.cars[c.car].autoRepair?d.repairWeight:0);let roll=Math.random()*pool.reduce((n,c)=>n+weight(c),0);return pool.find(c=>(roll-=weight(c))<=0)||pool.at(-1);}
 function begin(e,kind){const d=data(e);if(kind==='sniper'){const c=staffTarget(e);if(!c){e.attackTimer=d.interval;return;}e.windup={left:d.windup,total:d.windup,kind,car:c.car,staff:c.id};}else{const car=target();if(kind==='fire'&&fireOccupied().size>=C.fireCaps[g.state.actId]){e.attackTimer=C.tick;return;}if(kind==='fire'&&fireOccupied().has(car)){e.attackTimer=C.tick;return;}e.windup={left:d.windup,total:d.windup,kind,car};}g.playSound('alarm');}
 function fireOccupied(){const s=new Set((bstate().fires||[]).filter(f=>f.left>0).map(f=>f.car));for(const e of living())if(e.windup?.kind==='fire')s.add(e.windup.car);for(const p of bstate().eliteShots||[])if(p.kind==='fire')s.add(p.car);return s;}
 function shoot(e,w){const d=data(e),p=A.project(e,g.view.w,g.view.h),to=A.getCarPosition(w.car);e.muzzle=C.shotVisual;e.attackTimer=d.interval;if(w.kind==='sniper'){const c=g.state.crew.find(c=>c.id===w.staff);e.lastStaff=w.staff;if(!c||c.moving||c.car!==w.car||c.hp<=0)return;damageCar(w.car,0,c.maxHp*d.crewRatio,c);g.playSound('enemyShot');}else if(w.kind==='siege'){damageCar(w.car,e.carDamage,e.crewDamage,choose(g.state.crew.filter(c=>!c.dead&&!c.moving&&c.car===w.car)));g.playSound('cannonBass');}
   if(to)bstate().eliteShots.push({kind:w.kind,car:w.car,start:{x:p.x/g.view.w,y:p.y/g.view.h},end:{x:to.x/g.view.w,y:(to.y-40)/g.view.h},left:w.kind==='fire'?d.flight:C.shotVisual,total:w.kind==='fire'?d.flight:C.shotVisual,data:d});if(w.kind==='fire')g.playSound('mortarShot');
 }
 function aura(e){return living().find(x=>data(x)?.specialBehavior==='command'&&x!==e&&!elite(e)&&!e.bossPart&&nearby(x,e,data(x).radius));}
 g.eliteAuraSource=aura;
 g.eliteHandlers={
   siege(e,dt){ranged(e,dt,'siege');},sniper(e,dt){ranged(e,dt,'sniper');},fire(e,dt){ranged(e,dt,'fire');},
   bulwark(e,dt){basic(e,dt);},
   parasite(e,dt){const d=data(e);if(e.x>d.hold)return;if(!e.linked||g.state.cars[e.targetCar]?.hp<=0){const choices=g.state.cars.map((c,i)=>({c,i})).filter(x=>x.c.hp>0).sort((a,b)=>b.c.power-a.c.power);e.targetCar=choices[0]?.i??target();}e.linked=true;e.linkedSeconds+=dt;const p=powerBase(e.targetCar),loss=Math.min(Math.max(0,p-1),e.linkedSeconds>=d.drainAfter?d.drainMax:1);e.drained=loss;e.armor=Math.min(d.maxArmor,e.baseArmor+loss*d.armorPerPower);},
   command(e,dt){basic(e,dt);e.orderTimer-=dt;e.orderLeft=Math.max(0,(e.orderLeft||0)-dt);if(e.orderTimer<=0){e.orderTimer=data(e).orderInterval;e.orderLeft=data(e).orderSeconds;e.order=choose(['charge','focus','escort']);e.orderCar=target();g.playSound('alarm');}},
   stealth(e,dt){e.eliteAge+=dt;e.x=Math.max(B.battle.boardDistance,C.spawnDistance-(C.spawnDistance-B.battle.boardDistance)*e.eliteAge/data(e).travel);if(e.eliteAge>=data(e).travel){damageCar(e.targetCar,g.state.cars[e.targetCar].hp*data(e).currentHpRatio);e.dead=true;e.deathTime=.35;bstate().droneNextAt=bstate().elapsed+C.droneRest;g.playSound('explosion');}}
 };
 function basic(e,dt){if(e.x>B.battle.boardDistance)return;e.attackTimer-=dt;if(e.attackTimer<=0){damageCar(e.targetCar,e.carDamage,e.crewDamage,choose(g.state.crew.filter(c=>!c.dead&&!c.moving&&c.car===e.targetCar)));e.attackTimer=e.interval;g.playSound('enemyShot');}}
 function ranged(e,dt,kind){if(e.windup){const w=e.windup;if(kind==='sniper'){const c=g.state.crew.find(c=>c.id===w.staff);if(!c||c.dead||c.hp<=0||c.moving||c.car!==w.car){e.windup=null;e.attackTimer=data(e).interval;return;}}w.left-=dt;if(w.left<=0){e.windup=null;shoot(e,w);}return;}e.attackTimer-=dt;if(e.x<=data(e).hold&&e.attackTimer<=0)begin(e,kind);}
 const special=g.updateSpecialEnemy?.bind(g);
 g.updateSpecialEnemy=function(e,dt){const d=data(e),handler=d?.elite&&this.eliteHandlers[d.specialBehavior];if(!handler)return special?.(e,dt)||false;if(d.specialBehavior!=='stealth')e.x=Math.max(d.hold??B.battle.boardDistance,e.x-B.battle.enemyApproachSpeed*e.speed*dt);handler(e,dt);return true;};
 const powerBase=old.effectiveCarPower;
 g.effectiveCarPower=function(ci){const p=powerBase(ci);if(!present())return p;const loss=living().filter(e=>data(e)?.specialBehavior==='parasite'&&e.linked&&e.targetCar===ci).reduce((n,e)=>n+(e.drained||0),0);return Math.max(Math.min(1,p),p-loss);};
 // Read allocation directly here: module generation is queried by effectiveCarPower.
 g.moduleData=function(eq){const m=old.moduleData(eq);if(!present())return m;const ci=this.state.cars.findIndex(c=>c.equipment.includes(eq));if(ci<0)return m;const loss=living().filter(e=>data(e)?.specialBehavior==='parasite'&&e.linked&&e.targetCar===ci).reduce((n,e)=>n+(e.drained||0),0),p=this.state.cars[ci].power,levels=REVISION_CONFIG.modulePower,f=levels[Math.max(Math.min(1,p),p-loss)]/(levels[p]||1);for(const key of ['heatMult','coolingMult','stageHealMult','repairMult','ammoDamageMult'])if(key in m)m[key]=1+(m[key]-1)*f;if('extraPower'in m)m.extraPower*=f;return m;};
 const carEffects=g.carEffectsHTML.bind(g);g.carEffectsHTML=function(ci){let html=carEffects(ci);if(!present())return html;for(const e of living().filter(e=>data(e)?.specialBehavior==='parasite'&&e.linked&&e.targetCar===ci))html+=`<p class="negative">전력 기생 · 추가 출력 −${e.drained||0} · 유효 출력 ${this.effectiveCarPower(ci)}</p>`;if((bstate().fires||[]).some(f=>f.car===ci))html+='<p class="negative">화재 · 직원 대피 / 비상 장갑으로 피해 방어</p>';return html;};
 g.updateEnemies=function(dt){const b=bstate();if(b.eliteNotice)b.eliteNotice.left-=dt;for(const c of this.state.crew){c.hammerVisual=Math.max(0,(c.hammerVisual||0)-dt);c.boardShot=Math.max(0,(c.boardShot||0)-dt);}for(const e of this.state.enemies)e.boardShot=Math.max(0,(e.boardShot||0)-dt);
   const restored=[];for(const e of living()){const leader=aura(e);if(!leader)continue;const d=data(leader);restored.push([e,e.speed,e.interval]);e.speed*=1+d.speedBonus+(leader.order==='charge'&&leader.orderLeft>0?d.chargeBonus:0);if(e.boarded)e.interval*=d.intervalMult;else e.attackTimer-=dt*(1/d.intervalMult-1);if(leader.orderLeft>0){if(leader.order==='focus'&&!e.boarded)e.targetCar=leader.orderCar;if(leader.order==='escort'&&!e.boarded)e.y+=(leader.y-e.y)*Math.min(1,dt*C.escortConvergence);}}
   for(const w of [...(this.state.attackWindups||[]),...(this.state.systemWindups||[])]){const leader=aura(w.owner);if(leader)w.left-=dt*(1/data(leader).windupMult-1);}
   try{old.updateEnemies(dt);}finally{for(const[e,speed,interval]of restored){e.speed=speed;e.interval=interval;}}
   for(const p of b.eliteShots||[]){p.left-=dt;if(p.left<=0&&p.kind==='fire'){const found=b.fires.find(f=>f.car===p.car);if(found)found.left=Math.max(found.left,p.data.fireSeconds);else b.fires.push({car:p.car,left:p.data.fireSeconds,tick:0,data:p.data});this.playSound('explosion');}}b.eliteShots=(b.eliteShots||[]).filter(p=>p.left>0);
   for(const f of b.fires||[]){const step=Math.min(dt,f.left/(this.fireLifetimeMultiplier?.(f.car)??1));f.left-=step*(this.fireLifetimeMultiplier?.(f.car)??1);f.tick+=step;while(f.tick+1e-9>=C.fireTick){f.tick-=C.fireTick;damageCar(f.car,this.state.cars[f.car].maxHp*f.data.hullRatio*C.fireTick,c=>c.maxHp*f.data.crewRatio*C.fireTick,null,'fire');}}b.fires=(b.fires||[]).filter(f=>f.left>0);
 };
 const inspect=old.inspectEnemy;g.inspectEnemy=function(e){if(!elite(e))return inspect(e);document.querySelector('#inspector').innerHTML=`<h3>${data(e).icon} ${e.name}</h3><p>HP ${Math.ceil(e.hp)} / ${Math.ceil(e.maxHp)} · 장갑 ${Math.round(e.armor*100)}%</p><p>${data(e).help}</p>`+this.eliteCodexHTML(e.type);};
 const check=g.checkBattleState.bind(g);g.checkBattleState=function(){const s=this.state,b=s.battle;if(!b.boss&&(b.eliteShots||[]).some(p=>p.kind==='fire'&&p.left>0)&&s.cars.some(c=>c.hp>0)&&s.titanDistance>B.titan.forcedBattleAt)return;return check();};
 g.eliteCodexHTML=function(id){const d=D.ENEMIES[id],keys={hold:'유지 거리',windup:'조준 시간 (초)',interval:'공격 간격 (초)',transfer:'대신 받는 피해 비율',radius:'효과 반경',crewRatio:'직원 최대 HP 피해 비율',drainAfter:'추가 흡수까지 (초)',drainMax:'최대 흡수 출력',armorPerPower:'흡수당 장갑 증가',speedBonus:'이동 보너스',intervalMult:'공격 간격 배율',windupMult:'특수 예고 시간 배율',orderInterval:'지휘 주기 (초)',orderSeconds:'지휘 지속 (초)',chargeBonus:'돌격 추가 이동 보너스',fireSeconds:'화재 지속 (초)',hullRatio:'초당 객차 최대 HP 피해 비율',travel:'충돌까지 (초)',currentHpRatio:'객차 현재 HP 피해 비율'};return '<p>'+d.help+'</p><table class="codex-table">'+Object.entries(keys).filter(([k])=>d[k]!==undefined).map(([k,n])=>`<tr><th>${n}</th><td>${d[k]}</td></tr>`).join('')+'</table>';};
})();
