/* The deck layer sits above train DOM, below damage numbers and modal controls. */
(() => {
 'use strict';
 const g=lastRail,D=GAME_DATA,C=ELITE_CONFIG,A=LAST_RAIL_SCENE,priorDraw=g.draw.bind(g),priorEnemies=g.drawEnemies.bind(g);
 const layer=document.createElement('canvas');layer.setAttribute('aria-hidden','true');layer.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:17';document.body.append(layer);
 const ctx=layer.getContext('2d'),alive=e=>!e.dead&&!e.destroyed;
 const colors={siege:'#e49c7f',bulwark:'#9dbfca',sniper:'#ff9696',parasite:'#bfa0ff',command:'#b4d49a',fire:'#ff9e61',stealth:'#a9dee5'};
 function line(c,a,b,color,width=2){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}
 function text(c,s,x,y,color='#f0e7d2',size=12){c.fillStyle=color;c.font=`600 ${size}px sans-serif`;c.textAlign='center';c.fillText(s,x,y);}
 function person(c,x,y,color,shot,t){c.save();c.translate(x,y);c.fillStyle=color;c.beginPath();c.arc(0,-15,5,0,Math.PI*2);c.fill();c.fillRect(-6,-9,12,14);line(c,{x:-3,y:4},{x:-8,y:13},'#263f44',4);line(c,{x:3,y:4},{x:8,y:13},'#263f44',4);line(c,{x:4,y:-4},{x:18,y:-8},'#e2d7bc',3);if(shot>0){c.fillStyle='#fff0a6';c.beginPath();c.arc(21,-9,5+Math.sin(t*55)*2,0,Math.PI*2);c.fill();}c.restore();}
 g.drawEnemies=function(c,w,h,t){priorEnemies(c,w,h,t);for(const e of this.state.enemies){const d=D.ENEMIES[e.type];if(!d.elite||!alive(e))continue;const p=A.project(e,w,h),kind=d.specialBehavior,color=colors[kind];c.save();c.translate(p.x,p.y);const scale=Math.max(.85,p.scale);c.scale(scale,scale);c.fillStyle=e.hitFlash>0?'#ffffff':'#405b5e';c.strokeStyle=color;c.lineWidth=2;
   if(kind==='stealth'){c.globalAlpha=.7;c.setLineDash([5,3]);c.beginPath();c.moveTo(-23,0);c.lineTo(0,-18);c.lineTo(23,0);c.lineTo(0,12);c.closePath();c.fill();c.stroke();c.setLineDash([]);c.fillStyle=color;c.fillRect(-5,-5,10,6);for(const x of [-26,26]){c.beginPath();c.ellipse(x,-3,12,3,Math.sin(t*12)*.2,0,Math.PI*2);c.stroke();}}
   else {c.beginPath();c.roundRect(-28,-13,56,27,4);c.fill();c.stroke();c.fillStyle='#20353b';for(const x of [-21,0,21]){c.beginPath();c.arc(x,15,7,0,Math.PI*2);c.fill();}c.fillStyle=color;
     if(kind==='siege'){c.fillRect(-16,-30,36,19);c.save();c.translate(9,-23);const to=A.getCarPosition(e.windup?.car??e.targetCar);c.rotate(to?Math.atan2(to.y-p.y,to.x-p.x)*.25:0);c.fillRect(0,-5,52,10);c.fillRect(46,-8,10,16);c.restore();}
     if(kind==='bulwark'){c.fillRect(-36,-23,14,44);c.strokeRect(-39,-27,20,51);for(let y=-17;y<17;y+=9)c.fillRect(-17,y,11,4);}
     if(kind==='sniper'){c.fillRect(-9,-25,17,12);line(c,{x:0,y:-20},{x:37,y:-20},color,4);c.strokeRect(4,-29,12,6);}
     if(kind==='parasite'){for(const x of [-18,18]){c.fillRect(x-5,-26,10,17);c.beginPath();c.arc(x,-30,5,0,Math.PI*2);c.stroke();}c.fillRect(-5,-23,10,11);}
     if(kind==='command'){line(c,{x:0,y:-12},{x:0,y:-48},color,3);for(let i=0;i<3;i++){c.beginPath();c.arc(0,-40,8+i*6,-Math.PI*.8,-Math.PI*.2);c.stroke();}c.fillRect(-19,-23,13,9);}
     if(kind==='fire'){for(const x of [-21,19]){c.fillRect(x-5,-22,10,20);}person(c,0,-17,'#dfa784',0,t);c.fillStyle='#ffc260';c.beginPath();c.moveTo(21,-29);c.lineTo(17,-43-Math.sin(t*9)*4);c.lineTo(27,-33);c.closePath();c.fill();}
   }
   c.globalAlpha=1;c.fillStyle='#13282e';c.fillRect(-33,-61,66,6);c.fillStyle=color;c.fillRect(-33,-61,66*Math.max(0,e.hp/e.maxHp),6);text(c,d.icon+' '+e.name,0,-68,color,12);if(e.muzzle>0){c.fillStyle='#fff0ae';c.beginPath();c.arc(29,-19,9,0,Math.PI*2);c.fill();}c.restore();}
 };
 g.draw=function(){priorDraw();const w=this.view.w,h=this.view.h,dpr=Math.min(devicePixelRatio||1,2);if(layer.width!==Math.round(w*dpr)||layer.height!==Math.round(h*dpr)){layer.width=Math.round(w*dpr);layer.height=Math.round(h*dpr);layer.style.width=w+'px';layer.style.height=h+'px';}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(this.mode!=='battle'||this.sceneTransition||!this.state)return;const b=this.state.battle,t=A.visualClock;ctx.save();
   for(const e of this.state.enemies.filter(e=>alive(e)&&e.boarded)){const p=A.project(e,w,h);person(ctx,p.x,p.y,e.hitFlash>0?'#fff':'#d8786b',e.boardShot,t);ctx.fillStyle='#203236';ctx.fillRect(p.x-13,p.y-29,26,4);ctx.fillStyle='#ff8982';ctx.fillRect(p.x-13,p.y-29,26*e.hp/e.maxHp,4);if(e.boardShot>0){const car=A.getCarPosition(e.targetCar);if(car)line(ctx,{x:p.x+18,y:p.y-8},{x:car.x,y:car.y+2},'#ffbf8f',2);}}
   for(const c of this.state.crew){const el=document.querySelector(`[data-crew="${c.id}"]`),r=el?worldRect(el):null;if(!r)continue;if(c.boardShot>0&&c.returnFireVisual){const from={x:r.left+r.width/2,y:r.top+14},to={x:c.returnFireVisual.x*w,y:c.returnFireVisual.y*h};line(ctx,from,to,'#ffefab',2);ctx.fillStyle='#fff3bd';ctx.beginPath();ctx.arc(from.x,from.y,6,0,Math.PI*2);ctx.fill();}if(c.hammerVisual>0){const x=r.right,y=r.top+15;line(ctx,{x:x-10,y:y+14},{x,y},'#d4c193',3);ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(t*22)*.5);ctx.fillStyle='#b9d0c0';ctx.fillRect(-7,-3,14,6);ctx.restore();for(let i=0;i<3;i++)line(ctx,{x:x+5,y:y+15},{x:x+11+i*4,y:y+12+i*5},'#ffe3a7');}}
   for(const e of this.state.enemies.filter(alive)){const d=D.ENEMIES[e.type],p=A.project(e,w,h);if(e.windup){const to=A.getCarPosition(e.windup.car);if(to){let dest={x:to.x,y:to.y-35};if(e.windup.staff){const el=document.querySelector(`[data-crew="${e.windup.staff}"]`),r=el?worldRect(el):null;if(r)dest={x:r.left+r.width/2,y:r.top+10};}ctx.setLineDash([7,6]);line(ctx,p,dest,'#ff7474');ctx.setLineDash([]);ctx.strokeStyle='#ff7474';ctx.lineWidth=2;ctx.beginPath();ctx.arc(dest.x,dest.y,22,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-e.windup.left/e.windup.total));ctx.stroke();text(ctx,'! '+Math.max(0,e.windup.left).toFixed(1),dest.x,dest.y-30,'#ff9a90');}}
     if(d.specialBehavior==='parasite'&&e.linked){const to=A.getCarPosition(e.targetCar);if(to){line(ctx,p,{x:to.x,y:to.y-40},'#bc9eff',3);text(ctx,'ϟ −'+(e.drained||0),to.x,to.y-55,'#bc9eff');}}
     if(['command','bulwark'].includes(d.specialBehavior)){const color=colors[d.specialBehavior];for(const ally of this.state.enemies.filter(x=>alive(x)&&x!==e)){const protectedAlly=d.specialBehavior==='command'?this.eliteAuraSource(ally)===e:!ally.boarded&&(D.ENEMIES[ally.type].boards||D.ENEMIES[ally.type].behavior==='infiltrator')&&Math.hypot(ally.x-e.x,(ally.y-e.y)/D.BALANCE.projectile.laneSpan)<=d.radius;if(protectedAlly){const q=A.project(ally,w,h);ctx.globalAlpha=.35;line(ctx,p,q,color);ctx.globalAlpha=1;ctx.strokeStyle=color;ctx.beginPath();ctx.arc(q.x,q.y,q.r+5,0,Math.PI*2);ctx.stroke();}}if(e.orderLeft>0)text(ctx,({charge:'돌격',focus:'집중 공격',escort:'호위'})[e.order],p.x,p.y+35,color);}
   }
   for(const f of b.fires||[]){const p=A.getCarPosition(f.car);if(!p)continue;ctx.globalAlpha=this.state.cars[f.car].armor>0?.35:.85;for(let i=0;i<6;i++){const x=p.x-42+i*16,y=p.y-30;ctx.fillStyle=i%2?'#ffbd63':'#f46d4c';ctx.beginPath();ctx.moveTo(x-7,y+20);ctx.quadraticCurveTo(x-10,y-8,x+Math.sin(t*6+i)*9,y-24-Math.sin(t*8+i)*12);ctx.quadraticCurveTo(x+14,y+7,x+7,y+20);ctx.fill();}ctx.globalAlpha=1;text(ctx,'화재 '+Math.ceil(f.left)+'초',p.x,p.y-76,'#ffb085');}
   for(const p of b.eliteShots||[]){const v=Math.max(0,Math.min(1,1-p.left/p.total)),start={x:p.start.x*w,y:p.start.y*h},end={x:p.end.x*w,y:p.end.y*h};if(p.kind==='fire'){const q={x:start.x+(end.x-start.x)*v,y:start.y+(end.y-start.y)*v-4*v*(1-v)*h*.18};ctx.fillStyle='#ffc17b';ctx.beginPath();ctx.arc(q.x,q.y,6,0,Math.PI*2);ctx.fill();line(ctx,{x:q.x-8,y:q.y+5},q,'#ff754d',3);}else{ctx.globalAlpha=1-v;line(ctx,start,end,p.kind==='sniper'?'#ffae91':'#fff1b9',p.kind==='sniper'?2:5);ctx.globalAlpha=1;}}
   if(b.eliteNotice?.left>0){ctx.fillStyle='#172c30ee';const y=h*.19;ctx.fillRect(w*.06,y,w*.88,57);text(ctx,b.eliteNotice.text,w/2,y+20,'#f1cb8b',14);if(b.eliteNotice.help)text(ctx,b.eliteNotice.help,w/2,y+42,'#e4e2d3',Math.max(10,Math.min(13,w/65)));}
   ctx.restore();
 };
 // Deck sprites remain targetable even when their pixels overlap train DOM.
 document.addEventListener('click',event=>{if(g.mode!=='battle'||document.querySelector('#overlay').classList.contains('show')||g.state.targetMode!=='focus')return;const {x,y}=worldPointer(event),e=g.state.enemies.filter(e=>alive(e)&&e.boarded).find(e=>{const p=A.project(e,g.view.w,g.view.h);return Math.hypot(p.x-x,p.y-y)<p.r+5;});if(e){event.preventDefault();event.stopImmediatePropagation();g.executeFocus(e);}},true);
})();
