(()=>{
 const g=lastRail,D=GAME_DATA,B=D.BALANCE,C=EQUIPMENT_REFORM,W=WEAPON_UPGRADES,A=LAST_RAIL_SCENE,$=s=>document.querySelector(s);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Number((Number(n)||0).toFixed(2));
 const table=rows=>'<table class="comparison"><thead><tr><th>항목</th><th>기본</th><th>현재</th></tr></thead><tbody>'+rows.map(([name,base,current,lower=false])=>`<tr><td>${esc(name)}</td><td>${num(base)}</td><td class="${Math.abs(current-base)<.00001?'neutral':(lower?current<base:current>base)?'positive':'negative'}">${num(current)}</td></tr>`).join('')+'</tbody></table>';
 const descriptions={overdrive:'열 60 / 80 / 95에서 단계별 피해·연사 강화',crewArms:'개인화기 피해·대응 사거리·Grip 대응 강화',shield:'독립 실드가 피해를 흡수하고 소진되면 재충전',autoRepair:'전투 중 천천히 자동 수리 · 파괴된 객차 제외',grinder:'전투 시작 시 장착하고 끝까지 유지한 장비만 돈·고철 지급',targeting:'일반 사격과 집중 사격 사거리 증가'};
 const description=g.moduleDescription.bind(g);g.moduleDescription=m=>descriptions[m.effect]||description(m);
 function effects(p){const names={damage:'피해 배율',rate:'연사 배율',pierce:'추가 관통',splashMult:'폭발 반경 배율',pellets:'추가 펠릿',projectileSpeed:'탄속 배율',chains:'추가 연쇄',chainRange:'연쇄 거리 배율',slowStacks:'명중당 감속 중첩',knockback:'후퇴 거리',zoneDamage:'화염 피해 배율'};return Object.entries(p||{}).map(([k,v])=>`${names[k]||k} ${v}`).join(' · ');}
 const html=g.equipmentHTML.bind(g);g.equipmentHTML=function(eq,ci=null){let out=html(eq,ci);const d=(eq.kind==='turret'?D.TURRETS:D.MODULES)[eq.type];
  if(eq.kind==='turret'){
   const spec=C.turret[eq.type]||C.turret.cannon;
   if(ci===null){const p=this.weaponProfile(eq),level=eq.level||1,base={damage:d.damage*(d.pellets||1),interval:d.interval,heat:d.heat,splash:d.splash||0,armorPierce:d.armorPierce||0,chains:d.chains||1,chainRatio:d.chainRatio||1};const current=this.applyHeatProfile({...base,damage:base.damage*(1+(level-1)*B.upgrade.damagePerLevel)*p.damage,interval:base.interval/p.rate,heat:base.heat*(1+(level-1)*B.upgrade.heatPerLevel)*p.heat,armorPierce:Math.min(1,base.armorPierce+p.pierce)},eq);
    out=`<h3>${esc(d.name)} · Lv.${level}</h3><div class="detail-art">${A.equipmentArt(eq)}</div><p>${esc(d.role)}</p>${table([['1회 피해',base.damage,current.damage],['발사 간격 (초)',base.interval,current.interval,true],['발사당 기본 열',base.heat,current.heat,true],['초당 기초 냉각',d.cool,d.cool*p.cooling],['최대 사거리',B.targeting[d.range],B.targeting[d.range]*p.range],['관통 (%)',base.armorPierce*100,current.armorPierce*100]])}<p>강화·분기 반영, 직원·전력·모듈 보정 전입니다.</p>`;
    out+=Object.entries(eq.weaponBranches||{}).map(([tier,id])=>`<p>Lv.${tier} ${esc(W.tiers[tier]?.[id]?.name)} · ${esc(W.tiers[tier]?.[id]?.text)}</p>`).join('');
   }
   out+=`<section class="heat-guide"><h4>고열 운용 · 최대 Lv.8</h4><p>열 ${spec.high} 이상: ${esc(effects(spec.highEffect))}</p><p>열 ${spec.critical} 이상: ${esc(effects(spec.criticalEffect))}</p><p class="negative">과열: 열 ${B.heat.max} 도달로 정지한 뒤 열 ${B.heat.resumeAt} 이하가 될 때까지. 과열 중 냉각 ×${C.overheatCoolingMultiplier}. 과열 폭주 개조는 기존 폭주 후 열 0까지 강제 냉각하며 같은 냉각 배율을 적용합니다.</p><p>발열 방식: ${esc(({continuous:'현재 열과 무관한 고정 기본 발열',shell:'느린 단발 · 높은 발열',pellets:`초근거리 적중 펠릿당 열 +${spec.heatPerHit}`,chains:`추가 연쇄 적중당 열 +${spec.heatPerHit}`,zones:`유지 화염지대마다 발열 +${spec.heatPerZone}`,pulse:'충격파 단발 발열'})[spec.heatRule])}</p><b class="${eq.level>=8?'positive':''}">Lv.8 · ${esc(spec.cap.name)}</b><p>${esc(spec.cap.text)}</p></section>`;
   if(eq.type==='breaker')out+=`<p>적중당 장갑 ${C.armor.perHit*100}%p 감소 · 최대 ${C.armor.maxStacks}중첩 · ${C.armor.duration}초 유지</p>`;
   if(eq.type==='phosphorus')out+=`<p>화염 ${C.turret.phosphorus.zone.seconds}초 · 반경 ${C.turret.phosphorus.zone.radius} · 초당 포탄 피해의 ${C.turret.phosphorus.zone.damageRatio*100}%</p>`;
   if(eq.type==='frost')out+=`<p>감속 중첩당 ${C.slow.perHit*100}% · 최대 ${C.slow.maxStacks}중첩 · ${C.slow.duration}초</p>`;
  }else{
   out=out.replace('직원 능력·출력 2 이상은 모듈을 추가 증폭하지 않습니다.','현재 출력과 모듈 강화에 따라 효과가 증폭됩니다.');
   const config=C.modules[eq.type],source=ci===null?null:this.moduleSources(ci).find(s=>s.eq.id===eq.id),strength=ci===null?(1+((eq.level||1)-1)*C.moduleGrowth)*(B.moduleUpgrade.branches[eq.model]?.factor||1)*((eq.level||1)>=C.moduleCapLevel?(config?.capFactor||1):1):source?.strength||0;
   if(config){const names={damage:'추가 피해',rate:'추가 연사',range:'추가 사거리',grip:'추가 Grip 피해',capacity:'실드 HP',repair:'초당 수리',money:'완료 시 돈',scrap:'완료 시 고철'};out+=table(Object.entries(names).filter(([k])=>config[k]!==undefined).map(([k,n])=>[n,config[k],config[k]*strength]));if(config.recharge)out+=`<p>실드 소진 후 ${num(config.recharge*(eq.level>=5?config.capRecharge:1))}초 재충전</p>`;}
   if(d.upgradeable!==false)out+=`<p>최대 Lv.5 · Lv.3 분기 선택 + 보조 슬롯 1개 해금</p><p class="positive">${esc(d.level5Capstone)}</p><p>보조 장비는 레벨·분기·최종 특수효과를 제외한 기본 효과의 ${C.auxEfficiency*100}%만 적용합니다. 추가 중첩 슬롯은 생성하지 않습니다.</p><p>${eq.aux?`보조 장착: ${esc(D.MODULES[eq.aux.type].name)} (보관 레벨 ${eq.aux.level||1})`:(eq.level||1)>=3?'보조 슬롯 비어 있음 · 정비 스테이션 재정비에서 다른 모듈을 선택한 뒤 위쪽 보조 슬롯을 누르세요.':'Lv.3에 보조 슬롯 해금'}</p>`;
   if(this.auxHostFor?.(eq))out+=`<p class="aux-effect-note">보조 모듈은 ${C.auxEfficiency*100}%의 효과가 적용됩니다.</p>`;
  }return out;
 };
 g.upgradeHTML=function(){return this.state.cars.flatMap(c=>c.equipment.map(eq=>{const d=(eq.kind==='turret'?D.TURRETS:D.MODULES)[eq.type],cost=this.upgradeCost(eq),plan=eq.kind==='turret'?this.weaponUpgradePlan(eq):null,branches=eq.kind==='module'&&this.moduleUpgradePlan(eq)?.branch?B.moduleUpgrade.branches:plan?.tier?W.tiers[plan.tier]:null;let buttons=cost===null?'<button disabled>최대 강화 / 강화 불가</button>':branches&&(this.mode==='station'||eq.kind==='turret'&&this.canFieldBranch(eq))?Object.entries(branches).map(([id,b])=>`<button data-upgrade-id="${eq.id}" data-module-model="${id}" title="${esc(b.text)}">${esc(b.name)} · ▰ ${cost}</button>`).join(''):`<button data-upgrade-id="${eq.id}">${branches?'분기 · 정비소 전용':`Lv.${(eq.level||1)+1} 강화`} · ▰ ${cost}</button>`;return `<article class="upgrade-entry"><b>${esc(d.name)} Lv.${eq.level||1} · ${esc(c.name)}</b>${buttons}${this.mode==='station'&&cost!==null?this.timeHTML(this.equipmentUpgradeSeconds(eq)):''}</article>`;})).join('');};
 const station=g.renderStation.bind(g);g.renderStation=function(){if(this.stationTab==='auxiliary')this.stationTab='gear';station();if(this.mode!=='station'||this.stationTab!=='gear')return;for(const [i,offer]of this.stationOffers.gear.entries()){const button=$(`[data-station-action="buy"][data-index="${i}"]`),card=button?.closest('.shop-item');if(!card||!offer.equipment)continue;card.querySelector('h3').textContent=`${offer.d.name} · Lv.${offer.equipment.level} · ¤ ${offer.d.price}`;card.querySelector('.shop-detail').innerHTML='<summary>세부 스탯 보기</summary>'+this.equipmentHTML(offer.equipment);if(this.state.money<offer.d.price)button.classList.add('unaffordable');}};
 const render=g.renderCars.bind(g);g.renderCars=function(){render();if(!this.state)return;for(const car of this.state.cars)for(const eq of car.equipment){const el=$(`[data-equipment="${eq.id}"]`);if(!el)continue;const d=C.turret[eq.type];const overheated=this.isTurretOverheated(eq);el.classList.toggle('overheated',overheated);el.classList.toggle('high-heat',!overheated&&!!d&&eq.heat>=d.high);el.classList.toggle('critical-heat',overheated);el.querySelector('.aux-module-slot')?.remove();if(eq.kind==='module'&&(eq.level||1)>=C.auxUnlock&&D.MODULES[eq.type].upgradeable!==false&&(eq.aux||document.body.classList.contains('is-formation'))){const slot=document.createElement('span');slot.className=`aux-module-slot ${eq.aux?'occupied':'empty'}`;slot.dataset.auxHost=eq.id;slot.setAttribute('role','button');slot.tabIndex=0;if(eq.aux){slot.dataset.equipment=eq.aux.id;slot.dataset.auxEquipment=eq.aux.id;slot.setAttribute('aria-label',`${D.MODULES[eq.aux.type].name} 보조 모듈 정보`);slot.title=`보조 · ${D.MODULES[eq.aux.type].name}`;slot.innerHTML=`<span class="aux-mini-art">${A.equipmentArt(eq.aux)}</span>`;slot.classList.toggle('formation-selected',this.formationSelectedId===eq.aux.id);slot.classList.toggle('targeted',this.inspectedEquipment===eq.aux.id);}else{slot.textContent='+';slot.setAttribute('aria-label',`${D.MODULES[eq.type].name} 빈 보조 모듈 슬롯`);slot.title='선택한 모듈을 보조 모듈로 장착';const selected=this.formationSelectedId&&this.findEquipment(this.formationSelectedId);slot.classList.toggle('formation-destination',selected?.kind==='module'&&!this.auxHostFor?.(selected));}el.append(slot);}}
  this.state.cars.forEach((car,i)=>{const el=$(`[data-car-index="${i}"]`);if(!el)return;el.querySelector('.module-shield')?.remove();if(car.shieldHp>0){const b=document.createElement('span');b.className='module-shield';b.textContent=`실드 ${Math.ceil(car.shieldHp)}`;el.append(b);}});
 };
 $('#train-cars').addEventListener('keydown',e=>{const slot=e.target.closest('.aux-module-slot.occupied');if(slot&&(e.key==='Enter'||e.key===' ')){e.preventDefault();slot.click();}});
 const crew=g.crewHTML.bind(g);g.crewHTML=function(c,live=true){return crew(c,live)+(live?`<p>모듈 반영 개인화기 피해 ×${num(this.crewWeaponMultiplier(c))} · 추가 관통 ${num(this.crewWeaponPierce(c)*100)}%p · 대응 사거리 +${num(this.moduleBonus(c.car,'crewArms','range')*100)}%</p>`:'');};
 g.reformEquipmentArt=function(eq){const shapes={breaker:'<path d="M8 8L20 3 56 34 44 45Z"/><path d="M38 25H62V48H26Z"/>',phosphorus:'<path d="M19 7L31 3 54 40 40 48Z"/><circle cx="52" cy="28" r="9" fill="#e3ba79"/>',repulsor:'<path d="M24 44V14L59 10 66 23 60 42Z"/><path d="M8 7Q-3 28 8 49M18 13Q7 28 18 43" fill="none" stroke="#98e4db"/>',frost:'<path d="M13 15H57L64 39H17Z"/><path d="M7 25H45M25 8V42M12 12L38 38M12 38L38 12" fill="none" stroke="#b1e5f6"/>'};if(!shapes[eq.type]||eq.kind!=='turret')return null;return `<svg viewBox="0 0 80 60" aria-hidden="true"><g fill="#637e78" stroke="#192c32" stroke-width="3" stroke-linejoin="round"><path d="M20 48H63L68 58H13Z"/>${shapes[eq.type]}</g></svg>`;};
 const draw=g.draw.bind(g);g.draw=function(){draw();if(!this.state)return;const ctx=this.ctx,w=this.view.w,h=this.view.h;ctx.save();for(const z of this.state.weaponZones||[]){const p=A.project(z,w,h),edge=A.project({x:Math.min(1,z.x+z.radius),y:z.y},w,h);ctx.fillStyle='#efb96035';ctx.strokeStyle='#ffd3a0';ctx.beginPath();for(let n=0;n<=48;n++){const angle=n*Math.PI*2/48,q=A.project({x:z.x+Math.cos(angle)*z.radius,y:z.y+Math.sin(angle)*z.radius*B.projectile.laneSpan},w,h);if(n===0)ctx.moveTo(q.x,q.y);else ctx.lineTo(q.x,q.y);}ctx.closePath();ctx.fill();ctx.stroke();for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#ffecc2':'#e8a76b';ctx.fillRect(p.x+(i-2)*12,p.y-12-Math.sin(A.visualClock*6+i)*8,5,14);}}for(const e of this.state.enemies){if(!e.slowLeft&&!e.breakLeft)continue;const p=A.project(e,w,h);ctx.strokeStyle=e.frozen>0?'#e1fbff':e.slowLeft>0?'#8dcae7':'#e6b871';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,p.r+4,0,Math.PI*2);ctx.stroke();}ctx.restore();};
 const style=document.createElement('style');style.textContent='.equipment-button.heat-warning:not(.overheated) .equipment-heat i{background:#d1a56d!important}.equipment-button.overheated .equipment-heat i{background:#ff6262!important}.high-heat{filter:drop-shadow(0 0 6px #eec174)}.critical-heat{filter:drop-shadow(0 0 8px #ff7060)}.aux-module-slot{position:absolute;left:50%;top:-35px;transform:translateX(-50%);width:34px;height:29px;display:flex;align-items:center;justify-content:center;border:1px solid #93d0bd;border-radius:5px;background:#173c37;color:#c2e8d8;z-index:7;box-sizing:border-box;font:18px sans-serif;filter:drop-shadow(0 2px 3px #0008);pointer-events:auto}.aux-module-slot.empty{border-style:dashed;background:#173c3766;color:#b9d9ce}.aux-module-slot.occupied{cursor:pointer}.aux-module-slot .aux-mini-art{display:block;width:30px;height:25px;overflow:hidden;pointer-events:none}.aux-module-slot .aux-mini-art svg{width:100%!important;height:100%!important;transform:scale(.72);transform-origin:center}.aux-module-slot.formation-destination{outline:2px dashed #8be0a1!important;outline-offset:2px;background:#8be0a125!important}.aux-module-slot.formation-selected,.aux-module-slot.targeted{outline:2px solid #f1d266;outline-offset:2px}.aux-effect-note{margin-top:12px;padding:9px 11px;border:1px solid #93d0bd66;border-radius:5px;background:#173c374d;color:#c2e8d8;font-weight:700}.module-shield{position:absolute;right:8px;top:22px;padding:2px 5px;background:#223a58;color:#b3d8ff;font-size:11px;pointer-events:none}.heat-guide{margin-top:12px;padding:12px;border:1px solid #8d826245;border-radius:7px}.heat-guide p{line-height:1.6}.upgrade-entry select{max-width:100%;padding:9px;background:#243c40;color:#e5efdf}@media(max-width:700px){.aux-module-slot{top:-28px;width:28px;height:24px}.aux-module-slot .aux-mini-art{width:24px;height:21px}}';document.head.append(style);
})();
