/* Meta saves are distinct from a frozen per-run loadout. No mid-run meta purchases. */
(() => {
 'use strict';const g=lastRail,D=GAME_DATA,B=D.BALANCE,C=META_CONFIG,clone=x=>JSON.parse(JSON.stringify(x)),pick=a=>a[Math.floor(Math.random()*a.length)];
 const m=g.meta;try{if(m.schema!==C.version&&!localStorage.getItem('lastRailMetaBeforeV2'))localStorage.setItem('lastRailMetaBeforeV2',JSON.stringify(m));}catch{}
 m.upgrades??={};m.modifications??={};m.enabledMods??=[];m.spent??=0;m.clears??=0;m.apocalypseUnlocked??=0;m.apocalypseCleared??=-1;m.apocalypseSelected??=0;m.totalEarned??=Math.max(0,(m.relics||0)+(m.spent||0));m.act2Clears??=0;m.maxPoints??=0;m.schema=C.version;
 m.apocalypseUnlocked=Math.max(0,Math.min(C.apocalypse.length-1,Number(m.apocalypseUnlocked)||0));m.apocalypseSelected=Math.max(0,Math.min(m.apocalypseUnlocked,Number(m.apocalypseSelected)||0));
 for(const[id,d]of Object.entries(C.upgrades))m.upgrades[id]=Math.max(0,Math.min(d.max,Number(m.upgrades[id])||0));
 g.saveMeta=function(){try{localStorage.setItem('lastRailMeta',JSON.stringify(this.meta));return true;}catch{this.toast('영구 기록을 저장하지 못했습니다. 저장 공간을 확인하세요.');return false;}};
 g.modPoints=function(){return this.meta.act2Clears>0?C.points.filter(([spent])=>this.meta.spent>=spent).at(-1)?.[1]||0:0;};
 g.modMenuUnlocked=()=>m.act2Clears>0&&m.spent>=C.modSpent;
 g.metaUnlocked=function(id){const d=C.upgrades[id];return !!d&&(d.group!=='advanced'||m.spent>C.advancedSpent)&&(!d.requires||m.upgrades[d.requires.id]>=d.requires.level);};
 g.buyPermanent=function(id){if(this.mode!=='menu')return false;const d=C.upgrades[id],n=m.upgrades[id]||0;if(!d||!this.metaUnlocked(id)||n>=d.max)return false;const cost=d.costs[n];if(m.relics<cost){this.toast('고대 잔해가 부족합니다.');return false;}const before=clone(m);m.relics-=cost;m.spent+=cost;m.upgrades[id]=n+1;m.maxPoints=Math.max(m.maxPoints,this.modPoints());if(!this.saveMeta()){Object.assign(m,before);return false;}this.playSound('upgrade');this.drawMenuState();return true;};
 g.buyModification=function(id){if(this.mode!=='menu'||!this.modMenuUnlocked()||m.modifications[id])return false;const d=C.modifications[id];if(!d||m.relics<d.cost){this.toast('고대 잔해가 부족합니다.');return false;}const before=clone(m);m.relics-=d.cost;m.spent+=d.cost;m.modifications[id]=true;m.maxPoints=Math.max(m.maxPoints,this.modPoints());if(!this.saveMeta()){Object.assign(m,before);return false;}this.drawMenuState();return true;};
 g.toggleModification=function(id){if(this.mode!=='menu'||!this.modMenuUnlocked()||!m.modifications[id])return false;const next=m.enabledMods.includes(id)?m.enabledMods.filter(x=>x!==id):[...m.enabledMods,id];if(next.reduce((n,k)=>n+C.modifications[k].points,0)>this.modPoints()){this.toast('개조 포인트가 부족합니다. 다른 개조를 끄세요.');return false;}const previous=m.enabledMods;m.enabledMods=next;if(!this.saveMeta()){m.enabledMods=previous;return false;}return true;};
 m.enabledMods=m.enabledMods.filter(id=>m.modifications[id]&&C.modifications[id]);while(m.enabledMods.reduce((n,id)=>n+C.modifications[id].points,0)>g.modPoints())m.enabledMods.pop();g.saveMeta();
 let building=null;
 const context=()=>building||g.state?.metaRun;
 // Content eligibility is frozen together with the rest of the run loadout. Keep
 // immutable numeric thresholds here because save-format may later expose
 // account-retained unlocks through dynamic unlockSpent getters.
 const unlockRegistries={turrets:D.TURRETS,modules:D.MODULES,skills:D.TRAITS,events:Object.fromEntries(EVENT_CONFIG.events.map(e=>[e.id,e]))};
 const unlockThresholds=Object.fromEntries(Object.entries(unlockRegistries).map(([kind,reg])=>[kind,Object.fromEntries(Object.entries(reg).map(([id,d])=>[id,Number.isFinite(d.unlockSpent)?d.unlockSpent:0]))]));
 function snapshotUnlocks(spent=m.spent,retained=m.contentUnlocks||{}){const out={};for(const[kind,reg]of Object.entries(unlockRegistries)){const keep=new Set(Array.isArray(retained?.[kind])?retained[kind]:[]);out[kind]=Object.keys(reg).filter(id=>{const at=unlockThresholds[kind][id]||0;return !at||spent>=at||keep.has(id);});}return out;}
 g.runUnlockSpent=function(){const run=context();return Number.isFinite(run?.unlockSpent)?run.unlockSpent:m.spent;};
 g.captureCurrentRunUnlocks=()=>clone(snapshotUnlocks(m.spent));
 g.runContentUnlocked=function(kind,id){if(unlockRegistries[kind]?.[id]?.eventOnly)return false;const run=context();const list=run?.unlocks?.[kind];if(Array.isArray(list))return list.includes(id);const at=unlockThresholds[kind]?.[id]||0;return !at||this.runUnlockSpent()>=at;};
 const level=id=>context()?.upgrades?.[id]||0;
 g.runMetaLevel=level;
 const value=id=>C.upgrades[id]?.values[level(id)-1]||0;
 const mod=id=>!!context()?.mods?.includes(id);
 g.hasTrainMod=mod;
 g.apocalypseModifiers=function(n){const out={};for(const row of C.apocalypse.slice(0,n+1))for(const[k,v]of Object.entries(row))out[k]=typeof v==='number'?(out[k]||0)+v:v;return out;};
 const base={balance:clone(B),turretPower:Object.fromEntries(Object.entries(D.TURRETS).map(([id,t])=>[id,clone(t.power)])),stages:clone(D.ACTS),combat:clone(COMBAT_CONFIG.stageOverrides),boss:clone(D.BOSSES),bossTuning:clone(BOSS_REWORK),elite:clone(D.ENEMIES),caps:clone(ELITE_CONFIG.caps),returnFire:clone(PROGRESSION_CONFIG.returnFire),modulePower:clone(REVISION_CONFIG.modulePower)};
 function configure(run){const a=g.apocalypseModifiers(run.apocalypse);Object.assign(B,clone(base.balance));B.meta.hullHpBonus=C.upgrades.hull.values[0];B.meta.engineSpeedBonus=C.upgrades.engine.values[0];B.meta.focusRangeBonus=C.upgrades.focus.values[0];B.train.carHp*=run.mods.includes('armor')?C.tuning.armorHp:1;B.train.startingCrew=run.upgrades.extraCrew?3:base.balance.train.startingCrew;B.train.enginePower.start=run.upgrades.power?3:base.balance.train.enginePower.start;B.train.enginePower.max=run.mods.some(id=>['grid','pressure'].includes(id))?4:base.balance.train.enginePower.max;B.train.speedByPower[4]=base.balance.train.speedByPower[3]*1.2;B.run.startingMoney=Math.max(0,base.balance.run.startingMoney+(C.upgrades.startMoney.values[run.upgrades.startMoney-1]||0)+(a.money||0));B.run.startingScrap+=(C.upgrades.startScrap.values[run.upgrades.startScrap-1]||0);B.run.startingTitanDistance=Math.max(B.titan.forcedBattleAt+.1,base.balance.run.startingTitanDistance+(a.distance||0));B.titan.speedBase*=1+(a.titan||0);B.station.repairMoneyPerHp*=1+(a.shop||0);
   for(const[id,t]of Object.entries(D.TURRETS)){t.power=clone(base.turretPower[id]);if(run.mods.includes('grid'))t.power.push(clone(t.power.at(-1)));}REVISION_CONFIG.modulePower=[...base.modulePower,base.modulePower.at(-1)];Object.assign(PROGRESSION_CONFIG.returnFire,base.returnFire);if(run.mods.includes('rifle'))PROGRESSION_CONFIG.returnFire.range=C.tuning.rifleRange;
   for(const[id,act]of Object.entries(D.ACTS))act.stages=clone(base.stages[id].stages);configureStationSchedule(run.apocalypse);
   COMBAT_CONFIG.stageOverrides=clone(base.combat);for(const stages of Object.values(COMBAT_CONFIG.stageOverrides))for(const row of Object.values(stages))row.budget*=1+(a.budget||0);
   Object.assign(ELITE_CONFIG.caps,Object.fromEntries(Object.entries(base.caps).map(([k,n])=>[k,n+(a.eliteCap||0)])));
   for(const[id,b]of Object.entries(D.BOSSES)){Object.assign(b,clone(base.boss[id]));b.sharedHp*=1+(a.enemyHp||0);b.parts.forEach(p=>p.hp*=1+(a.enemyHp||0));}Object.assign(BOSS_REWORK,clone(base.bossTuning));BOSS_REWORK.behemoth.cannon.damage*=1+(a.enemyDamage||0);BOSS_REWORK.grips.crush.damagePerSecond*=1+(a.enemyDamage||0);for(const k of ['carDamage','crewDamage'])BOSS_REWORK.truck[k]*=1+(a.enemyDamage||0);for(const k of ['hp','boarderHp'])BOSS_REWORK.truck[k]*=1+(a.enemyHp||0);
   for(const[id,e]of Object.entries(D.ENEMIES))if(e.elite)for(const k of ['crewRatio','hullRatio','currentHpRatio'])if(base.elite[id][k]!==undefined)e[k]=base.elite[id][k]*(1+(a.enemyDamage||0));
 }
 const initial=g.makeInitialState.bind(g);
 g.makeInitialState=function(){const run={upgrades:clone(m.upgrades),mods:this.modMenuUnlocked()?[...m.enabledMods]:[],apocalypse:Math.min(m.apocalypseUnlocked,m.apocalypseSelected||0),unlockSpent:m.spent,unlocks:snapshotUnlocks(m.spent)};building=run;configure(run);try{const s=initial();s.metaRun=run;s.revivesUsed=0;s.metaTick=0;const stats=['combat','operate','repair','recovery'];for(const c of s.crew.slice(0,value('fortune'))){c.stars=c.birthStars=2;for(let i=0;i<PROGRESSION_CONFIG.stars.statBonus[2];i++)c.stats[pick(stats)]++;const talent=pick(Object.keys(D.TRAITS).filter(id=>D.TRAITS[id].canBeNormalSkill!==false&&!D.TRAITS[id].captainOnly&&this.runContentUnlocked('skills',id)));if(talent){c.traits.push(talent);c.starTraits.push(talent);}}
   if(mod('captain')){const car=s.cars.findIndex((_,i)=>s.crew.filter(c=>c.car===i).length<this.crewCapacity(i)),c={id:crypto.randomUUID(),name:'현장 열차장',background:'열차를 끝까지 지킨다',captain:true,car,stats:{combat:1,operate:1,repair:1,recovery:1},hp:B.crew.maxHp,maxHp:B.crew.maxHp,level:1,stars:3,xp:0,pendingStats:0,traits:['fieldCaptain'],starTraits:[],eventTraits:[],training:{},dead:false,moving:null};for(let i=stats.length;i<C.tuning.captainStats;i++)c.stats[pick(stats)]++;s.crew.push(c);}
   for(const[kind,flag]of [['module','startModule'],['turret','startTurret']])if(value(flag)){const car=s.cars.find((c,i)=>c.equipment.length<this.equipmentCapacity(i)),type=this.randomMetaGear(kind);if(car&&type)this.addEquipment(car,kind,type);}return s;}finally{building=null;}};
 D.TRAITS.fieldCaptain={name:'현장 지휘관',text:`같은 객차 직원 전투 +${C.tuning.captainCombatBonus} · 열차장 사망 시 런 종료`,captainOnly:true,unlockSpent:Infinity};
 g.randomMetaGear=function(kind,random=Math.random,unlocked=false){const registry=kind==='turret'?D.TURRETS:D.MODULES,key=kind==='turret'?'turrets':'modules';const pool=Object.keys(registry).filter(id=>{const d=registry[id],at=unlockThresholds[key]?.[id]||0;return !d.eventOnly&&!d.rare&&(!at||(unlocked&&this.runContentUnlocked(key,id)));});return pool[Math.floor(random()*pool.length)];};
 const equipment=g.addEquipment.bind(g);g.addEquipment=function(car,kind,type){if(kind==='turret'&&mod('random'))type=this.randomMetaGear('turret',Math.random,true)||type;return equipment(car,kind,type);};
 g.randomizeMetaEquipment=function(eq,random=Math.random){if(eq.kind==='turret'&&mod('random')&&!eq.metaRandomized){eq.type=this.randomMetaGear('turret',random,true)||eq.type;eq.metaRandomized=true;}return eq;};
 g.metaGain=(key,n)=>n>0&&['money','scrap'].includes(key)?Math.round(n*(1+value(key))):n;
 g.metaRelicReward=n=>Math.floor(n*(C.reward.filter(([n])=>n<=(context()?.apocalypse||0)).at(-1)?.[1]||1));
 const curve=g.stageCurve.bind(g);g.stageCurve=function(){const r={...curve()},a=this.apocalypseModifiers(context()?.apocalypse||0);r.hp*=1+(a.enemyHp||0);r.damage*=1+(a.enemyDamage||0);return r;};
 const battle=g.startBattle.bind(g);g.startBattle=function(...args){battle(...args);const b=this.state.battle,a=this.apocalypseModifiers(context()?.apocalypse||0),f=1+(a[b.elite?'eliteDistance':'normalDistance']||0);if(f===1)return;b.duration*=f;const r=b.rhythm;if(r){for(const p of r.phases){p.duration*=f;if(p.start!==undefined)p.start*=f;if(p.end!==undefined)p.end*=f;}r.queue.forEach(e=>e.at*=f);r.nextGroupAt*=f;}};
 const shop=g.prepareActShop.bind(g);g.prepareActShop=function(){shop();const o=this.stationOffers;if(!o||o.metaPriced)return;o.metaPriced=true;const a=this.apocalypseModifiers(context()?.apocalypse||0);for(const e of o.gear)e.d={...e.d,price:Math.ceil(e.d.price*(1-value('gearPrice'))*(1+(a.shop||0)))};};
 const crewPrice=g.stationCrewPrice.bind(g);g.stationCrewPrice=i=>Math.ceil(crewPrice(i)*(1-value('crewPrice'))*(1+(g.apocalypseModifiers(context()?.apocalypse||0).shop||0)));
 const plan=g.weaponUpgradePlan.bind(g);g.weaponUpgradePlan=function(eq){const p=plan(eq);return p?{...p,cost:Math.ceil(p.cost*(1-value('upgradePrice')))}:p;};
 g.canFieldBranch=eq=>eq.kind==='turret'&&value('tools')>0&&g.weaponUpgradePlan(eq)?.tier===3;
 const seconds=g.equipmentUpgradeSeconds.bind(g);g.equipmentUpgradeSeconds=eq=>g.canFieldBranch(eq)?0:seconds(eq);
 const command=g.commandStatBonus.bind(g);g.commandStatBonus=()=>command()+value('commandBook');const armor=g.armorDuration.bind(g);g.armorDuration=()=>armor()*(1+value('armorTime'));
 const focus=g.executeFocus.bind(g);g.executeFocus=function(e){const before=this.state.orders.focus.cooldown;focus(e);if(this.state.orders.focus.cooldown>before)for(const c of this.state.cars)for(const eq of c.equipment)if(eq.kind==='turret')eq.heat=Math.max(0,eq.heat-value('focusCool'));};
 const stat=g.effectiveStat.bind(g);g.effectiveStat=function(c,k){let v=stat(c,k);if(mod('military'))v=Math.max(1,v+(C.tuning.military[k]||0));if(mod('rifle')&&k==='combat')v=Math.max(1,v+C.tuning.rifleCombat);if(k==='combat'&&this.state?.crew.some(x=>x.captain&&!x.dead&&x.hp>0&&!x.moving&&x.car===c.car))v+=C.tuning.captainCombatBonus;return v;};
 const effect=g.moduleEffect.bind(g);g.moduleEffect=(ci,id,k)=>effect(ci,id,k)*(mod('repair')&&k==='repairMult'?C.tuning.repairFactor:1);
 const xp=g.grantCrewXp.bind(g);g.grantCrewXp=(c,...a)=>c.captain?0:xp(c,...a);
 const growth=g.crewGrowthText.bind(g);g.crewGrowthText=c=>c.captain?'현장 열차장 · 성장 불가':growth(c);
 const disruption=g.trainDisruptionMultiplier.bind(g);g.trainDisruptionMultiplier=()=>disruption()*(mod('pressure')?C.tuning.pressureSpeed[g.effectiveCarPower(0)]||1:1);
 const range=g.rangeBounds.bind(g);g.rangeBounds=function(t,eq){const r=range(t,eq);if(mod('close'))r.max*=C.tuning.closeRange;if(mod('long'))r.min=Math.max(r.min,C.tuning.longMin);return r;};
 const target=g.targetInRange.bind(g);g.targetInRange=function(e,r){if(mod('long')&&(e.boarded||e.grip>0)&&r.min>B.battle.boardDistance)return false;return target(e,r);};
 const stats=g.turretStats.bind(g);g.turretStats=function(eq,ci,op){const s=stats(eq,ci,op),t=D.TURRETS[eq.type];if(mod('close')&&t.range==='close')s.damage*=C.tuning.closeDamage;if(mod('long')&&t.range==='long')s.damage*=C.tuning.longDamage;if(eq.rageLeft>0)s.damage*=C.tuning.rageDamage;if(mod('grid')&&this.effectiveCarPower(ci)>=4){const p=C.power4.turrets[eq.type]||{};s.damage*=p.damage||1;s.interval*=p.interval||1;s.chains+=p.chains||0;s.splash+=p.splash||0;}return s;};
 const module=g.moduleData.bind(g);g.moduleData=function(eq){const out=module(eq),ci=this.state?.cars.findIndex(c=>c.equipment.includes(eq))??-1,s=this.state;const drained=ci>=0&&((s.enemies||[]).some(e=>!e.dead&&e.linked&&e.drained>0&&e.targetCar===ci)||(s.battle?.parts||[]).some(p=>!p.destroyed&&p.grip>0&&p.type==='drain'&&p.car===ci)||(s.interference||[]).some(e=>e.kind==='power'&&e.car===ci&&e.left>0&&!e.owner.dead&&!e.owner.destroyed));if(mod('grid')&&ci>=0&&s.cars[ci].power>=4&&!drained){const factor=(C.power4.modules[eq.type]||C.power4.defaultModule)/REVISION_CONFIG.modulePower[4];for(const k of ['heatMult','coolingMult','stageHealMult','repairMult','ammoDamageMult'])if(k in out)out[k]=1+(out[k]-1)*factor;if(eq.type==='generator'&&out.extraPower>0)out.extraPower=D.MODULES.generator.extraPower+C.power4.generatorExtraPower;}return out;};
 const cooling=g.turretCooling.bind(g);g.turretCooling=(eq,...a)=>eq.rageLeft>0?0:cooling(eq,...a);
 const fire=g.fireTurret.bind(g);g.fireTurret=function(eq,stats,...args){if(mod('rage')&&eq.heat+stats.heat>=B.heat.max&&!eq.rageLeft&&!eq.rageCooling){eq.rageLeft=C.tuning.rageSeconds;stats={...stats,damage:stats.damage*C.tuning.rageDamage};this.playSound('commandRise');}return fire(eq,stats,...args);};
 g.updateRage=function(eq,dt){if(!mod('rage'))return;if(eq.rageCooling){if(eq.heat<=0){eq.rageCooling=false;eq.overheated=false;}return;}if(eq.rageLeft>0){eq.rageLeft=Math.max(0,eq.rageLeft-dt);if(!eq.rageLeft){eq.rageCooling=true;eq.overheated=true;}return;}if(eq.overheated){eq.rageLeft=C.tuning.rageSeconds;this.playSound('commandRise');}};
 const heal=g.healAfterStage.bind(g);g.healAfterStage=function(){heal();if(mod('repair'))for(const car of this.state.cars){car.hp=Math.min(car.maxHp,car.hp+car.maxHp*C.tuning.afterHeal);if(car.hp>0){car.repair=0;car.destroyedLogged=false;}}};
 const update=g.updateCrew.bind(g);g.updateCrew=function(dt){update(dt);const s=this.state;s.metaTick=(s.metaTick||0)+dt;if(s.metaTick<1)return;const seconds=Math.floor(s.metaTick);s.metaTick-=seconds;const before={state:s,cars:s.cars.map(c=>c.hp),crew:s.crew.map(c=>({id:c.id,hp:c.hp}))};for(const [i,c]of s.cars.entries()){if(c.hp<=0)continue;let hp=c.armor>0?value('armorHeal')*seconds:0;if(i===0&&s.orders.command.active<=0&&!c.breakerBroken&&!this.bossCarSealed?.(i))hp+=value('engineHeal')*seconds;c.hp=Math.min(c.maxHp,c.hp+hp);if(i===0&&mod('pressure')&&this.effectiveCarPower(0)>=4&&c.armor<=0)c.hp=Math.max(0,c.hp-c.maxHp*C.tuning.pressureHpPerSecond*seconds);}this.reportHealthChanges?.(before);};
 const check=g.checkBattleState.bind(g);g.checkBattleState=function(){if(mod('captain')&&this.state.crew.some(c=>c.captain&&c.dead))return this.gameOver('현장 열차장이 사망했습니다.');return check();};
 const equipmentHTML=g.equipmentHTML.bind(g);g.equipmentHTML=function(eq,...args){let html=equipmentHTML(eq,...args);if(mod('rage')&&eq.kind==='turret')html+=`<p class="${eq.rageCooling?'negative':'positive'}">${eq.rageLeft>0?'과열 폭주 · 남은 '+eq.rageLeft.toFixed(1)+'초 · 피해 +25%':eq.rageCooling?'강제 냉각 · 열 0까지 사격 불가':'과열 시 3초간 폭주 후 열 0까지 강제 냉각'}</p>`;if(this.metaEquipmentLocked(eq))html+='<p class="negative">특수 장갑 고정 포탑 · 판매/재배치 불가</p>';if(mod('grid'))html+='<p>출력 4: 장비별 고유 효과 추가 · 현재 표시 수치에 반영</p>';return html;};
 const station=g.renderStation.bind(g);g.renderStation=function(){station();if(mod('random')){const note=document.createElement('p');note.className='negative';note.textContent='무작위 무장 개조: 정비소 입고 시 장비가 무작위로 결정됩니다. 표시된 장비와 강화 상태 그대로 구매합니다.';document.querySelector('#shop-content')?.prepend(note);}};
 g.metaEquipmentLocked=eq=>!!eq&&eq.kind==='turret'&&mod('armor');
 const rearrange=g.rearrange.bind(g);g.rearrange=function(kind,id,to){if(kind==='equipment'&&this.metaEquipmentLocked(this.findEquipment(id))){this.toast('특수 장갑 개조: 포탑은 고정되어 이동할 수 없습니다.');return false;}return rearrange(kind,id,to);};
 const render=g.renderCars.bind(g);g.renderCars=function(){render();if(mod('captain'))for(const el of document.querySelectorAll('[data-captain]')){el.classList.add('upgrade-robot');el.setAttribute('aria-label','강화 로봇');el.innerHTML='<span style="font-size:28px">▣</span><span class="crew-tag">강화 로봇</span>';}};
 const captain=g.renderCaptain.bind(g);g.renderCaptain=function(){captain();if(mod('captain'))document.querySelector('.captain-console h3').textContent='강화 로봇';if(!value('revive'))return;const box=document.createElement('section'),s=this.state,ci=s.orders.command.active>0?s.orders.command.car:null,uses=value('revive')-(s.revivesUsed||0);box.innerHTML=`<h4>구급 키트 · 남은 ${uses}회</h4><p>직접 지휘 중인 객차의 전투불능 직원을 선택해 회복합니다.</p>`;for(const c of s.crew.filter(c=>!c.dead&&c.hp<=0&&c.car===ci)){const button=document.createElement('button');button.textContent=c.name+' 완전 회복';button.disabled=uses<=0;button.onclick=e=>{e.stopPropagation();if(this.mode!=='battle'||s.orders.command.active<=0||s.orders.command.car!==c.car||c.dead||c.hp>0||s.revivesUsed>=value('revive'))return;c.hp=c.maxHp;s.revivesUsed++;this.playSound('repair');this.renderCars();this.renderCaptain();};box.append(button);}document.querySelector('#inspector').append(box);};
 for(const name of ['bossClear','completeAct','gameOver']){const old=g[name].bind(g);g[name]=function(...args){const before=m.relics,clears=m.clears,act=this.state.actId,wasBattle=this.mode==='battle';const r=old(...args);let changed=false;if(m.relics>before)m.totalEarned+=m.relics-before;
  if(name==='bossClear'&&wasBattle&&act==='act2'&&this.mode!=='battle'){m.act2Clears++;m.maxPoints=Math.max(m.maxPoints,this.modPoints());changed=true;}
  if(name==='bossClear'&&wasBattle&&act==='act3'&&this.mode!=='battle'&&!this.state.act3Recorded09){this.state.act3Recorded09=true;m.act3Clears=(m.act3Clears||0)+1;changed=true;}
  if(m.clears>clears&&['act2','act3','titan'].includes(act)){if(act==='act3'&&!this.state.act3Recorded09)m.act3Clears=(m.act3Clears||0)+1;const n=context()?.apocalypse||0;m.apocalypseCleared=Math.max(m.apocalypseCleared,n);m.apocalypseUnlocked=Math.min(C.apocalypse.length-1,Math.max(m.apocalypseUnlocked,n+1));m.maxPoints=Math.max(m.maxPoints,this.modPoints());}if(changed||m.relics!==before||m.clears!==clears)this.saveMeta();return r;};}
 g.restoreMetaRun=function(){if(!this.state)return;const run=this.state.metaRun??={upgrades:clone(m.upgrades),mods:[],apocalypse:0};if(!Number.isFinite(run.unlockSpent))run.unlockSpent=m.spent;if(!run.unlocks||typeof run.unlocks!=='object')run.unlocks=snapshotUnlocks(run.unlockSpent);for(const kind of Object.keys(unlockRegistries))if(!Array.isArray(run.unlocks[kind]))run.unlocks[kind]=snapshotUnlocks(run.unlockSpent,{})[kind];configure(run);};
})();
