(()=>{
 const g=lastRail,C=MOVEMENT_CONFIG,B=GAME_DATA.BALANCE,root=document.querySelector('.world-panel');
 g.worldLayer=root;root.id='world-stage';
 // HUD stays responsive; only scene objects inhabit the scaled world layer.
 for(const el of root.querySelectorAll('.threat-strip,.speed-controls,.battle-clock,.hint,.battle-note,.stage-banner'))document.body.append(el);
 for(const el of document.querySelectorAll('canvas[aria-hidden="true"]'))root.append(el);
 const style=document.createElement('style');style.textContent=`body{background:#080e13}#world-stage{position:fixed!important;right:auto!important;bottom:auto!important;transform-origin:0 0;overflow:hidden;width:${C.width}px!important;height:${C.height}px!important}#world-stage .canvas-wrap{width:100%;height:100%;inset:0}#world-stage #train-cars{position:absolute;left:${C.train.left}px;right:${C.train.right}px;bottom:${C.train.bottom}px;height:${C.train.height}px;gap:14px;padding:0;min-height:0}#world-stage .railcar{height:145px;min-width:0}#world-stage .equipment-row{bottom:140px;left:7px;right:7px;gap:8px}#world-stage .equipment-button{height:70px}#world-stage .equipment-button svg{height:58px}#world-stage .equipment-button .eq-label{font-size:11px}#world-stage .car-window{inset:42px 10px 30px;gap:8px;padding:2px}#world-stage .crew-sprite,#world-stage .empty-crew{height:52px}#world-stage .crew-sprite svg{width:34px;height:48px}#world-stage .crew-tag{font-size:11px}#world-stage .car-name{font-size:12px!important}#world-stage .power-console{bottom:-28px;height:25px}#world-stage .power-console button{width:24px;height:24px}#world-stage .power-console span{font-size:12px}#world-stage .moving-sprite{position:absolute}#world-stage .station-backdrop{max-width:none}body>.speed-controls,body>.battle-clock,body>.stage-banner{position:fixed}`;document.head.append(style);
 style.textContent+='#world-stage .station-backdrop{left:55%;bottom:165px;width:1650px;max-height:780px}';
 Object.assign(SCENE_CONFIG.motion,C.parallax);B.simulation.maxDelta=C.maxDelta;
 g.resize=function(){const scale=Math.min(innerWidth/C.width,innerHeight/C.height);root.style.left=`${(innerWidth-C.width*scale)/2}px`;root.style.top=`${(innerHeight-C.height*scale)/2}px`;root.style.transform=`scale(${scale})`;this.view={w:C.width,h:C.height};if(this.canvas.width!==C.width||this.canvas.height!==C.height){this.canvas.width=C.width;this.canvas.height=C.height;}this.ctx.setTransform(1,0,0,1,0,0);this.renderCars();};
 addEventListener('resize',()=>g.resize());g.resize();
 let accumulator=0,last=null;
 document.addEventListener('visibilitychange',()=>{last=null;accumulator=0;g.frameDelta=0;});
 g.loop=function(now){const dt=last===null||document.hidden?0:Math.min(C.maxDelta,Math.max(0,(now-last)/1000));last=now;this.lastFrame=now;this.frameDelta=dt;accumulator+=dt;while(accumulator+1e-10>=C.fixedStep){this.update(C.fixedStep);accumulator-=C.fixedStep;}this.draw();requestAnimationFrame(t=>this.loop(t));};
 const titan=g.updateTitan.bind(g);
 g.updateTitan=function(dt){titan(dt);const s=this.state;s.trainSpeed=s.currentTrainSpeed*C.unitsPerKm/C.secondsPerMinute;s.titanSpeed=s.currentTitanSpeed*C.unitsPerKm/C.secondsPerMinute;};
 const update=g.update.bind(g);g.update=function(dt){const s=this.state,b=s?.battle;if(s&&this.mode==='battle'&&b&&s.speed&&!document.querySelector('#overlay').classList.contains('show')){this.updateTitan(0);const base=B.train.speedByPower[B.train.enginePower.start]*C.unitsPerKm/C.secondsPerMinute;b.stageDistance??=b.duration*base;b.distanceTravelled=(b.distanceTravelled||0)+s.trainSpeed*dt*s.speed;b.routeProgress=b.distanceTravelled/base;b.distanceRemaining=Math.max(0,b.stageDistance-b.distanceTravelled);}const result=update(dt);if(s===this.state&&this.mode==='run'&&s?.launchPending&&s.launchElapsed>=B.launch.seconds){s.launchPending=false;s.titanDistance=B.run.startingTitanDistance;this.enterNode();}return result;};
 const enemies=g.updateEnemies.bind(g);g.updateEnemies=function(dt){const base=B.train.speedByPower[B.train.enginePower.start]*C.unitsPerKm/C.secondsPerMinute,f=Math.max(C.minApproach,Math.min(C.maxApproach,1+(base-(this.state.trainSpeed??base))/base*C.relativeWeight)),saved=this.state.enemies.map(e=>[e,e.speed]);for(const[e,speed]of saved){e.moveSpeed=speed*B.battle.enemyApproachSpeed*C.depthUnits;e.speed=speed*f;}try{return enemies(dt);}finally{for(const[e,speed]of saved)e.speed=speed;}};
})();
