/* Direct formation editing, spatial combat effects and the shared audio mixer. */
(() => {
  'use strict';
  const g=window.lastRail,D=window.GAME_DATA,B=D.BALANCE,V=window.SCENE_CONFIG,A=window.LAST_RAIL_SCENE;
  const $=s=>document.querySelector(s),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const prior={};for(const k of ['update','updateParticles','enemyAttack','renderCars','newRun','showMainMenu','toast','recruitCrew','giveRandomGear','upgradeEquipment','executeArmor','executeCommand','executeFocus','buyCar','moveCrew','swapCrew'])prior[k]=g[k].bind(g);

  // All sound sources use one master setting. A missing optional BGM never blocks play.
  let context,master,volume=B.audio.defaultMaster,voices=0,noiseBuffer,lastSound={},windClock=0,railClock=0;
  try{const saved=localStorage.getItem('lastRailVolume');if(saved!==null&&Number.isFinite(Number(saved)))volume=clamp(Number(saved),0,1);}catch{}
  const music=Object.fromEntries(Object.entries(B.audio.bgmTracks).map(([key,path])=>[key,{audio:new Audio(),path,gain:0}]));
  for(const track of Object.values(music)){track.audio.loop=true;track.audio.preload='none';track.audio.addEventListener('error',()=>{track.missing=true;track.audio.pause();});}
  let musicLast=performance.now();
  const audioPanel=document.createElement('label');audioPanel.className='volume-control';audioPanel.innerHTML='<span>전체 음량</span><input type="range" min="0" max="100" step="1" aria-label="전체 소리 볼륨"><output></output>';document.body.append(audioPanel);
  function syncVolume(){audioPanel.querySelector('input').value=Math.round(volume*100);audioPanel.querySelector('output').textContent=`${Math.round(volume*100)}%`;if(master)master.gain.setTargetAtTime(volume,context.currentTime,.02);for(const track of Object.values(music))track.audio.volume=volume*B.audio.bgmGain*track.gain;}
  audioPanel.querySelector('input').oninput=e=>{volume=Number(e.target.value)/100;syncVolume();try{localStorage.setItem('lastRailVolume',String(volume));}catch{};g.playSound('ui');};syncVolume();
  function unlock(){try{if(!context){context=new (window.AudioContext||window.webkitAudioContext)();master=context.createGain();master.connect(context.destination);master.gain.value=volume;noiseBuffer=context.createBuffer(1,context.sampleRate*3,context.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;}if(context.state==='suspended')context.resume().catch(()=>{});}catch{}syncMusic();}
  function syncMusic(){const now=performance.now(),dt=Math.min(.1,(now-musicLast)/1000);musicLast=now;
    const mode=g.mode,stationLike=mode==='station'||mode==='station-placement';
    const act=['act1','act2','act3'].includes(g.state?.actId)?g.state.actId:'act1';
    const desired=['menu','gameover','ending'].includes(mode)||stationLike?'lobby':mode==='battle'&&g.state?.battle?.bossId==='titan'?'titan_boss':`${act}_${mode==='battle'&&g.state?.battle?.boss?'boss':'battle'}`;
    for(const [key,track] of Object.entries(music)){
      if(document.hidden||volume===0){track.audio.pause();continue;}
      const target=key===desired?1:0;track.gain=clamp(track.gain+Math.sign(target-track.gain)*Math.min(Math.abs(target-track.gain),dt/B.audio.bgmFadeSeconds),0,1);
      track.audio.volume=volume*B.audio.bgmGain*track.gain;
      if(track.gain===0&&!target){track.audio.pause();continue;}
      if(!track.loaded){track.loaded=true;track.audio.src=window.LAST_RAIL_ASSETS?.url(track.path)||track.path;}
      if(!track.missing&&!track.starting&&!track.blocked&&track.audio.paused&&context?.state==='running'){track.starting=true;track.audio.play().catch(()=>{track.blocked=true;}).finally(()=>{track.starting=false;});}
    }
  }
  function musicFrame(){syncMusic();requestAnimationFrame(musicFrame);}requestAnimationFrame(musicFrame);
  const resumeAudio=()=>{Object.values(music).forEach(track=>track.blocked=false);unlock();};
  document.addEventListener('pointerdown',resumeAudio,{capture:true});document.addEventListener('keydown',resumeAudio,{capture:true});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){Object.values(music).forEach(track=>track.audio.pause());context?.suspend().catch(()=>{});}else resumeAudio();});
  g.playSound=function(kind){if(!context||context.state!=='running'||volume===0||document.hidden||voices>=B.audio.maxVoices)return;const spec=B.audio[kind]||B.audio.ui,now=context.currentTime;if(now-(lastSound[kind]??-10)<B.audio.minInterval)return;lastSound[kind]=now;
    const source=spec.noise?context.createBufferSource():context.createOscillator(),gain=context.createGain();let filter;
    if(spec.noise){source.buffer=noiseBuffer;filter=context.createBiquadFilter();filter.type=kind==='wind'?'bandpass':'lowpass';filter.frequency.value=spec.frequency;source.connect(filter);filter.connect(gain);}else{source.type=['ui','purchase','recruit','upgrade'].includes(kind)?'sine':'triangle';source.frequency.setValueAtTime(spec.frequency,now);source.frequency.exponentialRampToValueAtTime(spec.end||Math.max(20,spec.frequency*.2),now+spec.duration);source.connect(gain);}
    gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(B.audio.volume*(spec.gain??1),now+Math.min(.03,spec.duration/3));gain.gain.exponentialRampToValueAtTime(.001,now+spec.duration);gain.connect(master);voices++;source.start(now);source.stop(now+spec.duration);source.onended=()=>{voices--;source.disconnect();filter?.disconnect();gain.disconnect();};
  };
  document.addEventListener('click',e=>{if(e.target.closest('button,summary,select')||e.target===$('#game-canvas'))g.playSound('ui');});
  document.addEventListener('change',e=>{if(e.target.matches('select'))g.playSound('ui');});
  for(const [method,sound] of Object.entries({recruitCrew:'recruit',giveRandomGear:'equip',upgradeEquipment:'upgrade',buyCar:'equip',swapCrew:'equip'}))g[method]=function(...args){const result=prior[method](...args);if(result)this.playSound(sound);return result;};
  for(const method of ['executeArmor','executeCommand','executeFocus'])g[method]=function(...args){prior[method](...args);if(this.state&&!this.state.targetMode)this.playSound('skill');};
  g.moveCrew=function(...args){prior.moveCrew(...args);this.playSound('equip');};
  g.toast=function(message){prior.toast(message);this.playSound(/부족|없습니다|불가|확인|수 없습니다/.test(message)?'error':'purchase');};

  // Guides float above the current interface without changing its height.
  const help=document.createElement('section');help.className='floating-guide';help.hidden=true;help.setAttribute('role','dialog');help.setAttribute('aria-label','능력 효과 가이드');help.innerHTML='<header><b></b><button aria-label="가이드 닫기">×</button></header><p></p>';document.body.append(help);let helpAnchor=null,pinned=false;
  function closeHelp(){help.hidden=true;helpAnchor=null;pinned=false;}
  function showHelp(anchor,pin){helpAnchor=anchor;pinned=pin;help.querySelector('b').textContent=anchor.dataset.guideTitle;help.querySelector('p').textContent=anchor.dataset.guide;help.hidden=false;const r=anchor.getBoundingClientRect(),box=help.getBoundingClientRect();help.style.left=`${clamp(r.left,12,Math.max(12,innerWidth-box.width-12))}px`;help.style.top=`${clamp(r.top-box.height-10,12,Math.max(12,innerHeight-box.height-12))}px`;}
  help.querySelector('button').onclick=()=>{const anchor=helpAnchor;closeHelp();anchor?.focus();};
  document.addEventListener('pointerover',e=>{const b=e.target.closest('[data-guide]');if(b&&!pinned)showHelp(b,false);});
  document.addEventListener('pointerout',e=>{if(!pinned&&helpAnchor&&e.target.closest('[data-guide]')===helpAnchor&&!help.contains(e.relatedTarget)&&!helpAnchor.contains(e.relatedTarget))closeHelp();});
  document.addEventListener('click',e=>{const b=e.target.closest('[data-guide]');if(b){if(helpAnchor===b&&pinned)closeHelp();else showHelp(b,true);}else if(!help.contains(e.target))closeHelp();});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!help.hidden){e.stopImmediatePropagation();closeHelp();}},{capture:true});

  // The same distance interval determines target eligibility and the green map band.
  g.rangeBounds=function(t){const o=this.state.orders.focus;return {min:t.minRange?B.targeting[t.minRange]:0,max:B.targeting[t.range]*(o.active>0?1+B.focus.rangeBonus+((Number(this.meta.upgrades.focus)||0)*B.meta.focusRangeBonus):1)};};
  g.enemyOnScreen=function(e){const p=A.project(e,this.view.w,this.view.h);return p.x>=0&&p.x<=this.view.w&&p.y>=0&&p.y<=this.view.h;};
  g.pickTurretTarget=function(ci,t){const range=this.rangeBounds(t),inside=e=>this.enemyOnScreen(e)&&!e.dead&&!e.destroyed&&Math.max(0,e.x)>=range.min&&Math.max(0,e.x)<=range.max;const enemies=this.state.enemies.filter(inside),parts=(this.state.battle?.parts||[]).filter(inside),focus=this.state.orders.focus;if(focus.active>0){const chosen=[...enemies,...parts].find(e=>e.id===focus.target);if(chosen)return chosen;}return enemies.sort((a,b)=>a.x-b.x)[0]||parts.find(p=>p.victory)||parts[0]||null;};
  g.drawTacticalRanges=function(ctx,w,h){const eq=this.inspectedEquipment&&this.findEquipment(this.inspectedEquipment);if(!eq||eq.kind!=='turret'||!document.body.classList.contains('is-tactical'))return;const r=this.rangeBounds(D.TURRETS[eq.type],eq),near=A.project({x:r.min,y:.25},w,h),far=A.project({x:r.max,y:.25},w,h),ci=this.state.cars.findIndex(c=>c.equipment.includes(eq)),active=this.equipmentActive(ci);
    ctx.save();ctx.fillStyle=active?'#71ed9130':'#71ed9115';ctx.strokeStyle='#8be0a1';ctx.lineWidth=2;ctx.fillRect(w*.08,far.y,w*.84,Math.max(1,near.y-far.y));ctx.strokeRect(w*.08,far.y,w*.84,Math.max(1,near.y-far.y));ctx.fillStyle='#b9fac7';ctx.font='13px sans-serif';ctx.fillText(`${D.TURRETS[eq.type].name} 실제 사거리${r.min?' · 안쪽 최소 사거리 제외':''}${active?'':' · 전원/장갑 상태로 가동 중단'}`,w*.09,far.y+20);
    for(const e of [...this.state.enemies,...(this.state.battle?.parts||[])])if(!e.dead&&!e.destroyed&&this.enemyOnScreen(e)&&(this.targetInRange?this.targetInRange(e,r):Math.max(0,e.x)>=r.min&&Math.max(0,e.x)<=r.max)){const p=A.project(e,w,h);ctx.beginPath();ctx.arc(p.x,p.y,p.r+7,0,Math.PI*2);ctx.stroke();}
    if(r.min===0){document.querySelectorAll('[data-car-index]').forEach(el=>{const rect=worldRect(el);ctx.fillStyle='#71ed9118';ctx.fillRect(rect.left,rect.top,rect.width,rect.height);});}ctx.restore();
  };

  // Two stable wider-than-screen tiles per layer, moved only after fully exiting.
  let mountainWidth=0,mountainClock=null,mountainLayers=[];
  g.drawMountainLayers=function(ctx,w,h,clock){const config={...V.mountains,...V.actMountains?.[this.state?.actId]},L=w*Math.max(1.1,config.tileWidthRatio),dt=mountainClock===null?0:Math.max(0,clock-mountainClock);mountainClock=clock;
    if(mountainWidth!==w){const ratio=mountainWidth?w/mountainWidth:1;mountainLayers=config.colors.map((_,layer)=>mountainLayers[layer]?.map(tile=>({...tile,x:tile.x*ratio}))||[{x:0,id:0},{x:L,id:1}]);mountainWidth=w;}
    mountainLayers.forEach((tiles,layer)=>{const speed=layer===0?V.motion.mountains:V.motion.hills*layer*.6;tiles.forEach(tile=>tile.x-=dt*speed);tiles.sort((a,b)=>a.x-b.x);while(tiles[0].x+L<=0){const tile=tiles.shift();tile.x=tiles[0].x+L;tiles.push(tile);}
      const base=h*V.horizon+layer*config.layerOffset;ctx.fillStyle=config.colors[layer];for(const tile of tiles){ctx.beginPath();ctx.moveTo(tile.x,base);const stride=L/config.segments;for(let i=0;i<config.segments;i++){const x=tile.x+i*stride,seed=(i*7+tile.id*11+layer*3)%13,peak=base-config.peakHeight*(.35+seed/18)/(layer+1);if(config.profile){for(const [px,py] of config.profile)ctx.lineTo(x+stride*px,base-(base-peak)*py);}else{ctx.lineTo(x,base);ctx.lineTo(x+stride*.22,peak);ctx.lineTo(x+stride*.63,peak+4);ctx.lineTo(x+stride*.88,base);}}ctx.lineTo(tile.x+L+.5,base);ctx.lineTo(tile.x+L+.5,h*V.horizon+V.groundOffset+2);ctx.lineTo(tile.x,h*V.horizon+V.groundOffset+2);ctx.closePath();ctx.fill();}
    });
  };

  // Shell damage is resolved at impact; trajectory, impact ring and damage share coordinates.
  const carPoint=i=>{const p=A.getCarPosition(i);return p?{x:p.x/g.view.w,y:(p.y-35)/g.view.h}:{x:.5,y:.7};};
  const point=e=>{const p=A.project(e,g.view.w,g.view.h);return{x:p.x/g.view.w,y:p.y/g.view.h};};
  const turretShotSound=type=>({gatling:'gatlingShot',cannon:'cannonShot',scatter:'scatterShot',mortar:'mortarShot',tesla:'teslaShot',breaker:'breakerShot',phosphorus:'phosphorusShot',repulsor:'repulsorShot',frost:'frostShot',interceptor:'interceptorShot',sludge:'sludgeShot',penetrator:'penetratorShot'})[type]||'shot';
  g.fireTurret=function(eq,stats,target,ci){const arc=D.TURRETS[eq.type].trajectory==='arc',duration=arc?B.projectile.arcSeconds:B.projectile.directSeconds;this.state.projectiles.push({hostile:false,from:ci,start:carPoint(ci),end:point(target),targetId:target.id,target,tx:target.x,ty:target.y,life:duration,duration,arc,type:eq.type,stats:{...stats}});this.playSound(turretShotSound(eq.type));};
  g.enemyAttack=function(e){if(e.boarded){prior.enemyAttack(e);return;}const data=D.ENEMIES[e.type],arc=data?.trajectory==='arc';const origin=Number.isFinite(e.x)?e:(this.state.battle?.parts?.find(p=>p.type==='cannon'&&!p.destroyed)||this.state.battle?.parts?.find(p=>p.victory&&!p.destroyed)||{x:.8,y:.5});const duration=arc?B.projectile.arcSeconds:B.projectile.enemySeconds;e.muzzle=B.projectile.muzzleSeconds;origin.muzzle=B.projectile.muzzleSeconds;this.state.projectiles.push({hostile:true,start:point(origin),end:carPoint(e.targetCar),life:duration,duration,arc,type:e.type||'boss',attack:{targetCar:e.targetCar,carDamage:e.carDamage,crewDamage:e.crewDamage,name:e.name}});this.playSound(arc?'mortarShot':'enemyShot');};
  function worldDistance(a,b){return Math.hypot(a.x-b.x,(a.y-b.y)/B.projectile.laneSpan);}
  g.resolveProjectile=function(p){
    this.state.impacts??=[];
    if(p.hostile){prior.enemyAttack(p.attack);if(p.arc)this.playSound('explosion');this.state.impacts.push({screen:p.end,hostile:true,life:B.projectile.impactSeconds,arc:p.arc,type:'hostile'});return;}
    const {stats}=p,targets=[...this.state.enemies,...(this.state.battle?.parts||[])].filter(e=>!e.dead&&!e.destroyed&&this.enemyOnScreen(e)),target=targets.find(e=>e.id===p.targetId);
    if(stats.splash){const radius=stats.splash*B.projectile.splashRadiusScale,center={x:p.tx,y:p.ty};const hit=targets.filter(e=>worldDistance(e,center)<=radius).sort((a,b)=>worldDistance(a,center)-worldDistance(b,center));hit.slice(0,B.battle.maxSecondaryTargets).forEach(e=>this.damageEnemy(e,stats.damage,stats.armorPierce));this.state.impacts.push({world:center,radius,screen:p.end,life:B.projectile.impactSeconds,type:p.type,splash:true});this.playSound('explosion');}
    else if(target){this.damageEnemy(target,stats.damage,stats.armorPierce);this.state.impacts.push({world:{x:target.x,y:target.y},radius:.045,screen:p.end,life:B.projectile.impactSeconds*.8,type:p.type,direct:true});}
    if(stats.chains>1&&target){const chains=targets.filter(e=>e.id!==target.id).sort((a,b)=>worldDistance(a,target)-worldDistance(b,target)).slice(0,stats.chains-1);chains.forEach((e,i)=>this.damageEnemy(e,stats.damage*Math.pow(stats.chainRatio,i+1),stats.armorPierce));if(chains.length)this.state.impacts.push({world:{x:target.x,y:target.y},radius:.09,screen:p.end,life:B.projectile.impactSeconds*.9,type:p.type,chain:true});}
  };
  g.updateParticles=function(dt){const s=this.state;for(const p of s.projectiles){if(!p.hostile&&!p.arc&&!p.stats.splash&&p.target&&!p.target.dead&&!p.target.destroyed)p.end=point(p.target);p.life-=dt;if(p.life<=0&&!p.resolved){p.resolved=true;this.resolveProjectile(p);}}s.projectiles=s.projectiles.filter(p=>p.life>0);s.particles.forEach(p=>p.life-=dt);s.particles=s.particles.filter(p=>p.life>0);s.impacts=(s.impacts||[]).map(p=>({...p,life:p.life-dt})).filter(p=>p.life>0);};
  g.drawProjectiles=function(ctx,w,h){if(this.mode!=='battle')return;for(const p of this.state.projectiles){if(!p.start||!p.end)continue;const t=clamp(1-p.life/p.duration,0,1),sample=u=>({x:(p.start.x+(p.end.x-p.start.x)*u)*w,y:(p.start.y+(p.end.y-p.start.y)*u)*h-(p.arc?4*u*(1-u)*h*B.projectile.arcHeight:0)}),a=sample(Math.max(0,t-.1)),b=sample(t);ctx.save();ctx.strokeStyle=p.hostile?'#ff977f':'#e7f0b0';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=p.arc?3:2;ctx.beginPath();ctx.moveTo(a.x,a.y);for(let k=1;k<=5;k++){const q=sample(Math.max(0,t-.1)+Math.min(.1,t)*k/5);ctx.lineTo(q.x,q.y);}ctx.stroke();ctx.beginPath();ctx.arc(b.x,b.y,p.arc?5:3,0,Math.PI*2);ctx.fill();if(t<.3){ctx.globalAlpha=1-t/.3;ctx.beginPath();ctx.arc(p.start.x*w,p.start.y*h,12*(1-t),0,Math.PI*2);ctx.fill();}ctx.restore();}
    for(const e of [...this.state.enemies,...(this.state.battle?.parts||[])])if(e.muzzle>0){const p=A.project(e,w,h);ctx.save();ctx.globalAlpha=e.muzzle/B.projectile.muzzleSeconds;ctx.fillStyle='#ffd098';ctx.beginPath();ctx.arc(p.x,p.y-10,16,0,Math.PI*2);ctx.fill();ctx.restore();}
  };
  g.drawImpactAreas=function(ctx,w,h){const palette=type=>({gatling:['#f7e1a1','#efd17c'],cannon:['#ffd4a0','#ffb36b'],scatter:['#ffd9a6','#f0c27c'],mortar:['#ffcba7','#ff935f'],tesla:['#9ef3ff','#56dfff'],breaker:['#ffd7a5','#e4b870'],phosphorus:['#ffe3ae','#ff8d54'],repulsor:['#b6fff1','#64ead7'],frost:['#d8f6ff','#99deff'],interceptor:['#d5fff2','#7bf0c8'],sludge:['#dce99a','#9db35a'],penetrator:['#dcfbff','#87e3ff'],hostile:['#ffb6a6','#ff8585']})[type]||['#d7f3bf','#a5f3a8'];
    for(const impact of this.state.impacts||[]){const [fill,stroke]=palette(impact.type);const alpha=clamp(impact.life/B.projectile.impactSeconds,0,1);ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=fill+'55';ctx.strokeStyle=stroke;ctx.lineWidth=2.2;
      if(impact.world){const center=A.project(impact.world,w,h),rx=Math.max(10,(impact.radius||.05)*w*.9),ry=Math.max(8,rx*.55);if(impact.type==='tesla'){for(let i=0;i<5;i++){const ang=i*Math.PI*2/5+alpha*2;ctx.beginPath();ctx.moveTo(center.x,center.y);ctx.lineTo(center.x+Math.cos(ang)*(rx+8),center.y+Math.sin(ang)*ry);ctx.stroke();}ctx.beginPath();ctx.arc(center.x,center.y,7+6*(1-alpha),0,Math.PI*2);ctx.fill();}
      else if(impact.type==='repulsor'){ctx.beginPath();ctx.ellipse(center.x,center.y,rx*(1.25-alpha*.25),ry*(1.25-alpha*.25),0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.ellipse(center.x,center.y,rx*.6,ry*.6,0,0,Math.PI*2);ctx.stroke();}
      else if(impact.type==='frost'){for(let i=0;i<6;i++){const ang=i*Math.PI/3;ctx.beginPath();ctx.moveTo(center.x,center.y);ctx.lineTo(center.x+Math.cos(ang)*(rx+6),center.y+Math.sin(ang)*(ry+6));ctx.stroke();}ctx.beginPath();ctx.arc(center.x,center.y,5+4*(1-alpha),0,Math.PI*2);ctx.fill();}
      else {ctx.beginPath();for(let i=0;i<=B.projectile.areaSegments;i++){const angle=i/B.projectile.areaSegments*Math.PI*2,p=A.project({x:clamp(impact.world.x+Math.cos(angle)*(impact.radius||.05),0,1),y:impact.world.y+Math.sin(angle)*(impact.radius||.05)*B.projectile.laneSpan},w,h);if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);}ctx.closePath();ctx.fill();ctx.stroke();if(impact.direct){ctx.beginPath();ctx.arc(center.x,center.y,5+4*(1-alpha),0,Math.PI*2);ctx.fill();}}
      } else {ctx.beginPath();ctx.ellipse(impact.screen.x*w,impact.screen.y*h,impact.arc?48:18,impact.arc?25:12,0,0,Math.PI*2);ctx.fill();ctx.stroke();}
      ctx.restore();
    }};

  // Formation edits use live train slots, with time charged once on completion.
  let formation=null;const finish=document.createElement('section');finish.className='formation-finish';finish.hidden=true;finish.innerHTML='<b>열차 재정비</b><p></p><button>재정비 완료</button>';document.body.append(finish);
  function formationSeconds(){if(!formation)return 0;let moved=0;g.state.cars.forEach((c,ci)=>c.equipment.forEach((eq,slot)=>{if(eq.kind==='turret'&&formation.turrets.has(eq.id)&&formation.turrets.get(eq.id)!==`${ci}:${slot}`)moved++;}));return moved?B.formation.baseSeconds+moved*B.formation.secondsPerChange:0;}
  const sell=document.createElement('button');sell.className='equipment-sale';sell.hidden=true;sell.textContent='판매';document.body.append(sell);
  const saleDialog=document.createElement('dialog');saleDialog.className='sale-confirm';saleDialog.innerHTML='<h3>정말로 판매하겠습니까?</h3><p></p><button data-cancel>취소</button><button data-confirm>판매 확인</button>';document.body.append(saleDialog);let saleId=null;
  function saleQuote(eq){if(g.equipmentSaleQuote)return g.equipmentSaleQuote(eq);const d=(eq.kind==='turret'?D.TURRETS:D.MODULES)[eq.type],invested=eq.investedScrap??((eq.level>=2?B.upgrade.level2Scrap:0)+(eq.level>=3?B.upgrade.level3Scrap:0)+(eq.branch?B.upgrade.branchScrap:0));return{money:Math.floor(d.price*B.sale.moneyRatio),scrap:eq.kind==='turret'?Math.floor(invested*B.sale.turretScrapRatio):0};}
  function refreshSale(){const eq=formation?.selected?.kind==='equipment'&&g.findEquipment(formation.selected.id),anchor=eq&&$(`[data-equipment="${eq.id}"]`);sell.hidden=!anchor||!!g.metaEquipmentLocked?.(eq);if(!anchor)return;const quote=saleQuote(eq),r=anchor.getBoundingClientRect();sell.title=`판매 시 돈 ${quote.money} · 고철 ${quote.scrap} 획득`;sell.setAttribute('aria-label',sell.title);sell.style.left=`${clamp(r.left+r.width/2,70,innerWidth-70)}px`;sell.style.top=`${Math.max(8,r.top-38)}px`;}
  sell.onclick=()=>{const eq=formation?.selected&&g.findEquipment(formation.selected.id);if(!eq)return;saleId=eq.id;const q=saleQuote(eq);saleDialog.querySelector('p').textContent=`${(eq.kind==='turret'?D.TURRETS:D.MODULES)[eq.type].name} Lv.${eq.level||1}${eq.aux?` + 보조 ${D.MODULES[eq.aux.type].name} 함께 판매`:``} · 돈 ${q.money} / 고철 ${q.scrap} 획득`;saleDialog.showModal();saleDialog.querySelector('[data-cancel]').focus();};
  saleDialog.querySelector('[data-cancel]').onclick=()=>saleDialog.close();
  saleDialog.querySelector('[data-confirm]').onclick=()=>{const eq=formation&&g.findEquipment(saleId),car=eq&&g.state.cars.find(c=>c.equipment.includes(eq));if(!car||g.metaEquipmentLocked?.(eq)){saleDialog.close();return;}const q=saleQuote(eq);car.equipment.splice(car.equipment.indexOf(eq),1);g.state.money+=q.money;g.state.scrap+=q.scrap;formation.selected=null;formation.changes++;saleDialog.close();sell.hidden=true;g.rebalancePower();g.refreshFormation();g.renderCars();g.playSound('purchase');};
  g.enterFormation=function(){if(this.mode!=='station'||formation)return;A.cancelSelection();closeHelp();formation={selected:null,changes:0,turrets:new Map(this.state.cars.flatMap((c,ci)=>c.equipment.map((eq,slot)=>eq.kind==='turret'?[eq.id,`${ci}:${slot}`]:null).filter(Boolean)))};this.formationSelectedId=null;this.stationTab='gear';$('#overlay').classList.remove('show');document.body.classList.add('is-formation');finish.hidden=false;this.refreshFormation();this.renderCars();};
  g.refreshFormation=function(){if(!formation)return;const seconds=formationSeconds();finish.querySelector('p').textContent=`장비/직원 → 빈자리 또는 교환 대상 · 모듈 → Lv.3+ 모듈 위 보조 슬롯 · ${formation.changes}회 변경`;finish.querySelector('button').innerHTML=`재정비 완료${this.timeHTML(seconds)}`;};
  function swapMainAndAux(mainId,hostId){
    const main=g.findEquipment(mainId),host=g.findEquipment(hostId),oldAux=host?.aux;if(!main||!host||!oldAux||main===host||main.kind!=='module'||host.kind!=='module'||g.auxHostFor?.(main)||main.aux)return false;
    const car=g.state.cars.find(c=>c.equipment.includes(main));if(!car)return false;const i=car.equipment.indexOf(main);if(i<0)return false;
    car.equipment[i]=oldAux;host.aux=main;g.rebalancePower();g.renderAll?.();return true;
  }
  finish.querySelector('button').onclick=()=>{if(!formation)return;const seconds=formationSeconds();formation=null;g.formationSelectedId=null;finish.hidden=true;sell.hidden=true;saleDialog.close();document.body.classList.remove('is-formation');A.cancelSelection();if(g.spendTime(seconds))g.showStation();g.playSound('equip');};
  $('#train-cars').addEventListener('click',e=>{if(!formation)return;e.stopImmediatePropagation();const car=e.target.closest('[data-car-index]');if(!car)return;const ci=Number(car.dataset.carIndex),auxSlot=e.target.closest('.aux-module-slot'),crew=e.target.closest('[data-crew]'),gear=e.target.closest('[data-equipment]'),blank=e.target.closest('.empty-equipment,.empty-crew');
    if(e.target.closest('[data-output],[data-captain]'))return;
    const selected=formation.selected;
    if(auxSlot){const hostId=auxSlot.dataset.auxHost,auxId=auxSlot.dataset.auxEquipment;
      if(auxId){if(selected?.kind==='equipment'){const source=g.findEquipment(selected.id);if(source?.kind!=='module'){g.toast('보조 슬롯과 교환할 수 있는 것은 일반 모듈뿐입니다.');return;}if(swapMainAndAux(selected.id,hostId)){formation.changes++;formation.selected=null;g.formationSelectedId=null;g.state.selectedCrew=null;g.refreshFormation();g.renderCars();g.playSound('equip');}else g.toast('보조 모듈과 위치를 교환할 수 없습니다. 다른 일반 모듈을 선택하세요.');return;}if(selected?.kind==='aux'&&selected.id===auxId){formation.selected=null;g.formationSelectedId=null;g.renderCars();return;}formation.selected={kind:'aux',id:auxId,hostId};g.formationSelectedId=auxId;g.state.selectedCrew=null;g.renderCars();g.playSound('ui');return;}
      if(!selected){g.toast('보조로 장착할 모듈을 먼저 선택하세요.');return;}if(selected.kind!=='equipment'){g.toast('일반 모듈을 선택한 뒤 빈 보조 슬롯을 누르세요.');return;}const source=g.findEquipment(selected.id);if(source?.kind!=='module'){g.toast('보조 슬롯에는 모듈만 장착할 수 있습니다.');return;}if(g.attachAux(hostId,selected.id)){formation.changes++;formation.selected=null;g.formationSelectedId=null;g.state.selectedCrew=null;g.refreshFormation();g.renderCars();}else g.toast('보조 슬롯 상태와 선택한 모듈을 확인하세요.');return;}
    const hit=crew?{kind:'crew',id:crew.dataset.crew}:gear?{kind:'equipment',id:gear.dataset.equipment}:null;
    if(selected&&hit?.id===selected.id){formation.selected=null;g.formationSelectedId=null;g.state.selectedCrew=null;g.renderCars();return;}
    if(selected?.kind==='aux'&&hit?.kind==='equipment'){const target=g.findEquipment(hit.id);if(target?.kind!=='module'){g.toast('보조 모듈은 일반 모듈과만 위치를 교환할 수 있습니다.');return;}if(swapMainAndAux(hit.id,selected.hostId)){formation.changes++;formation.selected=null;g.formationSelectedId=null;g.state.selectedCrew=null;g.refreshFormation();g.renderCars();g.playSound('equip');}else g.toast('해당 모듈과 위치를 교환할 수 없습니다.');return;}
    let changed=false;
    if(selected?.kind==='aux'&&blank?.matches('.empty-equipment')){changed=g.detachAux(selected.hostId,ci);}
    else if(selected&&hit&&hit.kind===selected.kind){
      if(hit.kind==='crew')changed=g.swapCrew(selected.id,hit.id,true);
      else{const from=g.state.cars.find(c=>c.equipment.some(eq=>eq.id===selected.id)),to=g.state.cars[ci];if(from){const a=from.equipment.findIndex(eq=>eq.id===selected.id),b=to.equipment.findIndex(eq=>eq.id===hit.id);if(g.metaEquipmentLocked?.(from.equipment[a])||g.metaEquipmentLocked?.(to.equipment[b]))g.toast('특수 장갑 개조: 설치된 포탑은 고정됩니다.');else{[from.equipment[a],to.equipment[b]]=[to.equipment[b],from.equipment[a]];g.rebalancePower();changed=true;}}}
    }else if(selected&&blank&&((selected.kind==='crew'&&blank.matches('.empty-crew'))||(selected.kind==='equipment'&&blank.matches('.empty-equipment'))))changed=g.rearrange(selected.kind,selected.id,ci);
    else if(hit){formation.selected=hit;g.formationSelectedId=hit.id;g.state.selectedCrew=hit.kind==='crew'?hit.id:null;g.renderCars();g.playSound('ui');return;}
    if(changed){formation.changes++;formation.selected=null;g.formationSelectedId=null;g.state.selectedCrew=null;g.playSound('equip');}else if(selected&&blank)g.toast(selected.kind==='aux'?'보조 모듈을 내릴 빈 장비 칸을 확인하세요.':'이 위치에는 배치할 수 없습니다.');g.refreshFormation();g.renderCars();
  },true);
  g.renderCars=function(){prior.renderCars();refreshSale();if(!formation){this.formationSelectedId=null;return;}const selected=formation.selected;this.formationSelectedId=selected?.id||null;document.querySelectorAll('#train-cars .empty-equipment').forEach(el=>{if(el.tagName==='BUTTON')return;const button=document.createElement('button');button.className='empty-equipment';button.textContent='+';button.setAttribute('aria-label',`${el.closest('[data-car-index]').getAttribute('aria-label')} 빈 장비 슬롯`);el.replaceWith(button);});document.querySelectorAll('#train-cars .empty-crew').forEach(el=>el.disabled=false);document.querySelectorAll('#train-cars [data-equipment],#train-cars [data-crew]').forEach(el=>el.classList.toggle('formation-selected',el.dataset.equipment===selected?.id||el.dataset.crew===selected?.id));document.querySelectorAll('#train-cars .empty-equipment,#train-cars .empty-crew').forEach(el=>el.classList.toggle('formation-destination',!!selected&&el.matches(selected.kind==='crew'?'.empty-crew':'.empty-equipment')));};

  g.update=function(dt){prior.update(dt);const s=this.state;if(!s)return;const elapsed=this.mode==='battle'&&!$('#overlay').classList.contains('show')?dt*s.speed:0;for(const e of [...s.enemies,...(s.battle?.parts||[])])e.muzzle=Math.max(0,(e.muzzle||0)-elapsed);
    const moving=(this.mode==='battle'&&s.speed>0&&!$('#overlay').classList.contains('show'))||this.mode==='run';if(moving&&!document.hidden){windClock+=dt;railClock+=dt;if(windClock>=B.audio.windInterval){windClock=0;this.playSound('wind');}if(railClock>=B.audio.railInterval/Math.max(.5,s.currentTrainSpeed||1)){railClock=0;this.playSound('rail');}}syncMusic();
  };
  g.newRun=function(){formation=null;this.formationSelectedId=null;finish.hidden=true;sell.hidden=true;saleDialog.close();document.body.classList.remove('is-formation','launch-quake');closeHelp();prior.newRun();this.state.impacts=[];syncMusic();};
  g.showMainMenu=function(){formation=null;this.formationSelectedId=null;finish.hidden=true;sell.hidden=true;saleDialog.close();document.body.classList.remove('is-formation');closeHelp();prior.showMainMenu();syncMusic();};
})();
