/* Runtime upgrades never mutate shared balance data or persistent meta saves. */
(() => {
  'use strict';
  const g=window.lastRail,D=window.GAME_DATA,B=D.BALANCE,P=window.PROGRESSION_CONFIG,A=window.LAST_RAIL_SCENE;
  const $=s=>document.querySelector(s),labels={combat:'전투',operate:'운용',repair:'수리',recovery:'회복'};
  const old={};for(const k of ['makeInitialState','prepareActShop','recruitCrew','stationCrewPrice','effectiveStat','updateCrew','resolveProjectile','damageEnemy','executeFocus','executeCommand','executeArmor','updateOrders','battleClear','applyResult','renderCars','crewHTML','updateHUD','draw'])old[k]=g[k].bind(g);
  const level=id=>g.state?.runUpgrades?.[id]||0;
  g.crewForCar=ci=>g.state.crew.filter(c=>!c.dead&&c.hp>0&&!c.moving&&c.car===ci);
  g.departureDistance=()=>B.run.branchDistanceBonus+level('escape')*P.upgrades.escape.distance;
  g.crewMoveMultiplier=()=>1+level('movement')*P.upgrades.movement.speed;
  g.commandStatBonus=()=>B.crew.directCommandBonus+level('command')*P.upgrades.command.stat;
  g.focusDamageBonus=()=>B.focus.damageBonus+level('focus')*P.upgrades.focus.damage;
  g.armorDuration=()=>B.armor.duration+level('armor')*P.upgrades.armor.duration;
  g.crewXpRequired=c=>(c.level||1)>=P.crew.maxLevel?Infinity:Math.ceil((P.crew.xpBase+((c.level||1)-1)*P.crew.xpPerLevel)*P.stars.xpMultiplier[c.stars||1]);
  function addTalent(c,list,random=Math.random){const pool=Object.keys(D.TRAITS).filter(id=>!c.traits.includes(id)&&(!D.TRAITS[id].unlockSpent||g.meta.spent>=D.TRAITS[id].unlockSpent));if(!pool.length)return false;const id=pool[Math.floor(random()*pool.length)];list.push(id);c.traits.push(id);return true;}
  function promote(c,random){const target=c.level>=P.stars.promotion[3]?3:c.level>=P.stars.promotion[2]?2:1;while(c.stars<target){c.stars++;addTalent(c,c.starTraits,random);}}
  function invest(c,points){for(let n=0;n<points;n++){const stat=Object.keys(labels)[Math.floor(Math.random()*Object.keys(labels).length)];c.stats[stat]+=P.crew.statGain;c.training[stat]+=P.crew.statGain;}}
  g.rollCrewStars=function(){const t=Math.max(0,Math.min(1,(this.globalStage()-1)/(P.stars.progressStages-1))),weights=P.stars.initialWeights.map((v,i)=>v+(P.stars.finalWeights[i]-v)*t);let roll=Math.random();for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<0)return i+1;}return 3;};
  function initializeCrew(c,recruitLevel=1,stars=1){c.level=Math.min(P.crew.maxLevel,(P.stars.promotion[stars+1]||P.crew.maxLevel+1)-1,recruitLevel);c.stars=stars;c.birthStars=stars;c.xp=0;c.pendingStats=0;c.past=c.background;c.traits=[];c.starTraits=[];c.eventTraits=[];c.training={combat:0,operate:0,repair:0,recovery:0};invest(c,P.stars.statBonus[stars]);for(let i=1;i<stars;i++)addTalent(c,c.starTraits);if(c.level>1)invest(c,c.level);return c;}
  g.makeInitialState=function(){const s=old.makeInitialState();s.runUpgrades={};s.crew.forEach(c=>initializeCrew(c,1,1));return s;};
  g.prepareActShop=function(){old.prepareActShop();const offers=this.stationOffers;if(!offers||offers.progressionReady)return;offers.progressionReady=true;const recruitLevel=Math.min(P.crew.maxRecruitLevel,1+Math.floor((this.globalStage()-1)/P.crew.recruitStageStep));offers.crew=offers.crew.map(c=>initializeCrew({...c,stats:{...c.stats}},recruitLevel,this.rollCrewStars()));};
  g.stationCrewPrice=function(i){return Math.ceil(old.stationCrewPrice(i)*P.stars.priceMultiplier[this.stationOffers?.crew[i]?.birthStars||1]);};
  g.recruitCrew=function(template){if(template?.level)return old.recruitCrew(template);const candidates=D.CREW_TEMPLATES.filter(t=>!this.state.crew.some(c=>c.name===t.name)),base=template||candidates[Math.floor(Math.random()*candidates.length)];if(!base)return false;return old.recruitCrew(initializeCrew({...base,stats:{...base.stats}},Math.min(P.crew.maxRecruitLevel,1+Math.floor((this.globalStage()-1)/P.crew.recruitStageStep)),this.rollCrewStars()));};
  g.effectiveStat=function(c,stat){return old.effectiveStat(c,stat)+c.traits.reduce((n,id)=>n+(D.TRAITS[id].allStats||0),0);};
  g.crewXpMultiplier=function(c){const own=c.traits.reduce((n,id)=>n*(D.TRAITS[id].xpMultiplier??1),1),teachers=this.crewForCar(c.car).reduce((n,ally)=>n+ally.traits.reduce((v,id)=>v+(D.TRAITS[id].crewXpBonus||0),0),0);return own*(1+teachers);};
  g.grantCrewXp=function(c,amount,random=Math.random){if(c.dead||!(amount>0)||(c.level||1)>=P.crew.maxLevel)return 0;if(c.level===undefined)initializeCrew(c);const gained=amount*this.crewXpMultiplier(c);c.xp=Number((c.xp+gained).toFixed(4));while(c.level<P.crew.maxLevel&&c.xp>=this.crewXpRequired(c)){c.xp-=this.crewXpRequired(c);c.level++;c.pendingStats++;promote(c,random);this.playSound('upgrade');}if(c.level>=P.crew.maxLevel)c.xp=0;return gained;};
  g.grantEventTalent=function(c){if(c.dead)return false;c.eventTraits??=[];if(c.eventTraits.length>=P.stars.eventTalentSlots)return false;return addTalent(c,c.eventTraits);};
  g.availableEvents=function(){const canRepair=this.state.cars.some(c=>c.hp<c.maxHp),canLearn=this.state.crew.some(c=>!c.dead&&(c.eventTraits?.length||0)<P.stars.eventTalentSlots);return D.EVENTS.filter(ev=>!ev.choices.some(c=>!canRepair&&(c.result?.repairAll||c.risk?.repairAll))).filter(ev=>!ev.choices.some(c=>!canLearn&&c.result?.crewTalent));};
  g.eventChoiceHint=function(choice){return choice.hint+(choice.result?.healCrew?` · 이미 HP가 가득 찬 직원은 경험치 ${P.crew.fullHealXp} 획득 (재능 보정·최대 레벨 제외)`:'');};
  // A projectile owns its firing car, including splash, chain and double-barrel kills.
  let shot=null;
  g.resolveProjectile=function(p){const previous=shot;shot=p;try{return old.resolveProjectile(p);}finally{shot=previous;}};
  g.damageEnemy=function(e,...args){const alive=e&&!e.dead&&!e.destroyed;old.damageEnemy(e,...args);if(!alive||(!e.dead&&!e.destroyed)||!shot||shot.hostile||!Number.isInteger(shot.from))return;
    const xp='destroyed'in e?P.crew.bossPartXp:P.crew.killXp;
    for(const c of this.crewForCar(shot.from))this.grantCrewXp(c,xp);
  };
  g.executeFocus=function(target){old.executeFocus(target);const o=this.state.orders.focus;if(o.target===target.id&&o.active>0)o.active+=level('focus')*P.upgrades.focus.duration;};
  g.executeCommand=function(ci){old.executeCommand(ci);const o=this.state.orders.command;if(o.car===ci&&o.active>0)o.active+=level('command')*P.upgrades.command.duration;};
  g.executeArmor=function(ci){const before=this.state.armorCharge;old.executeArmor(ci);if(this.state.armorCharge<before)this.state.cars[ci].armor=this.armorDuration();};
  g.updateOrders=function(dt){old.updateOrders(dt);for(const c of this.state.crew)if(c.returnFireVisual)c.returnFireVisual.life=Math.max(0,c.returnFireVisual.life-dt);for(const id of ['focus','command']){const o=this.state.orders[id];o.cooldown=Math.max(0,o.cooldown-dt*level(id)*P.upgrades[id].cooldownRate);}};
  g.crewReturnFire=function(c,dt){if(this.state.cars[c.car].armor>0)return;const R=P.returnFire;c.returnFireCooldown=Math.max(0,(c.returnFireCooldown||0)-dt);if(c.returnFireCooldown>0)return;const target=this.state.enemies.filter(e=>!e.dead&&!e.boarded&&e.x<=R.range&&this.enemyOnScreen(e)).sort((a,b)=>a.x-b.x)[0];if(!target)return;const combat=Math.max(0,this.effectiveStat(c,'combat')),chance=Math.max(R.hitMin,Math.min(R.hitMax,R.hitBase+combat*R.hitPerCombat)),hit=Math.random()<chance,point=A.project(target,this.view.w,this.view.h);c.returnFireCooldown=R.interval;c.returnFireVisual={x:(point.x+(hit?0:R.missOffset))/this.view.w,y:(point.y-(hit?0:R.missOffset))/this.view.h,life:R.seconds,hit};this.playSound('shot');if(hit){let damage=R.damageBase+combat*R.damagePerCombat;if(c.traits.includes('marksman'))damage*=D.TRAITS.marksman.damageMult;this.damageEnemy(target,damage,0);}};
  g.battleClear=function(...args){const s=this.state;if(this.mode==='battle'){const gain=s.battle.elite?B.armor.eliteCharge:B.armor.battleCharge;s.armorCharge=Math.min(B.armor.maxCharge,s.armorCharge+gain*level('armor')*P.upgrades.armor.charge);}return old.battleClear(...args);};
  g.applyResult=function(result){const full=result?.healCrew?this.state.crew.filter(c=>!c.dead&&c.hp>=c.maxHp):[];const out=old.applyResult(result?.armor?{...result,armor:result.armor*(1+level('armor')*P.upgrades.armor.charge)}:result);for(const c of full)this.grantCrewXp(c,P.crew.fullHealXp);if(result?.crewTalent){const eligible=this.state.crew.filter(c=>!c.dead&&(c.eventTraits?.length||0)<P.stars.eventTalentSlots),c=eligible[Math.floor(Math.random()*eligible.length)];if(c&&this.grantEventTalent(c))this.playSound('upgrade');}return out;};
  g.crewStatGuides=function(){return{
    combat:`전투 1당 승선 적 대상 개인화기 DPS +${B.crew.personalDpsPerCombat}, 직원 피격 피해 ${B.crew.boarderDamageReductionPerCombat*100}% 감소 (최대 ${B.crew.maxDamageReduction*100}%). 승선 적과 싸우지 않을 때 초근거리 대응사격: ${P.returnFire.interval}초마다 피해 ${P.returnFire.damageBase}+전투×${P.returnFire.damagePerCombat}, 명중률 ${P.returnFire.hitBase*100}%+전투×${P.returnFire.hitPerCombat*100}%p (최대 ${P.returnFire.hitMax*100}%).`,
    operate:`같은 객차의 활동 직원 운용을 모두 합산합니다. 합계 1당 포탑 피해 +${P.crew.operateDamagePerPoint*100}% (최대 ${P.crew.maxOperateDamage*100}%), 발열 −${B.heat.operatorHeatReductionPerPoint*100}%, 냉각 +${B.heat.operatorCoolingBonusPerPoint*100}% (발열·냉각 최대 각 ${B.heat.maxOperatorModifier*100}%). 직원 특성도 전원 적용됩니다. 이동·전투불능·사망 중에는 제외됩니다.`,
    repair:`모든 활동 직원은 객차 HP ${P.crew.repairStart*100}% 이하에서 자동 수리를 시작하고 ${P.crew.repairStop*100}%까지 수리합니다. 직원마다 초당 수리 × ${B.train.repairStatScale} HP, 모듈·응급수리공 배율 적용. 파괴 객차는 초당 ${B.train.repairBasePerSecond}+수리 × ${B.train.repairStatScale} 복구 진행, ${B.train.repairGoal} 도달 시 HP ${B.train.restoredHpRatio*100}%로 복원합니다.`,
    recovery:`전투 후 회복 1당 최대 HP의 ${B.crew.stageHealPerRecovery*100}% 회복. 의료 모듈과 야전의무병 배율이 추가 적용됩니다.`
  };};
  g.crewGrowthText=function(c){return `${'★'.repeat(c.stars||1)} · Lv.${c.level||1} · ${c.level>=P.crew.maxLevel?'최대 레벨':`경험치 ${Number((c.xp||0).toFixed(2))}/${this.crewXpRequired(c)}`}`;};
  g.crewHTML=function(c,...args){return old.crewHTML(c,...args)+`<p class="crew-growth">${this.crewGrowthText(c)}${c.pendingStats?` · <strong class="positive">능력 선택 ${c.pendingStats}회 대기 !</strong>`:''}</p><p>성급 재능 ${c.starTraits?.length||0}/2 · 이벤트 재능 ${c.eventTraits?.length||0}/${P.stars.eventTalentSlots}</p>`;};
  g.renderCars=function(){old.renderCars();if(!this.state)return;for(const c of this.state.crew){const el=document.querySelector(`[data-crew="${c.id}"]`);if(!el)continue;const pending=!c.dead&&(c.pendingStats||0)>0;el.classList.toggle('crew-level-ready',pending);el.querySelector('.crew-level-mark')?.remove();if(pending){const mark=document.createElement('span');mark.className='crew-level-mark';mark.textContent='!';mark.setAttribute('aria-label',`직원 능력 선택 ${c.pendingStats}회 대기`);el.append(mark);}}};
  g.openCaptain=function(){if(this.mode!=='battle')return;A.cancelSelection();this.setTactical(true);this.captainTab=this.captainTab||'train';this.renderCaptain();};
  g.renderCaptain=function(){const inspector=$('#inspector'),tab=this.captainTab||'train';let content='';
    if(tab==='train')content='<p>고철을 사용하며, 현재 런이 끝나면 초기화됩니다.</p>'+Object.entries(P.upgrades).map(([id,d])=>{const n=level(id),cost=d.costs[n];return `<article class="upgrade-entry"><b>${d.name} Lv.${n}/${d.costs.length}</b><p>${d.text} / 레벨</p><button data-run-upgrade="${id}" ${cost===undefined||this.state.scrap<cost?'disabled':''}>${cost===undefined?'최대 강화':`강화 · ▰ ${cost}`}</button></article>`;}).join('');
    if(tab==='turret')content=this.upgradeHTML();
    if(tab==='crew')content=this.state.crew.filter(c=>!c.dead).map(c=>`<article class="crew-training"><h3>${c.name}</h3><p>${this.crewGrowthText(c)} · 대기 포인트 ${c.pendingStats||0}</p><div class="crew-training-stats">${Object.keys(labels).map(k=>`<button data-train-crew="${c.id}" data-stat="${k}" ${(c.pendingStats||0)>0?'':'disabled'}>${labels[k]} ${c.stats[k]}<br><span class="positive">+${P.crew.statGain}</span></button>`).join('')}</div></article>`).join('')||'<p>강화할 직원이 없습니다.</p>';
    inspector.innerHTML=`<div class="captain-console"><nav class="captain-tabs" aria-label="열차장 강화 분류">${[['train','열차 강화'],['turret','포탑 강화'],['crew','직원 강화']].map(([id,label])=>`<button data-captain-tab="${id}" aria-pressed="${id===tab}" class="${id===tab?'active':''}">${label}</button>`).join('')}</nav><h3>열차장</h3><p>고철 ▰ <span class="captain-scrap">${Math.floor(this.state.scrap)}</span></p>${content}</div>`;
    inspector.onclick=e=>{const tabButton=e.target.closest('[data-captain-tab]');if(tabButton){this.captainTab=tabButton.dataset.captainTab;this.playSound('select');this.renderCaptain();return;}
      const run=e.target.closest('[data-run-upgrade]');if(run){const id=run.dataset.runUpgrade,d=P.upgrades[id],cost=d?.costs[level(id)];if(this.mode!=='battle'||cost===undefined||this.state.scrap<cost)return;this.state.scrap-=cost;this.state.runUpgrades??={};this.state.runUpgrades[id]=level(id)+1;this.playSound('upgrade');this.renderCaptain();this.updateHUD();return;}
      const crew=e.target.closest('[data-train-crew]');if(crew){const c=this.state.crew.find(c=>c.id===crew.dataset.trainCrew),stat=crew.dataset.stat;if(this.mode!=='battle'||!c||c.dead||!(stat in labels)||!(c.pendingStats>0))return;c.stats[stat]+=P.crew.statGain;c.training??={};c.training[stat]=(c.training[stat]||0)+P.crew.statGain;c.pendingStats--;this.playSound('upgrade');this.renderCaptain();this.renderCars();return;}
      const eq=e.target.closest('[data-upgrade-id]');if(eq&&this.upgradeEquipment(eq.dataset.upgradeId,eq.dataset.moduleModel))this.renderCaptain();
    };
    this.captainRevision=this.captainStateKey();
  };
  g.captainStateKey=function(){return JSON.stringify([Math.floor(this.state.scrap),this.state.crew.map(c=>[c.id,c.xp,c.pendingStats,c.dead])]);};
  g.updateHUD=function(){old.updateHUD();if(this.state&&this.mode==='battle'&&document.body.classList.contains('is-tactical')&&$('.captain-console')&&this.captainRevision!==this.captainStateKey())this.renderCaptain();};
  g.draw=function(){
    old.draw();if(this.mode!=='battle'||!this.state)return;const ctx=this.ctx;
    ctx.save();for(const c of this.state.crew){const shot=c.returnFireVisual,from=A.getCarPosition(c.car);if(shot?.life>0&&from){ctx.globalAlpha=shot.life/P.returnFire.seconds;ctx.strokeStyle=shot.hit?'#fff1bd':'#b1beb8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(from.x,from.y-20);ctx.lineTo(shot.x*this.view.w,shot.y*this.view.h);ctx.stroke();ctx.fillStyle='#fff1bd';ctx.beginPath();ctx.arc(from.x,from.y-20,4,0,Math.PI*2);ctx.fill();}
      if(c.moving){const el=document.querySelector(`.moving-sprite[data-id="${c.id}"]`);if(c.pendingStats>0&&el&&!el.querySelector('.crew-level-mark')){const mark=document.createElement('span');mark.className='crew-level-mark';mark.textContent='!';el.append(mark);}else if(!c.pendingStats)el?.querySelector('.crew-level-mark')?.remove();}
    }ctx.restore();
    const b=this.state.battle;if(!b?.rhythm)return;const pending=b.rhythm.queue.filter(e=>e.side==='left'&&e.warningAt!==undefined&&b.elapsed-e.warningAt<P.leftWarning.seconds);if(!pending.length)return;const v=P.leftWarning,positions=this.state.cars.map((_,i)=>A.getCarPosition(i)).filter(Boolean),y=positions.length?positions.reduce((n,p)=>n+p.y,0)/positions.length:this.view.h*.65;
    ctx.save();ctx.fillStyle='#ef39392b';ctx.strokeStyle='#ff5555';ctx.lineWidth=3;ctx.fillRect(2,y-v.height/2,v.width,v.height);ctx.strokeRect(2,y-v.height/2,v.width,v.height);ctx.restore();
  };
})();
