(()=>{
 const g=lastRail,D=GAME_DATA,B=D.BALANCE,R=REVISION_CONFIG,$=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const module=g.moduleData.bind(g);g.moduleData=function(eq){const m=module(eq),ci=this.state?.cars.findIndex(c=>c.equipment.includes(eq))??-1,p=ci<0?1:this.state.cars[ci].power,f=R.modulePower[Math.min(p,R.modulePower.length-1)];for(const k of ['heatMult','coolingMult','stageHealMult','repairMult','ammoDamageMult'])if(k in m)m[k]=1+(m[k]-1)*f;if('extraPower'in m)m.extraPower*=f;return m;};
 const curve=g.stageCurve.bind(g);g.stageCurve=function(){const c={...curve()};if(this.state?.battle?.elite&&!this.state.battle.boss){c.hp*=R.elite.hp;c.damage*=R.elite.damage;}return c;};
 g.repairPlan=function(){const cars=this.state.cars,missing=cars.reduce((n,c)=>n+c.maxHp-c.hp,0),cap=cars.reduce((n,c)=>n+c.maxHp,0)*R.repairCap,budget=Math.max(0,Math.floor(this.state.money)),amount=Math.min(missing,cap,budget/B.station.repairMoneyPerHp);return{amount,cost:Math.min(budget,Math.ceil(amount*B.station.repairMoneyPerHp-1e-8)),cap};};
 g.repairCost=()=>g.repairPlan().cost;
 const action=g.stationAction.bind(g);g.stationAction=function(button){if(button.dataset.stationAction!=='repair')return action(button);const p=this.repairPlan();if(!p.amount)return this.toast('수리 예산이 없거나 모든 객차가 온전합니다.');const before={state:this.state,cars:this.state.cars.map(c=>c.hp),crew:this.state.crew.map(c=>({id:c.id,hp:c.hp}))};this.state.money-=p.cost;let left=p.amount,eligible=this.state.cars.filter(c=>c.hp<c.maxHp);while(left>.000001&&eligible.length){const share=left/eligible.length;for(const c of eligible){const n=Math.min(share,c.maxHp-c.hp);c.hp+=n;left-=n;if(c.hp>0){c.destroyedLogged=false;c.repair=0;}}eligible=eligible.filter(c=>c.hp<c.maxHp-.000001);}this.reportHealthChanges?.(before,true);this.playSound('repair');if(this.spendTime(B.station.actionSeconds.repair))this.renderStation();};
 const shop=g.prepareActShop.bind(g);g.prepareActShop=function(){shop();const offers=this.stationOffers;if(offers.revisionReady)return;offers.revisionReady=true;const people=this.state.crew.filter(c=>!c.dead),average=people.reduce((n,c)=>n+c.level,0)/Math.max(1,people.length),canThree=people.some(c=>c.stars>=2),P=PROGRESSION_CONFIG;
  for(const c of offers.crew){const min=Math.max(1,Math.ceil(average)),max=Math.max(min,Math.floor(average+R.crewLevelBonus)),target=Math.min(P.crew.maxLevel,min+Math.floor(Math.random()*(max-min+1)));let star=Math.max(c.stars,target>=P.stars.promotion[3]&&canThree?3:target>=P.stars.promotion[2]?2:1);if(!canThree)star=Math.min(star,2);const base=D.CREW_TEMPLATES.find(t=>t.name===c.name);c.stars=c.birthStars=star;c.stats={...base.stats};c.training={combat:0,operate:0,repair:0,recovery:0};c.level=target;c.starTraits=c.starTraits.slice(0,star-1);while(c.starTraits.length<star-1){const pool=Object.keys(D.TRAITS).filter(id=>D.TRAITS[id].canBeNormalSkill!==false&&!c.starTraits.includes(id)&&(!D.TRAITS[id].unlockSpent||g.meta.spent>=D.TRAITS[id].unlockSpent));if(!pool.length)break;c.starTraits.push(pool[Math.floor(Math.random()*pool.length)]);}c.traits=[...c.starTraits];for(let i=0;i<P.stars.statBonus[star]+(target>1?target:0);i++){const keys=Object.keys(c.stats),k=keys[Math.floor(Math.random()*keys.length)];c.stats[k]+=P.crew.statGain;c.training[k]+=P.crew.statGain;}}
 };
 const cards=g.renderCars.bind(g);g.renderCars=function(){cards();if(!this.state)return;this.state.cars.forEach((c,i)=>{const bar=$(`[data-car-index="${i}"] .hull-hp i`);if(bar)bar.style.background=R.hpColors.find(([max])=>c.hp/c.maxHp<=max)?.[1]||R.hpColors.at(-1)[1];});};
 // HP updates formerly replaced crew buttons between pointer-down and click.
 let pressed=null,suppressClick=null;const deck=$('#train-cars');deck.addEventListener('pointerdown',e=>{suppressClick=null;pressed=e.target.closest('[data-crew]')?.dataset.crew||null;},true);deck.addEventListener('pointercancel',()=>pressed=null,true);deck.addEventListener('pointerup',e=>{if(!pressed||g.mode!=='battle')return;const id=pressed;pressed=null;const current=deck.querySelector(`[data-crew="${id}"]`),hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-car-index]');if(current&&hit?.dataset.carIndex===current.closest('[data-car-index]').dataset.carIndex){e.preventDefault();suppressClick=id;current.click();}},true);deck.addEventListener('click',e=>{if(e.isTrusted&&suppressClick&&e.target.closest('[data-crew]')?.dataset.crew===suppressClick){suppressClick=null;e.stopImmediatePropagation();e.preventDefault();}},true);
 const hud=g.updateHUD.bind(g);g.updateHUD=function(){hud();const stopped=['station','event','event-placement'].includes(this.mode);document.body.classList.toggle('train-stopped',stopped);if(this.state){$('#stage-label').textContent=this.state.stageIndex>=R.stages?'BOSS':`${this.state.stageIndex+1} / ${R.stages}`;if(stopped)$('#train-speed').textContent='0.00';}};
 let arrival=null,parked=null;const station=document.createElement('img');station.src='./station-background.png';station.alt='';station.className='station-backdrop';station.hidden=true;document.querySelector('.canvas-wrap').append(station);
 function arrive(kind,open,args){if(parked===`${g.state.actId}:${g.state.stageIndex}:${kind}`||g.mode==='station'||g.mode==='event')return open(...args);parked=`${g.state.actId}:${g.state.stageIndex}:${kind}`;/* Prepare and checkpoint fixed contents before braking, then reopen without rerolling. */if(g.checkpointEnabled)open(...args);g.mode='arrival';g.state.speed=0;g.arrivalPace=1.8;arrival={elapsed:0,open,args,kind};g.stationArrivalKind=kind;g.stationArrivalProgress=0;$('#overlay').classList.remove('show');}
 for(const name of ['showStation','showEvent']){const open=g[name].bind(g);g[name]=function(...args){return arrive(name==='showStation'?'station':'event',open,args);};}
 const update=g.update.bind(g);g.update=function(dt){if(arrival&&!this.sceneTransition){if(document.hidden)return;if(!arrival.elapsed){this.playSound('brake');station.hidden=arrival.kind!=='station';if(!matchMedia('(prefers-reduced-motion: reduce)').matches)document.querySelectorAll('.topbar,.threat-strip').forEach(el=>el.animate([{transform:`translateX(-${R.stop.shake}px)`},{transform:`translateX(${R.stop.shake}px)`},{transform:'none'}],{duration:R.stop.seconds*1000}));}arrival.elapsed+=dt;const p=Math.min(1,arrival.elapsed/R.stop.seconds);this.stationArrivalProgress=p;this.arrivalPace=1.8*(1-p)*(1-p);$('#train-cars').style.translate=`${matchMedia('(prefers-reduced-motion: reduce)').matches?0:R.stop.shift*Math.sin(p*Math.PI)}px 0`;if(p===1){const a=arrival;arrival=null;$('#train-cars').style.translate='';a.open(...a.args);}return;}update(dt);};
 for(const name of ['advanceStage','newRun','showMainMenu']){const old=g[name].bind(g);g[name]=function(...a){arrival=null;parked=null;delete this.arrivalPace;station.hidden=true;$('#train-cars').style.translate='';return old(...a);};}
 const render=g.renderStation.bind(g);g.renderStation=function(){render();const b=$('[data-station-action="repair"]');if(b){const p=this.repairPlan();b.disabled=false;b.classList.toggle('unaffordable',!p.amount);b.textContent=`객차 수리 · HP +${p.amount.toFixed(1)} / ¤ ${p.cost}`;}markCosts();};
 function markCosts(){if(!g.state)return;document.querySelectorAll('[data-station-action],[data-upgrade-id],[data-run-upgrade]').forEach(b=>{let cost=0,resource='money';const a=b.dataset.stationAction,i=Number(b.dataset.index);if(a==='repair'){b.classList.toggle('unaffordable',!g.repairPlan().amount);return;}if(a==='buy')cost=g.stationOffers.gear[i].d.price;if(a==='recruit')cost=g.stationCrewPrice(i);if(a==='car')cost=B.station.carPrices[g.state.cars.length-B.train.startingCars]||0;if(b.dataset.upgradeId){resource='scrap';cost=g.upgradeCost(g.findEquipment(b.dataset.upgradeId))||0;}if(b.dataset.runUpgrade){resource='scrap';const id=b.dataset.runUpgrade;cost=PROGRESSION_CONFIG.upgrades[id].costs[g.state.runUpgrades?.[id]||0]||0;}const poor=g.state[resource]<cost;b.classList.toggle('unaffordable',poor);if(poor)b.disabled=false;});}
 const captain=g.renderCaptain.bind(g);g.renderCaptain=function(){captain();markCosts();};
 const meta=g.showMeta.bind(g);g.showMeta=function(){meta();document.querySelectorAll('[data-meta]').forEach(b=>{const d=D.META_UPGRADES[b.dataset.meta],cost=d.costs[Number(this.meta.upgrades[b.dataset.meta])||0];b.classList.toggle('unaffordable',cost!==undefined&&this.meta.relics<cost);});};
 const equipment=g.equipmentHTML.bind(g);g.equipmentHTML=function(...a){return equipment(...a).replace('직원 능력·출력 2 이상은 모듈을 추가 증폭하지 않습니다.',`직원 능력은 모듈을 증폭하지 않습니다. 출력 2: 효과량 ×${R.modulePower[2]}, 출력 3: ×${R.modulePower[3]}.`);};
 document.addEventListener('click',e=>{if(e.target.closest('.unaffordable'))g.toast('자원 또는 실행 조건이 부족합니다.');},true);
 const css=document.createElement('style');css.textContent='.event-modal .choice-card,#event-placement-panel .choice-card{display:block!important;grid-template-columns:none!important;width:100%;text-align:center;white-space:normal;word-break:keep-all;overflow-wrap:break-word;min-height:48px}.event-modal .choice-card>div{width:100%;max-width:none!important;text-align:left}.event-modal .choice-card p{margin:6px 0}.unaffordable{color:#b6babc!important;background:#5a606333!important;border-color:#7e858766!important;opacity:.8}.unaffordable *{color:inherit!important}.station-backdrop{position:absolute;left:50%;bottom:165px;width:min(1450px,120vw);height:auto;max-width:none;max-height:72vh;object-fit:contain;object-position:center bottom;transform:translateX(-50%);transform-origin:center bottom;pointer-events:none;z-index:4}.station-backdrop[hidden]{display:none}.crew-sprite{touch-action:manipulation}.station-backdrop~*{pointer-events:inherit}@media(max-width:700px){.station-backdrop{bottom:175px;width:165vw;max-height:62vh}}@media(max-height:650px) and (min-width:701px){.station-backdrop{bottom:130px;width:min(1320px,120vw);max-height:68vh}}';document.head.append(css);
 css.textContent+='.train-stopped .wheel{animation-play-state:paused}.station-backdrop{mask-image:radial-gradient(ellipse 72% 68% at 50% 62%,#000 48%,transparent 100%)}';
})();
