(()=>{
 const g=lastRail,F=SAVE_FORMAT,S=SAVE_STORAGE;let box=null,creditsBox=null,selection=0;
 const parse=(key,fallback)=>{const value=localStorage.getItem(key);return value===null?fallback:JSON.parse(value);};
 function snapshot(){const m=JSON.parse(JSON.stringify(g.meta)),codex=parse('lastRailCodexV2',{});return{game:'last-train',saveFormatVersion:F.saveFormatVersion,gameVersion:F.gameVersion,exportedAt:new Date().toISOString(),metaProgress:m,unlocks:F.unlocked(m,codex),upgrades:Object.fromEntries(Object.entries(m.upgrades).filter(([id])=>META_CONFIG.upgrades[id]?.group!=='captain')),captainUpgrades:Object.fromEntries(Object.entries(m.upgrades).filter(([id])=>META_CONFIG.upgrades[id]?.group==='captain')),trainModifications:{unlocked:m.modifications,enabled:m.enabledMods,points:g.modPoints()},apocalypse:{unlocked:m.apocalypseUnlocked,highestClear:m.apocalypseCleared,selected:m.apocalypseSelected},records:{codex,combatReports:parse('lastRailCombatReports',[]),eliteSeen:parse('lastRailEliteSeen',[])},currentRun:parse(RUN_CHECKPOINT_CONFIG.key,null),settings:{volume:parse('lastRailVolume',GAME_DATA.BALANCE.audio.defaultMaster),saveGuideAcknowledged:parse(RUN_CHECKPOINT_CONFIG.warningKey,false)}};}
 function rawSave(s){const raw=Object.fromEntries(S.keys.map(k=>[k,null]));Object.assign(raw,{lastRailMeta:JSON.stringify(s.metaProgress),lastRailCodexV2:JSON.stringify(s.records.codex),lastRailCombatReports:JSON.stringify(Array.isArray(s.records.combatReports)?s.records.combatReports:[]),lastRailEliteSeen:JSON.stringify(Array.isArray(s.records.eliteSeen)?s.records.eliteSeen.filter(id=>typeof id==='string'):[]),lastRailVolume:JSON.stringify(s.settings.volume)});raw[RUN_CHECKPOINT_CONFIG.warningKey]=JSON.stringify(!!(s.settings.saveGuideAcknowledged??s.settings.saveWarningAcknowledged));if(s.currentRun)raw[RUN_CHECKPOINT_CONFIG.key]=JSON.stringify(s.currentRun);return raw;}
 function download(save){const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`last-train-save-v${F.gameVersion}-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
 function close(){selection++;box?.close();box?.remove();box=null;document.querySelector('#save-manager-btn')?.focus();}
 function status(message){if(box)box.querySelector('[data-status]').textContent=message;}
 g.showSaveManager=function(){if(this.mode!=='menu')return;close();box=document.createElement('dialog');box.className='admin-dialog save-manager';box.innerHTML=`<h2>세이브 관리</h2><p>진행 데이터는 현재 브라우저에 자동 저장됩니다. 외부 파일로 내보내면 백업하거나 다른 브라우저·기기로 옮길 수 있습니다.</p><p>공식 주소: <a href="https://pagter54-creator.github.io/last-train/" target="_blank" rel="noopener">pagter54-creator.github.io/last-train/</a><br>같은 주소의 게임 업데이트는 일반적으로 저장을 유지합니다. 사이트 데이터 삭제·비공개 모드·다른 브라우저나 기기·주소 변경 시 파일 백업이 필요합니다.</p><p>0.6 이상 세이브를 지원합니다. 현재 런은 가장 최근 스테이지 시작 체크포인트를 포함하며 전투 도중 상태는 저장하지 않습니다. 파일은 기기에 별도로 보관하세요.</p><div class="save-file-actions"><button data-export>저장 파일 내보내기</button><label>저장 파일 불러오기<input data-import type="file" accept=".json,application/json"></label></div><section data-preview></section><p data-status role="status"></p><button data-close>닫기</button>`;document.body.append(box);box.querySelector('[data-close]').onclick=close;box.addEventListener('cancel',e=>{e.preventDefault();close();});box.querySelector('[data-export]').onclick=()=>{try{download(snapshot());status('저장 파일 다운로드를 요청했습니다. 다운로드 폴더를 확인하세요.');}catch(e){status('내보내기에 실패했습니다. '+e.message);}};
 box.querySelector('[data-import]').onchange=async e=>{const file=e.target.files[0],ticket=++selection;box.querySelector('[data-preview]').replaceChildren();if(!file)return;try{if(file.size>F.maxBytes)throw Error('저장 파일이 너무 큽니다. 최대 8MB까지 지원합니다.');const text=await file.text();if(!box||ticket!==selection)return;let json;try{json=JSON.parse(text,(key,value)=>{if(['__proto__','prototype','constructor'].includes(key))throw Error('잘못된 필드');return value;});}catch{throw Error('올바른 JSON 저장 파일이 아닙니다.');}const result=F.validateSave(json);const preview=box.querySelector('[data-preview]');const info=document.createElement('p');info.textContent=`v${json.gameVersion} · 보유 잔해 ${result.save.metaProgress.relics} · 누적 사용 ${result.save.metaProgress.spent}\n현재 진행상황이 불러온 저장으로 교체됩니다. 기존 데이터는 자동 백업됩니다.\n${result.notes.join('\n')}`;preview.append(info);const cancel=document.createElement('button');cancel.textContent='취소';cancel.onclick=()=>{selection++;preview.replaceChildren();status('불러오기를 취소했습니다.');};const apply=document.createElement('button');apply.textContent='이 저장으로 교체';apply.onclick=()=>{apply.disabled=true;try{S.apply(rawSave(result.save));try{sessionStorage.setItem('lastTrainImportResult',JSON.stringify(['저장 파일을 불러왔습니다.',...result.notes]));}catch{}g.update=()=>{};location.reload();}catch(e){apply.disabled=false;status(e.message);}};preview.append(cancel,apply);status('파일 검사 완료. 적용하려면 교체 버튼을 누르세요.');cancel.focus();}catch(e){status(e.message);}};box.showModal();};
 function closeCredits(){creditsBox?.close();creditsBox?.remove();creditsBox=null;document.querySelector('#credits-btn')?.focus();}
 g.showCredits=function(){
  if(this.mode!=='menu')return;
  closeCredits();
  creditsBox=document.createElement('dialog');
  creditsBox.className='admin-dialog credits-dialog';
  creditsBox.innerHTML=`<div class="credits-head"><small>LAST RAIL · CREDITS</small><h2>크레딧</h2></div><div class="credits-list"><div><span>기획</span><b>정지석</b></div><div><span>사용 모델</span><b>astra</b></div><div><span>이미지</span><b>ChatGPT</b></div><div><span>음악</span><b>Suno AI</b></div></div><p class="credits-note">LAST RAIL을 플레이해 주셔서 감사합니다.</p><button data-close class="credits-close">닫기</button>`;
  document.body.append(creditsBox);
  creditsBox.querySelector('[data-close]').onclick=closeCredits;
  creditsBox.addEventListener('cancel',e=>{e.preventDefault();closeCredits();});
  creditsBox.showModal();
 };
 function mount(){
  const how=document.querySelector('#howto-btn');if(!how)return;
  let save=document.querySelector('#save-manager-btn');
  if(!save){save=document.createElement('button');save.id='save-manager-btn';save.textContent='세이브 관리';save.onclick=()=>g.showSaveManager();how.after(save);}
  if(!document.querySelector('#credits-btn')){const credits=document.createElement('button');credits.id='credits-btn';credits.textContent='크레딧';credits.onclick=()=>g.showCredits();save.after(credits);}
 }
 const menu=g.showMainMenu.bind(g);g.showMainMenu=function(...args){const r=menu(...args);mount();return r;};mount();
 window.addEventListener('keydown',e=>{if(box?.open||creditsBox?.open)e.stopImmediatePropagation();},true);
 const style=document.createElement('style');style.textContent='.menu-actions{flex-wrap:wrap}.save-manager{width:min(660px,92vw)}.save-manager p{line-height:1.7;white-space:pre-line}.save-manager a{color:#b5dcdf}.save-file-actions{display:flex;flex-wrap:wrap;align-items:center;gap:8px}.save-manager input[type=file]{max-width:100%;box-sizing:border-box}.save-manager [data-preview]:not(:empty){border:1px solid #d9b980;padding:12px;margin-top:16px}.credits-dialog{width:min(520px,92vw);padding:0;overflow:hidden;background:linear-gradient(180deg,#172527,#0f1719);color:#e7ece8;border:1px solid #5f706d;border-radius:14px;box-shadow:0 24px 80px #000b}.credits-dialog::backdrop{background:#02090cd9;backdrop-filter:blur(4px)}.credits-head{padding:28px 30px 20px;border-bottom:1px solid #ffffff18;background:#1b2f31}.credits-head small{font-size:11px;letter-spacing:.18em;color:#d8b477}.credits-head h2{margin:6px 0 0;font-size:34px}.credits-list{display:grid;gap:1px;margin:20px 24px;background:#ffffff12;border:1px solid #ffffff14}.credits-list>div{display:grid;grid-template-columns:140px 1fr;align-items:center;padding:14px 16px;background:#111d1f}.credits-list span{color:#8f9c99;font-size:13px}.credits-list b{font-size:18px;color:#efe4c5}.credits-note{margin:18px 24px;color:#8f9c99;font-size:12px}.credits-close{margin:0 24px 24px auto;display:block;padding:9px 18px;border:1px solid #657875;background:#1d2a2c;color:#fff;cursor:pointer;border-radius:6px}.credits-close:hover{border-color:#d8b477;color:#f2d89f}@media(max-width:620px){.credits-list>div{grid-template-columns:105px 1fr}}';document.head.append(style);
 try{const messages=JSON.parse(sessionStorage.getItem('lastTrainImportResult')||'null');if(Array.isArray(messages)){sessionStorage.removeItem('lastTrainImportResult');g.showSaveManager();status(messages.join('\n'));}}catch{}
})();
