/* JANUS rework: split-side targeting, alternating split/merge cycle and Dual Verdict. */
(()=>{
 'use strict';
 const g=lastRail,D=GAME_DATA,C=UPDATE09.janus,A=LAST_RAIL_SCENE,B=D.BALANCE;
 const active=()=>g.state?.battle?.bossId==='janus';
 const live=p=>p&&!p.destroyed&&p.hp>0;
 const old={};for(const key of ['startBoss','updateBoss','damageEnemy','checkBattleState','bossCrewReturnFire','targetInRange','inspectEnemy','bossCodexHTML','pickTurretTarget','turretTargets','turretCooling'])if(g[key])old[key]=g[key].bind(g);
 function notice(text){const b=g.state.battle;b.notice=text;b.noticeLeft=6;g.showBanner('JANUS',text);}
 function wall(){return{connector:Math.max(0,Math.floor(g.state.cars.length/2)-1),hp:C.wallHp,maxHp:C.wallHp};}
 function homes(swapped){return swapped?[[.83,.55],[.28,.35]]:[[.28,.35],[.83,.55]];}
 /* Movement animation is intentionally preserved from the original 0.9 JANUS implementation. */
 function moveTo(points){const seconds=window.ESCALATION09?.motion.janusTravel||1.6;g.state.battle.parts.forEach((p,i)=>{p.travel09={from:[p.x,p.y],to:points[i],left:seconds,total:seconds};});}
 // Legacy animation signature retained for static compatibility: moveTo(homes(j.swapped))
 function animate(dt){for(const p of g.state.battle.parts){const m=p.travel09;if(m){m.left=Math.max(0,m.left-dt);const t=1-m.left/m.total,ease=t*t*(3-2*t);p.x=m.from[0]+(m.to[0]-m.from[0])*ease;p.y=m.from[1]+(m.to[1]-m.from[1])*ease;if(!m.left)delete p.travel09;}const target=p.x<.55?1:-1;p.facing09??=target;p.facing09+=(target-p.facing09)*(1-Math.exp(-(window.ESCALATION09?.motion.janusTurn||5)*dt));}}
 function splitIndex(){return g.state.battle?.janus09?.wall?.connector??Math.max(0,Math.floor(g.state.cars.length/2)-1);}
 function carSide(ci){return ci<=splitIndex()?'left':'right';}
 function partSide(p){return p.x<.55?'left':'right';}
 function eligibleCars(p,exclude=[]){const s=g.state,side=partSide(p);return s.cars.map((c,i)=>({c,i})).filter(x=>x.c.hp>0&&!x.c.destroyed&&!exclude.includes(x.i)&&(s.battle.janus09.phase==='merge'||carSide(x.i)===side));}
 function weightedEntry(list){if(!list.length)return null;const weights=list.map(x=>g.bossTargetWeight09?.(x)??1),total=weights.reduce((a,b)=>a+b,0);let roll=Math.random()*total;for(let i=0;i<list.length;i++){roll-=weights[i];if(roll<=0)return list[i];}return list.at(-1);}
 function randomCar(p,exclude=[]){return weightedEntry(eligibleCars(p,exclude));}
 function weightedSample(list,count){const pool=[...list],out=[];while(pool.length&&out.length<count){const picked=weightedEntry(pool);if(!picked)break;out.push(picked);pool.splice(pool.indexOf(picked),1);}return out;}
 function turretOrdinal(eq,ci){let n=0;for(let i=0;i<g.state.cars.length;i++)for(const item of g.state.cars[i].equipment||[])if(item.kind==='turret'){if(item===eq)return n;n++;}return Math.max(0,ci||0);}
 function damageHull(ci,amount,crewDamage=0){const car=g.state.cars[ci];if(!car||car.hp<=0||car.armor>0)return;const before={car:car.hp,crew:g.state.crew.map(c=>({id:c.id,hp:c.hp,dead:c.dead}))};car.hp=Math.max(0,car.hp-g.absorbHullDamage(ci,amount));car.hitFlash=.2;for(const c of g.state.crew.filter(c=>!c.dead&&!c.moving&&c.car===ci))if(crewDamage>0)g.hurtCrew(c,crewDamage,'attack');g.onHullImpact(ci,before);}
 function heatCar(ci,amount){const car=g.state.cars[ci];if(!car||car.hp<=0)return;for(const eq of car.equipment)if(eq.kind==='turret'){eq.heat=Math.min(B.heat.max,(eq.heat||0)+amount);if(eq.heat>=B.heat.max)eq.overheated=true;}}
 function telegraph(kind,part,cars,seconds=C.warning,payload={}){const j=g.state.battle.janus09;j.telegraphs.push({kind,part:part?.type||null,cars:[...cars],left:seconds,total:seconds,payload,resolved:false});}
 function spawnHeatDrone(ci){const s=g.state,before=s.enemies.length;g.spawnEnemy('janusHeatDrone');if(s.enemies.length===before)return;const e=s.enemies.at(-1);e.hp=e.maxHp=C.heatDroneHp;e.targetCar=ci;e.boarded=true;e.attached=true;e.x=B.battle.boardDistance;e.y=.48;e.attackTimer=999;e.janusHeatDrone=true;e.name='발열 드론';g.playSound('steam');}
 function currentThreatBudget(){const s=g.state,stage=g.globalStage(),local=s.stageIndex+1,custom=COMBAT_CONFIG.stageOverrides[s.actId]?.[local]||{},base=custom.budget??COMBAT_CONFIG.budgets[Math.min(stage-1,COMBAT_CONFIG.budgets.length-1)]??0;return base*COMBAT_CONFIG.swarm.budgetMultiplier*(g.escalationRules09?.().threat??1);}
 function summonThreatWave(){
  const s=g.state,stage=g.globalStage(),hasStaffed=s.cars.some((car,ci)=>car.hp>0&&!car.destroyed&&s.crew.some(c=>!c.dead&&c.hp>0&&c.car===ci));
  const pool=Object.entries(D.ENEMIES).filter(([id,d])=>!d.elite&&!['janusHeatDrone'].includes(id)&&(d.rhythmMinStage??d.fromStage??1)<=stage&&(d.threatCost||0)>0&&(hasStaffed||!d.boards));
  if(!pool.length)return;let budget=currentThreatBudget(),room=Math.max(0,B.battle.maxAlive-s.enemies.filter(e=>!e.dead).length),spawned=0;const cheapest=Math.min(...pool.map(([,d])=>d.threatCost));
  while(room>0&&budget>=cheapest){const options=pool.filter(([,d])=>d.threatCost<=budget);if(!options.length)break;const choice=options[Math.floor(Math.random()*options.length)],before=s.enemies.length;g.spawnEnemy(choice[0]);if(s.enemies.length===before)break;const spawnedEnemy=s.enemies.at(-1);if(choice[1].boards){const staffed=s.cars.map((c,i)=>({c,i})).filter(x=>x.c.hp>0&&!x.c.destroyed&&s.crew.some(c=>!c.dead&&c.hp>0&&c.car===x.i));const target=weightedEntry(staffed);if(!target){spawnedEnemy.dead=true;continue;}spawnedEnemy.targetCar=target.i;spawnedEnemy.bossBoarder09=true;}budget-=choice[1].threatCost;room--;spawned++;}
  notice(`파괴형 증원 호출 · 비정예 ${spawned}기 투입`);
 }
 function resolveTelegraph(t){if(t.resolved)return;t.resolved=true;const part=g.state.battle.parts.find(p=>p.type===t.part);
  if(t.kind==='crusherHeavy'){const ci=t.cars[0],car=g.state.cars[ci];if(car?.hp>0)damageHull(ci,Math.max(1,car.hp*C.heavyCurrentHpRatio),C.crewDamage);g.playSound('cannonBass');}
  else if(t.kind==='crusherMulti'){for(const ci of t.cars){const car=g.state.cars[ci];if(car?.hp>0)damageHull(ci,Math.max(1,car.maxHp*C.multiMaxHpRatio),Math.max(0,C.crewDamage*.5));}g.playSound('hull');}
  else if(t.kind==='heaterShot'){for(const ci of t.cars)heatCar(ci,C.heatShot);g.playSound('steam');}
  else if(t.kind==='heatDrone'){for(const ci of t.cars)spawnHeatDrone(ci);}
  else if(t.kind==='verdict'){resolveVerdict(t);}
  if(part)g.state.battle.janus09.shot={car:t.cars[0],left:.3,part:part.type};
 }
 function startCrusherPattern(part,exclude=[]){const choices=['heavy','multi','summon'],pick=choices[Math.floor(Math.random()*choices.length)];if(pick==='summon'){summonThreatWave();return[];}if(pick==='heavy'){const target=randomCar(part,exclude);if(target){telegraph('crusherHeavy',part,[target.i],C.heavyWarning);return[target.i];}return[];}const targets=eligibleCars(part,exclude),count=Math.min(targets.length,C.multiTargets),cars=weightedSample(targets,count).map(x=>x.i);if(cars.length)telegraph('crusherMulti',part,cars,C.multiWarning);return cars;}
 function startHeaterPattern(part,exclude=[]){const target=randomCar(part,exclude);if(!target)return[];if(Math.random()<.55)telegraph('heaterShot',part,[target.i],C.heatWarning);else telegraph('heatDrone',part,[target.i],C.droneWarning);return[target.i];}
 function startSplitAttack(){const b=g.state.battle,j=b.janus09,crusher=b.parts.find(p=>p.type==='janusCrusher'),heater=b.parts.find(p=>p.type==='janusHeater');if(live(crusher))startCrusherPattern(crusher);if(live(heater))startHeaterPattern(heater);j.attackLeft=C.attackInterval;}
 function startMergeAttack(){const b=g.state.battle,j=b.janus09,crusher=b.parts.find(p=>p.type==='janusCrusher'),heater=b.parts.find(p=>p.type==='janusHeater'),used=[];if(live(crusher))used.push(...startCrusherPattern(crusher));if(live(heater))startHeaterPattern(heater,used);j.attackLeft=C.mergeAttackInterval;}
 function startVerdict(){const s=g.state,j=s.battle.janus09,cars=s.cars.map((c,i)=>({c,i})).filter(x=>x.c.hp>0&&!x.c.destroyed);if(cars.length<1)return;const marks={};cars.forEach((x,n)=>marks[x.i]=n%2===0?'destroy':'heat');if(cars.length>1&&Math.random()<.5){const a=cars[Math.floor(Math.random()*cars.length)].i;marks[a]=marks[a]==='destroy'?'heat':'destroy';}j.verdict={marks,flipped:false,left:C.verdictWarning,total:C.verdictWarning};telegraph('verdict',null,cars.map(x=>x.i),C.verdictWarning,{marks});notice('쌍면 판결 · 객차 표식을 확인하세요');}
 function flipVerdict(){const j=g.state.battle.janus09,v=j.verdict;if(!v||v.flipped)return;const keys=Object.keys(v.marks).map(Number);if(keys.length>1){keys.sort(()=>Math.random()-.5);const count=Math.max(1,Math.floor(keys.length*C.verdictFlipRatio));for(const ci of keys.slice(0,count))v.marks[ci]=v.marks[ci]==='destroy'?'heat':'destroy';for(const t of j.telegraphs)if(t.kind==='verdict'&&!t.resolved)t.payload.marks={...v.marks};notice('쌍면 판결 · 일부 표식 반전');}v.flipped=true;}
 function resolveVerdict(t){const j=g.state.battle.janus09,marks=t.payload.marks||j.verdict?.marks||{};for(const [key,mark] of Object.entries(marks)){const ci=Number(key),car=g.state.cars[ci];if(!car||car.hp<=0)continue;if(mark==='destroy')damageHull(ci,Math.max(1,car.hp*C.verdictCurrentHpRatio),0);else{heatCar(ci,C.verdictHeat);car.janusHeatLock=Math.max(car.janusHeatLock||0,C.verdictCoolingDebuff);}}j.vulnerableLeft=C.vulnerableSeconds;j.verdict=null;notice(`쌍면 판결 종료 · JANUS 과부하 ${C.vulnerableSeconds}초`);g.playSound('explosion');}
 function enterMerge(){const b=g.state.battle,j=b.janus09;if(j.phase==='merge')return;j.phase='merge';j.phaseLeft=C.mergeSeconds;j.wall=null;j.attackLeft=C.mergeAttackDelay;j.verdictClock=C.verdictDelay;j.verdictDone=false;moveTo([[.48,.38],[.60,.38]]);notice('중앙 합체 · 좌우 제한 해제 / 양 차량 동시 피해');}
 function enterSplit(){const b=g.state.battle,j=b.janus09;j.phase='combat';j.phaseLeft=0;j.splitClock=0;j.attackLeft=C.splitAttackDelay;j.wall=wall();j.verdict=null;moveTo(homes(false));notice('JANUS 분리 · 봉쇄벽 전개 경고');j.wallArmLeft=C.wallDeployDelay;}
 g.startBoss=function(id){const r=old.startBoss(id);if(id!=='janus')return r;const b=this.state.battle;b.rework=false;b.arrivalLeft=0;b.defeated=false;b.janus09={phase:'combat',phaseLeft:0,splitClock:0,wall:null,wallArmLeft:C.wallDeployDelay,attackLeft:C.splitAttackDelay,telegraphs:[],vulnerableLeft:0,verdict:null};b.parts.forEach((p,i)=>{p.bossPart=false;p.janusPart=true;p.victory=false;p.x=i?1.2:-.2;p.y=homes(false)[i][1];p.facing09=i?-1:1;});moveTo(homes(false));jArrival();notice('JANUS 분리 · 봉쇄벽 전개 경고');return r;};
 function jArrival(){g.state.battle.janus09.arrival09=window.ESCALATION09?.motion.janusTravel||1.6;}
 g.damageJanusWall09=function(c,dt){const j=this.state.battle?.janus09,w=j?.wall;if(!w||w.hp<=0||c.dead||c.hp<=0||c.moving||![w.connector,w.connector+1].includes(c.car))return false;const combat=Math.max(0,this.effectiveStat(c,'combat')),damage=combat*C.wallDpsPerCombat*dt*(this.crewWeaponMultiplier?.(c)??1);if(damage>0){w.hp=Math.max(0,w.hp-damage);if(!(c.wallShot09>0))this.playSound('shotCrack');c.wallShot09=C.wallVisual;}if(w.hp>0&&this.state.cars[c.car].armor<=0)this.hurtCrew(c,C.wallRetaliation*dt,'attack');if(w.hp<=0){j.wall=null;this.playSound('explosion');notice('봉쇄벽 파괴 · JANUS 중앙 합체');enterMerge();}return true;};
 function crewHeatDrone(c,dt){const e=g.state.enemies.find(e=>!e.dead&&e.janusHeatDrone&&e.targetCar===c.car);if(!e)return false;let damage=Math.max(0,g.effectiveStat(c,'combat'))*B.crew.personalDpsPerCombat*dt*(g.crewWeaponMultiplier?.(c)??1);if(c.traits.includes('marksman'))damage*=D.TRAITS.marksman.damageMult;if(damage>0){g.damageEnemy(e,damage,1);c.wallShot09=C.wallVisual;}return true;}
 g.bossCrewReturnFire=function(c,dt){if(active()){if(crewHeatDrone(c,dt))return true;if(this.state.battle.janus09?.wall?.hp>0)return this.damageJanusWall09(c,dt);}return old.bossCrewReturnFire(c,dt);};
 g.targetInRange=function(e,r){if(e?.janusWall||e?.janusHeatDrone)return false;if(e?.janusPart&&!live(e))return false;return old.targetInRange(e,r);};
 g.turretTargets=function(t,eq){const targets=old.turretTargets(t,eq);return active()?targets.filter(e=>!e.janusHeatDrone):targets;};
 g.pickTurretTarget=function(ci,t,eq){if(!active())return old.pickTurretTarget(ci,t,eq);const s=this.state,b=s.battle,j=b.janus09,focus=s.orders.focus;if(focus.active>0&&focus.target){const forced=[...s.enemies,...b.parts].find(e=>e.id===focus.target&&!e.dead&&!e.destroyed);if(forced)return forced;}if(j.phase==='combat'){const side=carSide(ci),part=b.parts.find(p=>live(p)&&partSide(p)===side);if(part)return part;}const parts=b.parts.filter(live);if(parts.length){const n=turretOrdinal(eq,ci);return parts[n%parts.length];}return old.pickTurretTarget(ci,t,eq);};
 g.turretCooling=function(eq,ci){const base=old.turretCooling(eq,ci);if(!active())return base;const drones=this.state.enemies.filter(e=>!e.dead&&e.janusHeatDrone&&e.targetCar===ci).length,lock=this.state.cars[ci]?.janusHeatLock>0;return base*Math.pow(C.heatDroneCoolingMult,drones)*(lock?C.verdictCoolingMult:1);};
 g.damageEnemy=function(e,damage,pierce=0){if(e?.janusWall)return;if(!e?.janusPart)return old.damageEnemy(e,damage,pierce);const b=this.state.battle;if(!active()||b.defeated||!live(e)||!(damage>0))return;const j=b.janus09,mult=j?.vulnerableLeft>0?C.vulnerableDamageMult:1,targets=j?.phase==='merge'?b.parts.filter(live):[e];for(const p of targets){const armor=Math.max(0,(p.armor||0)-pierce),dealt=damage*mult*(1-Math.min(.9,armor));p.hp=Math.max(0,p.hp-dealt);p.hitFlash=.16;if(p.hp<=0){p.destroyed=true;this.playSound('explosion');}}b.sharedHp=b.parts.reduce((n,p)=>n+p.hp,0);};
 g.updateBoss=function(dt){if(!active())return old.updateBoss(dt);const s=this.state,b=s.battle,j=b.janus09;if(!j)return;for(const e of s.enemies.filter(e=>e.bossBoarder09&&!e.dead&&!e.boarded)){const valid=s.cars[e.targetCar]?.hp>0&&s.crew.some(c=>!c.dead&&c.hp>0&&c.car===e.targetCar);if(!valid){const staffed=s.cars.map((c,i)=>({c,i})).filter(x=>x.c.hp>0&&!x.c.destroyed&&s.crew.some(c=>!c.dead&&c.hp>0&&c.car===x.i)),target=weightedEntry(staffed);if(target)e.targetCar=target.i;else e.dead=true;}}animate(dt);if(j.arrival09>0){j.arrival09=Math.max(0,j.arrival09-dt);if(!j.arrival09)j.wallArmLeft=C.wallDeployDelay;return;}for(const p of b.parts)p.hitFlash=Math.max(0,(p.hitFlash||0)-dt);for(const c of s.crew)c.wallShot09=Math.max(0,(c.wallShot09||0)-dt);for(const car of s.cars){car.janusHeatLock=Math.max(0,(car.janusHeatLock||0)-dt);}b.noticeLeft=Math.max(0,(b.noticeLeft||0)-dt);j.vulnerableLeft=Math.max(0,(j.vulnerableLeft||0)-dt);if(j.shot)j.shot.left=Math.max(0,j.shot.left-dt);if(b.defeated){b.defeatFadeLeft=Math.max(0,b.defeatFadeLeft-dt);return;}
  for(const t of j.telegraphs){t.left=Math.max(0,t.left-dt);if(t.kind==='verdict'&&j.verdict){j.verdict.left=t.left;if(!j.verdict.flipped&&t.left<=C.verdictFlipAt)flipVerdict();}if(!t.left)resolveTelegraph(t);}j.telegraphs=j.telegraphs.filter(t=>!t.resolved);
  if(j.phase==='combat'){if(j.wallArmLeft>0){j.wallArmLeft=Math.max(0,j.wallArmLeft-dt);if(!j.wallArmLeft&&!j.wall){j.wall=wall();notice('봉쇄벽 전개 · 좌우 전선 분리');}}j.splitClock+=dt;if(j.splitClock>=C.splitSeconds){enterMerge();return;}j.attackLeft-=dt;if(j.attackLeft<=0&&j.wallArmLeft<=0)startSplitAttack();}
  else if(j.phase==='merge'){j.phaseLeft=Math.max(0,j.phaseLeft-dt);j.verdictClock=Math.max(0,j.verdictClock-dt);if(!j.verdictDone&&j.verdictClock<=0){j.verdictDone=true;startVerdict();}j.attackLeft-=dt;if(j.attackLeft<=0&&!j.verdict)startMergeAttack();if(!j.phaseLeft&&!j.verdict){enterSplit();return;}}
 };
 g.checkBattleState=function(){if(!active())return old.checkBattleState();const s=this.state,b=s.battle;if(this.hasTrainMod?.('captain')&&s.crew.some(c=>c.captain&&c.dead))return this.gameOver('현장 열차장이 사망했습니다.');if(s.cars.every(c=>c.hp<=0))return this.gameOver('모든 객차가 파괴되었습니다.');if(s.titanDistance<=D.BALANCE.titan.forcedBattleAt)return this.gameOver('타이탄이 열차를 따라잡았습니다.');if(b.parts.every(p=>!live(p))){if(!b.defeated){b.defeated=true;b.defeatFadeLeft=2;b.janus09.wall=null;for(const e of s.enemies)e.dead=true;notice('JANUS 격파');}if(b.defeatFadeLeft<=0)return this.bossClear();}};
 g.inspectEnemy=function(e){if(!e?.janusPart)return old.inspectEnemy(e);document.querySelector('#inspector').innerHTML=`<h3>${e.name}</h3><p>내구 ${Math.ceil(e.hp)} / ${e.maxHp} · 장갑 ${Math.round(e.armor*100)}%</p><p>${e.type==='janusCrusher'?'파괴형 · 강습/다중 포격/비정예 증원':'과열형 · 과열탄/발열 드론'}</p><p>분리 중에는 같은 측 객차만 공격합니다. 합체 중 한 차량을 맞히면 양 차량에 피해가 누적됩니다.</p>${this.state.battle.janus09?.vulnerableLeft>0?'<p>과부하 · 받는 피해 +25%</p>':''}`;};
 g.bossCodexHTML=function(id){
  if(id!=='janus')return old.bossCodexHTML(id);
  const boss=D.BOSSES.janus,crusher=boss.parts.find(p=>p.type==='janusCrusher'),heater=boss.parts.find(p=>p.type==='janusHeater');
  const pct=v=>`${Math.round(v*1000)/10}%`,rows=[
   ['총 내구',`${boss.sharedHp} · 두 개체 내구의 합`],
   ['JANUS · 파괴형',`HP ${crusher.hp} · 장갑 ${Math.round(crusher.armor*100)}% · 강공격 / 다중 포격 / 비정예 증원`],
   ['JANUS · 과열형',`HP ${heater.hp} · 장갑 ${Math.round(heater.armor*100)}% · 과열탄 / 발열 드론`],
   ['분리 상태',`${C.splitSeconds}초 · 중앙 봉쇄벽을 기준으로 좌·우 전선 분리 · 각 JANUS는 자기 측 객차만 공격`],
   ['봉쇄벽',`HP ${C.wallHp} · 직원 개인화기만 공격 가능 · 전투 1당 초당 ${C.wallDpsPerCombat} 피해 · 공격 중 초당 ${C.wallRetaliation} 반격 피해`],
   ['분리 공격 주기',`${C.attackInterval}초 · 집중 사격은 좌우 조준 제한보다 우선`],
   ['파괴형 강공격',`${C.heavyWarning}초 경고 · 대상 객차 현재 HP의 ${pct(C.heavyCurrentHpRatio)} 피해`],
   ['파괴형 다중 포격',`${C.multiWarning}초 경고 · 최대 ${C.multiTargets}개 객차 · 각 객차 최대 HP의 ${pct(C.multiMaxHpRatio)} 피해`],
   ['파괴형 증원',`현재 스테이지 위협 예산만큼 비정예 적을 호출 · 승선형 적은 직원이 있는 객차만 목표`],
   ['과열탄',`${C.heatWarning}초 경고 · 대상 객차 포탑 발열 +${C.heatShot}`],
   ['발열 드론',`${C.droneWarning}초 경고 · HP ${C.heatDroneHp} · 부착 중 해당 객차 냉각 ×${C.heatDroneCoolingMult}`],
   ['중앙 합체',`${C.mergeSeconds}초 지속 · 좌우 제한 해제 · 두 계열 패턴 동시 사용 · 한 개체에 준 피해가 살아 있는 양쪽 개체에 함께 적용`],
   ['합체 공격 주기',`${C.mergeAttackInterval}초 · 두 계열이 가능하면 서로 다른 객차를 우선 목표`],
   ['쌍면 판결',`${C.verdictWarning}초 경고 · 종료 ${C.verdictFlipAt}초 전에 일부 표식 반전 가능 · 파괴 표식은 현재 HP ${pct(C.verdictCurrentHpRatio)} 피해 · 과열 표식은 발열 +${C.verdictHeat}`],
   ['판결 냉각 방해',`과열 표식 적중 시 ${C.verdictCoolingDebuff}초간 냉각 ×${C.verdictCoolingMult}`],
   ['과부하',`쌍면 판결 종료 후 ${C.vulnerableSeconds}초 · 받는 피해 ×${C.vulnerableDamageMult}`]
  ];
  return '<p>JANUS는 파괴형과 과열형 두 개체가 한 전투를 공유하는 ACT III 보스입니다. 분리 상태에서는 열차 중앙을 봉쇄해 전선을 둘로 나누고, 일정 시간이 지나거나 봉쇄벽이 파괴되면 중앙에서 합체합니다.</p><p>파괴형은 객차 내구를 직접 깎는 공격과 증원 호출로 압박하고, 과열형은 포탑 발열과 냉각 방해로 화력을 무너뜨립니다. 합체 상태에서는 두 계열을 동시에 사용하므로 객차별 전력·냉각·직원 배치를 함께 관리해야 합니다.</p><table class="codex-table">'+rows.map(([k,v])=>`<tr><th>${k}</th><td>${v}</td></tr>`).join('')+'</table><p>공략 핵심: 분리 중에는 각 전선의 화력을 균형 있게 유지하고, 봉쇄벽은 인접 객차 직원으로 빠르게 파괴할 수 있습니다. 합체 후 쌍면 판결이 끝난 직후의 과부하 시간이 가장 큰 화력 집중 기회입니다.</p>';
 };
})();
