(()=>{
 const g=lastRail,D=GAME_DATA;
 const style=document.createElement('style');style.textContent=`
 #world-stage .railcar .car-name{left:8px!important;right:8px!important;top:23px!important;width:auto!important;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
 #world-stage .railcar .car-health-row{position:absolute;left:42px;right:42px;bottom:3px;height:17px;display:flex;align-items:center;gap:5px;min-width:0;z-index:3;pointer-events:none}
 #world-stage .railcar .car-health-value{flex:0 1 auto;min-width:0;max-width:70%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:10px/17px sans-serif;font-variant-numeric:tabular-nums;color:#f0ede2;text-shadow:0 1px 2px #000;background:#112025d9;border-radius:2px;padding:0 2px}
 #world-stage .railcar .hull-hp{position:relative;inset:auto;flex:1 1 0;min-width:0;width:auto;height:7px;margin:0;border:1px solid #17292d;background:#112025;border-radius:3px;overflow:hidden}
 #world-stage .railcar .hull-hp i{height:100%;display:block}
 `;document.head.append(style);
 g.crewCandidateTemplates=function(count,random=Math.random){const pool=D.CREW_TEMPLATES.filter(c=>!this.state.crew.some(x=>x.name===c.name));for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,count);};
 g.prepareUnexpectedStation=function(random){const oldOffers=this.stationOffers,oldStage=this.stationStage,oldRandom=Math.random;try{Math.random=random;const available=(kind,reg)=>Object.entries(reg).filter(([id])=>this.runContentUnlocked?.(kind,id)??true).sort(()=>random()-.5);this.stationOffers={gear:['turret','module'].flatMap(kind=>available(kind==='turret'?'turrets':'modules',kind==='turret'?D.TURRETS:D.MODULES).slice(0,2).map(([id,d])=>({id,d,kind}))),crew:this.crewCandidateTemplates(D.BALANCE.station.crewOfferCount,random),bought:new Set()};this.prepareActShop();return JSON.parse(JSON.stringify({...this.stationOffers,bought:[]}));}finally{Math.random=oldRandom;this.stationOffers=oldOffers;this.stationStage=oldStage;}};
 const codex=g.showCodex.bind(g);g.showCodex=function(...args){const r=codex(...args);if(this.pauseCodex){const body=document.querySelector('#codex-content')?.parentElement;if(body){const back=document.createElement('button');back.textContent='일시정지로 돌아가기';back.onclick=()=>{this.pauseCodex=false;const speed=this.state.priorSpeed;this.openPause();this.state.priorSpeed=speed;};body.append(back);}}return r;};
 const close=g.closeOverlay.bind(g);g.closeOverlay=function(...args){this.pauseCodex=false;return close(...args);};
 g.clearCombatPresentation=function(){const s=this.state;if(!s)return;for(const key of ['enemies','projectiles','particles','impacts','weaponZones','attackWindups','systemWindups','interference','grabs'])s[key]=[];if(s.battle){for(const key of ['fires','eliteShots'])s.battle[key]=[];s.battle.eliteNotice=null;for(const p of s.battle.parts||[]){p.hitFlash=0;p.muzzle=0;p.grip=0;p.warning=0;}}for(const c of s.cars){c.hitFlash=0;c.impactPulse=0;c.shieldFlash=0;for(const e of c.equipment){e.recoil=0;e.muzzle=0;}}for(const c of s.crew){c.returnFireVisual=null;c.boardShot=0;c.hammerVisual=0;c.hitFlash=0;}this.clearFloatingCombat?.();this.clearRhythmCombat?.();document.querySelectorAll('.moving-sprite').forEach(el=>el.remove());this.renderCars();};
 for(const name of ['battleClear','bossClear']){const old=g[name].bind(g);g[name]=function(...args){const r=old(...args);if(this.mode!=='battle')this.clearCombatPresentation();return r;};}
 const boss=g.drawBoss.bind(g);g.drawBoss=function(...args){if(this.mode==='battle')return boss(...args);};
})();
